### ISSUE TITLE
Immersive portals crashes when using FreeCam and tweakeroo

### ISSUE THREAD

**Issue by iainvm** [qouteall/ImmersivePortalsMod#1014]
Minecraft Version: 1.18.2
Immersive Portals Version: immersive-portals-1.3.3-mc1.18.2-fabric.jar
Free cam mod used: tweakeroo-fabric-1.18.2-0.13.1.jar
Link to other mod: https://www.curseforge.com/minecraft/mc-mods/tweakeroo

When near some immersive portals if I enable Free Cam (Spectator like mode) the client crashes with the following stack trace
```
java.lang.IllegalArgumentException: The validated expression is false
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:183)
	at qouteall.imm_ptl.core.render.PortalRenderer.renderPortals(PortalRenderer.java:62)
	at qouteall.imm_ptl.core.render.RendererUsingStencil.doPortalRendering(RendererUsingStencil.java:57)
	at qouteall.imm_ptl.core.render.RendererUsingStencil.onBeforeTranslucentRendering(RendererUsingStencil.java:48)
	at net.minecraft.class_761.handler$bpd000$onBeforeTranslucentRendering(class_761.java:7024)
	at net.minecraft.class_761.method_22710(class_761.java:1459)
	at net.minecraft.class_757.method_3188(class_757.java:1034)
	at net.minecraft.class_757.redirect$bpa000$redirectRenderingWorld(class_757.java:3134)
	at net.minecraft.class_757.method_3192(class_757.java:813)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

This also happens with other free cam mods like: https://www.curseforge.com/minecraft/mc-mods/free-cam

**Comment by qouteall** [comment]
Seems that it creates a faked camera entity and the camera entity's world will be different to the player's world when multiple client worlds are loaded

**Comment by PeppilipicalFungus** [comment]
I was having problems caused by the same issue but it didnt result in a crash ever. What happened is I would fall through the world when going into free cam in my single player world.

**Comment by jkcoxson** [comment]
This doesn't seem to be an issue with the community built 1.19 tweakeroo and the latest immersive portals.

**Comment by iainvm** [comment]
Even though the community version of the mod is accepted and might not have the issue (I haven't tested). I wouldn't say we should close this issue based on it, since the official tweakaroo is being rewritten and could still have issues when officially released.

Though very useful to know as a work around.
