### ISSUE TITLE
Incompatible with VMP

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#1031]
https://github.com/RelativityMC/VMP-fabric

**Comment by qouteall** [comment]
```
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3898$class_3208 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.loadEntity(ThreadedAnvilChunkStorage:1168)
	at net.minecraft.server.world.ServerChunkManager.loadEntity(ServerChunkManager:472)
	at net.minecraft.server.world.ServerWorld$ServerEntityHandler.startTracking(ServerWorld:1502)
	at net.minecraft.server.world.ServerWorld$ServerEntityHandler.startTracking(ServerWorld:1480)
	at net.minecraft.server.world.ServerEntityManager.startTracking(ServerEntityManager:210)
	at net.minecraft.server.world.ServerEntityManager.addEntity(ServerEntityManager:180)
	at net.minecraft.server.world.ServerEntityManager.addEntity(ServerEntityManager:161)
	at net.minecraft.server.world.ServerWorld.addEntity(ServerWorld:855)
	at net.minecraft.server.world.ServerWorld.spawnEntity(ServerWorld:806)
	at net.minecraft.entity.FallingBlockEntity.spawnFromBlock(FallingBlockEntity:88)
	at net.minecraft.block.FallingBlock.scheduledTick(FallingBlock:45)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.scheduledTick(AbstractBlock:919)
	at net.minecraft.server.world.ServerWorld.tickBlock(ServerWorld:691)
	at net.minecraft.world.tick.WorldTickScheduler.tick(WorldTickScheduler:215)
	at net.minecraft.world.tick.WorldTickScheduler.tick(WorldTickScheduler:98)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:301)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:907)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:851)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:97)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273)
	at java.lang.Thread.run(Thread.java:833)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 25 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectGetMaxTrackDistance(Lnet/minecraft/class_3898$class_3208;)I in vmp.mixins.json:entitytracker.MixinThreadedAnvilChunkStorageEntityTracker from mod vmp failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap vmp-fabric-mc1.18.2-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 28 more
```

**Comment by qouteall** [comment]
~~This cannot be fixed because VMP assumes that only the chunks near player is visible to player, but with immptl remote chunks can also become visible via portals.~~

**Comment by Poopooracoocoo** [comment]
Would you consider adding this incompatibility to your fabric mod json?

**Comment by Senjosei** [comment]
Found another issue while making my modpack. https://github.com/RelativityMC/VMP-fabric/issues/59
