### ISSUE TITLE
Incompatible with Twilight Forest

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#1133]
https://streamable.com/mlud9n

**Comment by qouteall** [comment]
```
 java.lang.IndexOutOfBoundsException: readerIndex(6359) + length(1) exceeds writerIndex(6359): UnpooledHeapByteBuf(ridx: 6359, widx: 6359, cap: 6359/6359)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-all-4.1.68.Final.jar:?]
	at net.minecraft.network.FriendlyByteBuf.readByte(FriendlyByteBuf.java:1013) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.network.FriendlyByteBuf.readVarInt(FriendlyByteBuf.java:344) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.network.FriendlyByteBuf.readLongArray(FriendlyByteBuf.java:269) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.network.FriendlyByteBuf.readLongArray(FriendlyByteBuf.java:265) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.world.level.chunk.PalettedContainer.read(PalettedContainer.java:163) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.world.level.chunk.LevelChunkSection.read(LevelChunkSection.java:170) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.world.level.chunk.LevelChunk.replaceWithPacketData(LevelChunk.java:445) ~[minecraft-project-@-merged-named.jar:?]
	at qouteall.imm_ptl.core.chunk_loading.MyClientChunkManager.replaceWithPacketData(MyClientChunkManager.java:121) ~[imm_ptl_core-v1.4.8-1.18.jar:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.updateLevelChunk(ClientPacketListener.java:661) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.handleLevelChunkWithLight(ClientPacketListener.java:656) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.handle(ClientboundLevelChunkWithLightPacket.java:45) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.handle(ClientboundLevelChunkWithLightPacket.java:12) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.network.protocol.PacketUtils.method_11072(PacketUtils.java:22) ~[minecraft-project-@-merged-named.jar:?]
	at qouteall.imm_ptl.core.ClientWorldLoader.lambda$withSwitchedWorld$11(ClientWorldLoader.java:486) ~[imm_ptl_core-v1.4.8-1.18.jar:?]
	at qouteall.imm_ptl.core.ClientWorldLoader.withSwitchedWorld(ClientWorldLoader.java:468) ~[imm_ptl_core-v1.4.8-1.18.jar:?]
	at qouteall.imm_ptl.core.ClientWorldLoader.withSwitchedWorld(ClientWorldLoader.java:485) ~[imm_ptl_core-v1.4.8-1.18.jar:?]
```

**Comment by qouteall** [comment]
Update: I tested the latest Fabric version twilight forest with ImmPtl and the chunk loading issue seems fixed.

But there is a new issue that causes crash:
```
java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract int modifyColor(double, double, int)' of abstract class net.minecraft.world.level.biome.BiomeSpecialEffects$GrassColorModifier.
	at net.minecraft.world.level.biome.Biome.getGrassColor(Biome.java:275)
	at net.minecraft.client.multiplayer.ClientLevel.calculateBlockTint(ClientLevel.java:796)
	at net.minecraft.client.multiplayer.ClientLevel.method_38538(ClientLevel.java:112)
	at net.minecraft.client.color.block.BlockTintCache.getColor(BlockTintCache.java:91)
	at net.minecraft.client.multiplayer.ClientLevel.getBlockTint(ClientLevel.java:778)
	at net.minecraft.client.renderer.chunk.RenderChunkRegion.getBlockTint(RenderChunkRegion.java:67)
	at net.minecraft.client.renderer.BiomeColors.getAverageColor(BiomeColors.java:14)
	at net.minecraft.client.renderer.BiomeColors.getAverageGrassColor(BiomeColors.java:18)
	at net.minecraft.client.color.block.BlockColors.method_1693(BlockColors.java:48)
	at net.minecraft.client.color.block.BlockColors.getColor(BlockColors.java:112)
	at net.minecraft.client.renderer.block.ModelBlockRenderer.putQuadData(ModelBlockRenderer.java:134)
	at net.minecraft.client.renderer.block.ModelBlockRenderer.renderModelFaceAO(ModelBlockRenderer.java:120)
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateWithAO(ModelBlockRenderer.java:77)
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:48)
	at net.minecraft.client.renderer.block.BlockRenderDispatcher.renderBatched(BlockRenderDispatcher.java:61)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.redirect$cbf000$hookChunkBuildTesselate(ChunkRenderDispatcher.java:791)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.compile(ChunkRenderDispatcher.java:578)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.doTask(ChunkRenderDispatcher.java:489)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.method_22757(ChunkRenderDispatcher.java:140)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by Zarepheth** [comment]
I've currently got Immersive Portal (Fabric) running with Twilight Forest (Fabric). So far, no problems, but I've not been inspecting the logs for non-crash errors.

I've been able to travel between overworld and nether via two currently active portals (both are Immersive Portal portals that are operating correctly). I also have one active portal between the overworld and the twilight forest. This is a normal Twilight Forest portal, no Immersive Portal effects, and it also operates correctly.

I suppose I should try a nether portal from the twilight forest and see what happens... (or maybe I shouldn't???)

My Curse Forge profile on the Overwolf client is based upon the "[Better MC [FABRIC] 1.19.2 v9](https://www.curseforge.com/minecraft/modpacks/better-mc-fabric)" mod pack, though I've added lots of mods beyond what @xSHXRKIEx put in it.

**Comment by Lassnik** [comment]
NVIDIA 1060 6GB

AMD Ryzen 5600X 6-Core 3701 MHz

16,0 GB RAM

B550 AORUS ELITE V2

Windows 10 64-Bit

Fabric 1.19.2 0.14.12

Immersive Portals and The Twilight Forrest causes huge lag spikes (without 400 - 500 fps, with Twilight Forrest 50 - 200 fps). In my Mod pack with 90 more mods (and Immersive Portals) the fps are stable but terrible (without Twilight Forrest in my Mod pack 200 - 300 fps, with Twilight Forrest in my Mod pack 30 - 50 fps).

Btw, I personally don't care about a fix, but just wanted to say this, so others don't have to go through testing like I did to figure it out. And of course, I decided myself for Immersive Portals in my Mod pack c:

**Comment by Adzeiros** [comment]
> I've currently got Immersive Portal (Fabric) running with Twilight Forest (Fabric). So far, no problems, but I've not been inspecting the logs for non-crash errors.
> 
> I've been able to travel between overworld and nether via two currently active portals (both are Immersive Portal portals that are operating correctly). I also have one active portal between the overworld and the twilight forest. This is a normal Twilight Forest portal, no Immersive Portal effects, and it also operates correctly.
> 
> I suppose I should try a nether portal from the twilight forest and see what happens... (or maybe I shouldn't???)
> 
> My Curse Forge profile on the Overwolf client is based upon the "[Better MC [FABRIC] 1.19.2 v9](https://www.curseforge.com/minecraft/modpacks/better-mc-fabric)" mod pack, though I've added lots of mods beyond what @xSHXRKIEx put in it.

How did you get Immersive Portals to work with Better MC? Mine crashes anytime I launch with this mod.

**Comment by Zarepheth** [comment]
> How did you get Immersive Portals to work with Better MC? Mine crashes anytime I launch with this mod.

I did not do anything special. I just added it via the CurseForge Overwolf client.

I have not used that profile for several weeks, as I'm currently playing some other games. When I finish with these games, and probably finish reading some novels, I'll likely return to Minecraft.

@Adzeiros : Do you have crash logs when combining Immersive Portals with the Better MC mod pack? And is it the same version and edition as I'm using?
