### ISSUE TITLE
Crash client on Velocity proxy

### ISSUE THREAD

**Issue by Siorinex** [qouteall/ImmersivePortalsMod#1142]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

No

### Describe the issue

I use Velocity proxy + server`s on Fabric with ImmPtl
If I on Server 2 go to other dimmension (End, Nether, IP demo or Datapack CustomDimmension), exit from server and teleport from Server 1 (Overworld) to Server 2 - Client crush with 255 error on "Loading terrain...".

If delete ImmPtl - normal.
If I direct connect to server - normal.
If on Server 1 and 2 - Overworld - normal.
If I teleport from Server 2 (Nether or other) to Server 1 (Overworld) - crush...

### Post the log here

```shell
https://paste.gg/p/anonymous/89f22388be024917b5e686cbf56f7823 - full log

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 7/18/22, 2:47 PM
Description: Unexpected error

java.lang.IllegalArgumentException: The validated expression is false
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:183)
	at qouteall.imm_ptl.core.ClientWorldLoader.initializeIfNeeded(ClientWorldLoader.java:310)
	at qouteall.imm_ptl.core.render.context_management.RenderStates.updatePreRenderInfo(RenderStates.java:77)
	at net.minecraft.class_757.handler$bnk000$onFarBeforeRendering(class_757.java:4567)
	at net.minecraft.class_757.method_3192(class_757.java)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:183)
	at qouteall.imm_ptl.core.ClientWorldLoader.initializeIfNeeded(ClientWorldLoader.java:310)
	at qouteall.imm_ptl.core.render.context_management.RenderStates.updatePreRenderInfo(RenderStates.java:77)
	at net.minecraft.class_757.handler$bnk000$onFarBeforeRendering(class_757.java:4567)

-- Affected level --
Details:
	All players: 1 total; [class_746['Siorinex'/5516, l='ClientWorld minecraft:overworld', x=5.28, y=61.00, z=-8.40]]
	Chunk stats: Client Chunks (ImmPtl) 0
	Level dimension: immersive_portals:alternate5
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Server brand: YourServer (fabric)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, mirrors2, continuity/glass_pane_culling_fix, continuity/default, dakota-s-sodium-connected-textures.zip, Better+Clear+Glass+Bordered+1.18.zip

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 5.4.0-121-generic
	Java Version: 17.0.3, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 3104301408 bytes (2960 MiB) / 3972005888 bytes (3788 MiB) up to 6291456000 bytes (6000 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-3330 CPU @ 3.00GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: unknown
	Frequency (GHz): 3.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: GF119 [GeForce GT 610]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 160.00
	Graphics card #0 deviceId: 0x104a
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 6003.95
	Virtual memory used (MB): 8679.68
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 1249.09
	JVM Flags: 2 total; -Xms1000m -Xmx6000m
	Fabric Mods: 
		architectury: Architectury 4.5.76
		chiselsandbits: Chisels & Bits 1.2.113
		cloth-config: Cloth Config v6 6.2.57
			cloth-basic-math: cloth-basic-math 0.6.0
		computercraft: CC: Restitched 1.100.8
			cloth-utils-v1: Cloth Utils v1 2.0.54
			com_electronwill_night-config_core: core 3.6.3
			com_electronwill_night-config_toml: toml 3.6.3
		continuity: Continuity 1.1.0+1.18.2
		create: Create mc1.18.2_v0.4.1+637
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.3.0
			flywheel: Flywheel 1.18-0.7.0.26
			forge_tags: Forge Tags 2.1
			forgeconfigapiport: Forge Config API Port 3.2.0
			milk: Milk Lib 0.3.2
				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
			noindium: No Indium? 1.0.1+1.18.2
				omega-config: OmegaConfig 1.2.3-1.18.1
			porting_lib: Porting Lib 1.1.317-beta+1.18.2-dev.7ad1f24
				com_github_llamalad7_mixinextras: MixinExtras 0.0.10
				mm: Manningham Mills 2.3
				serialization_hooks: Serialization Hooks 0.2.0+1.18.f5d4aa6
			reach-entity-attributes: Reach Entity Attributes 2.1.1
			registrate-fabric: Registrate for Fabric MC1.18.2-1.0.3
		customskinloader: CustomSkinLoader 14.13
		disable_custom_worlds_advice: Disable Custom Worlds Advice 2.0
		fabric: Fabric API 0.57.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.22+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.0+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.18+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.1+6c4e5d0960
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.22+e6b169eb60
			fabric-networking-v0: Fabric Networking (v0) 0.3.9+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.9+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.2+d005b03a60
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.1+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabricloader: Fabric Loader 0.14.5
		ftblibrary: FTB Library 1802.3.6-build.119
		ftbquests: FTB Quests 1802.3.8-build.101
		ftbteams: FTB Teams 1802.2.6-build.51
		gravitychanger: GravityChanger 0.3.1
		ibeeditor: IBE Editor 2.0.10
		immersive_portals: Immersive Portals 1.4.9
			imm_ptl_core: Immersive Portals Core 1.4.9
			q_misc_util: QMiscUtil 1.4.9
		indium: Indium 1.0.3+mc1.18.2
		itemfilters: Item Filters 1802.2.7-build.33
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.18.2
		modmenu: Mod Menu 3.2.2
		offlineskins: OfflineSkins 1.18.2-v2-fabric
		pehkui: Pehkui 3.3.3+1.14.4-1.19.1
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVD9 GL version 4.3 (Core Profile) Mesa 21.2.6, nouveau
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/mirrors2 (incompatible), continuity/glass_pane_culling_fix, continuity/default, file/dakota-s-sodium-connected-textures.zip (incompatible), file/Better+Clear+Glass+Bordered+1.18.zip
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-3330 CPU @ 3.00GHz
```

**Comment by qouteall** [comment]
This mod manage multiple dimensions in client at the same time and multiple servers break the assumption of dimensions

**Comment by Siorinex** [comment]
In Discord of Velocity - say about problem in this - https://github.com/qouteall/ImmersivePortalsMod/blob/1.19/imm_ptl_core/src/main/java/qouteall/imm_ptl/core/ClientWorldLoader.java#L310

**Comment by unilock** [comment]
I was able to "fix" this on 1.19.2 by just commenting out all verifications against `client.level`, specifically:

https://github.com/iPortalTeam/ImmersivePortalsMod/blob/b7e88493c041db2ca56eb123f5ae2154f286bce6/imm_ptl_core/src/main/java/qouteall/imm_ptl/core/ClientWorldLoader.java#L310

https://github.com/iPortalTeam/ImmersivePortalsMod/blob/b7e88493c041db2ca56eb123f5ae2154f286bce6/imm_ptl_core/src/main/java/qouteall/imm_ptl/core/render/PortalRenderer.java#L65

I'm surprised it hasn't blown up in my face yet, considering I have about 500 other mods installed.

**Comment by D3it7i** [comment]
Works fine when ImmPtl command is not registered 1.20.2
`velocity-3.2.0-SNAPSHOT-294.jar`

**Comment by adaliszk** [comment]
Ah, that's good to hear that 1.20.2 is working fine. Right now, I am stuck on 1.20.1, mainly because of create. 

For the maintainers and collaborators, Is there any chance that we can get the backport fix for it on 1.20.1?

**Comment by qouteall** [comment]
I didn't change the validation code in ClientWorldLoader in 1.20.2. I don't know why it becomes compatible in 1.20.2.
