### ISSUE TITLE
mod is compatible with optifabric

### ISSUE THREAD

**Issue by arlinkquaker** [qouteall/ImmersivePortalsMod#1147]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

Yes

### Describe the issue

my mc set with fabric ,optifine, and optifabric. and the immersive portals error with optifabric.

### Post the log here

```shell
[23:37:22] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.8
[23:37:22] [main/WARN]: Mod resolution failed
[23:37:22] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE immersive_portals 2.0.5 {depends fabric @ [>=0.28.1]}, ROOT_FORCELOAD_SINGLE immersive_portals 2.0.5]
[23:37:22] [main/INFO]: Reason: [HARD_DEP immersive_portals 2.0.5 {depends fabric @ [>=0.28.1]}, NEG_HARD_DEP immersive_portals 2.0.5 {breaks optifabric @ [*]}, HARD_DEP imm_ptl_core 2.0.5 {depends fabric @ [>=0.28.1]}, HARD_DEP q_misc_util 2.0.5 {depends fabric @ [>=0.28.1]}]
[23:37:22] [main/INFO]: Fix: add [], remove [], replace [[immersive_portals 2.0.5] -> add:immersive_portals 1 ([(-∞,∞)])]
[23:37:22] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Immersive Portals' (immersive_portals) 2.0.5 with any version that is compatible with:
		 - optifabric 1.13.5
Unmet dependency listing:
	 - Mod 'Immersive Portals' (immersive_portals) 2.0.5 requires version 0.28.1 or later of fabric, which is missing!
	 - Mod 'Immersive Portals' (immersive_portals) 2.0.5 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.5!
	 - Mod 'Immersive Portals Core' (imm_ptl_core) 2.0.5 requires version 0.28.1 or later of fabric, which is missing!
	 - Mod 'QMiscUtil' (q_misc_util) 2.0.5 requires version 0.28.1 or later of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
```

**Comment by qouteall** [comment]
https://qouteall.fun/immptl/wiki/Miscellaneous.html#optifine-compatibility
