### ISSUE TITLE
All alternate dimensions are always perfectly lit up everywhere no matter what

### ISSUE THREAD

**Issue by ghost** [qouteall/ImmersivePortalsMod#1166]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

Yes

### Describe the issue

I have first encountered the issue on my immptl server, where no hostile mobs properly spawned, spawners didn't work, etc, after a while I noticed it was as if I had fullbright - but i had no mods that would provide fulbringht.
Today i got to singleplayer testing and I can certainly say there is a bug with immptl.
Things are:
1. Everything on the server side behaves as if the light level is 15 everywhere (in the alternate dimensions)
2. On the client it looks as if you had fullbright on.
3. "Client light" in F3 is calculated properly (is low in areas that are supposed to be dark)

So what may be happening here is the server not bothering to ever calculate light for those dimensions. It's weird for a severe bug like that got unnoticed.

The log has no useful information at first glance, but i'll upload it here anyway. I had sodium, but it cannot be it because it's a 100% server side issue (happened on a muliplayer server)

### Post the log here

https://mclo.gs/m00I0ul

**Comment by qouteall** [comment]
I intentionally made the alternate dimensions fully bright to make the skylands not dark when seeing from downside (when using the skyland for dimension stack)

**Comment by qouteall** [comment]
I am going to make that only alternate1 has fullbright and all other alternate dimensions have normal brightness

**Comment by ghost** [comment]
> I intentionally made the alternate dimensions fully bright to make the skylands not dark when seeing from downside (when using the skyland for dimension stack)

You could make it so the bottom of the world also emits sunlight for this purpose.

**Comment by qouteall** [comment]
MC's lighting system does not allow "reverse sunlight from the bottom".

**Comment by ghost** [comment]
> MC's lighting system does not allow "reverse sunlight from the bottom".

anyway, when is the fix for this gonna be live?
+, this sort of ligthing change should be client only and toggleable

**Comment by qouteall** [comment]
In 2.2.2, only alternate1 has fullbright and all other alternate dimensions have normal brightness

**Comment by qouteall** [comment]
The lighting option cannot be client-only because non-synchronized light will cause bugs. If you want fully bright simply use alternate1. There is no config option for that

**Comment by ghost** [comment]
> In 2.2.2, only alternate1 has fullbright and all other alternate dimensions have normal brightness

@qouteall 2.2.2 crashes my server. 

```
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'imm_ptl_core'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.9.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-launch.jar:0.11.0]
Caused by: java.lang.NoClassDefFoundError: org/apache/http/client/methods/HttpUriRequest
        at qouteall.imm_ptl.core.platform_specific.IPModEntryDedicatedServer.onInitializeServer(IPModEntryDedicatedServer.java:10) ~[imm_ptl_core-2.2.2-b9c3f9955ec0e319.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.9.jar:?]
        ... 8 more
Caused by: java.lang.ClassNotFoundException: org.apache.http.client.methods.HttpUriRequest
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at qouteall.imm_ptl.core.platform_specific.IPModEntryDedicatedServer.onInitializeServer(IPModEntryDedicatedServer.java:10) ~[imm_ptl_core-2.2.2-b9c3f9955ec0e319.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.9.jar:?]
        ... 8 more
```

**Comment by ghost** [comment]
You literally mistyped the word "url" as "uri"

**Comment by ghost** [comment]
is 2.2.3 the fix (yes it is) thank you!
