### ISSUE TITLE
incompatible with optifine

### ISSUE THREAD

**Issue by Santiag09** [qouteall/ImmersivePortalsMod#1177]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

Yes

### Describe the issue

While using optifine & Immersive Portals the game fails to even open.

### Post the log here

```shell
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Immersive Portals' (immersive_portals) 2.2.3 with any version that is compatible with:
		 - optifabric 1.13.16
Unmet dependency listing:
	 - Mod 'Immersive Portals' (immersive_portals) 2.2.3 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.16!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by Nick1st** [comment]
Optifine is not supported, use Sodium+Iris instead.

**Comment by Santiag09** [comment]
Ok

**Comment by qouteall** [comment]
https://qouteall.fun/immptl/wiki/Miscellaneous.html#optifine-compatibility
