### ISSUE TITLE
non-fatal issue with Quilt

### ISSUE THREAD

**Issue by Lolothepro** [qouteall/ImmersivePortalsMod#1178]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

Yes

### Describe the issue

*

### Post the log here

```shell
[18:31:10] [Render thread/ERROR]: Failed to process task qouteall.q_misc_util.my_util.MyTaskList$$Lambda$4474/0x000000080167dad8@42ae60a2
[18:31:10] [Render thread/INFO]: [STDERR]: java.lang.UnsupportedOperationException: not implemented
[18:31:10] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.ModContainerImpl.getContainingMod(ModContainerImpl.java:61)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at qouteall.imm_ptl.core.compat.IPModCompatibilityWarning.lambda$initClient$5(IPModCompatibilityWarning.java:115)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at qouteall.imm_ptl.core.compat.IPModCompatibilityWarning.lambda$initClient$6(IPModCompatibilityWarning.java:116)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at qouteall.q_misc_util.my_util.MyTaskList.lambda$oneShotTask$1(MyTaskList.java:52)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at qouteall.q_misc_util.my_util.MyTaskList.lambda$withDelayCondition$4(MyTaskList.java:114)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at qouteall.q_misc_util.my_util.MyTaskList.lambda$processTasks$0(MyTaskList.java:35)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at qouteall.q_misc_util.Helper.removeIf(Helper.java:544)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at qouteall.q_misc_util.my_util.MyTaskList.processTasks(MyTaskList.java:33)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at qouteall.q_misc_util.my_util.Signal.lambda$emit$0(Signal.java:18)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at qouteall.q_misc_util.my_util.Signal.emit(Signal.java:18)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.handler$zgn000$onAfterClientTick(class_310.java:3497)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1574(class_310.java:1788)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1091)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:737)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:236)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
[18:31:10] [Render thread/INFO]: [STDERR]: 	at org.polymc.EntryPoint.main(EntryPoint.java:74)
```

**Comment by qouteall** [comment]
You can ignore that error.

**Comment by Lolothepro** [comment]
fixed https://github.com/QuiltMC/quilt-loader/commit/28340bc63c1dbe1e25f2f902d4d780a50b7fff2d
