### ISSUE TITLE
Launcher crashes when launching fabric with mod

### ISSUE THREAD

**Issue by altacountbabi** [qouteall/ImmersivePortalsMod#1204]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

Yes

### Describe the issue

Theres really not much to explain, it just crashes with code 1 when launching fabric and I think its an issue in the code.

### Post the log here

```shell
[23:46:42] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.14.10
[23:46:43] [ForkJoinPool-1-worker-2/WARN]: Mod modmenu uses the version v1.16.8+unknown.bd9230a which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[23:46:43] [main/INFO]: Loading 52 mods:
	- cloth-basic-math 0.5.1 via cloth-config2
	- cloth-config2 4.11.15 via immersive_portals
	- fabric 0.36.0+1.16
	- fabric-api-base 0.3.0+c88702897d via fabric
	- fabric-api-lookup-api-v1 1.2.0+6aebe11a7d via fabric
	- fabric-biome-api-v1 3.1.10+3661eaa17d via fabric
	- fabric-blockrenderlayer-v1 1.1.5+ca58154a7d via fabric
	- fabric-command-api-v1 1.1.1+351679a77d via fabric
	- fabric-commands-v0 0.2.2+ca58154a7d via fabric
	- fabric-containers-v0 0.1.11+9354966b7d via fabric
	- fabric-content-registries-v0 0.2.1+ca58154a7d via fabric
	- fabric-crash-report-info-v1 0.1.3+ca58154a7d via fabric
	- fabric-dimensions-v1 2.0.6+61336ba97d via fabric
	- fabric-entity-events-v1 1.1.0+c88702897d via fabric
	- fabric-events-interaction-v0 0.4.3+f941baf07d via fabric
	- fabric-events-lifecycle-v0 0.2.1+ca58154a7d via fabric
	- fabric-game-rule-api-v1 1.0.6+ca58154a7d via fabric
	- fabric-item-api-v1 1.2.1+ca58154a7d via fabric
	- fabric-item-groups-v0 0.2.7+2868a2287d via fabric
	- fabric-key-binding-api-v1 1.0.4+9354966b7d via fabric
	- fabric-keybindings-v0 0.2.1+ca58154a7d via fabric
	- fabric-lifecycle-events-v1 1.2.1+ca58154a7d via fabric
	- fabric-loot-tables-v1 1.0.2+ca58154a7d via fabric
	- fabric-mining-levels-v0 0.1.3+ca58154a7d via fabric
	- fabric-models-v0 0.3.0+bc7a746f7d via fabric
	- fabric-networking-api-v1 1.0.3+e3c9d0627d via fabric
	- fabric-networking-blockentity-v0 0.2.8+ca58154a7d via fabric
	- fabric-networking-v0 0.3.2+ca58154a7d via fabric
	- fabric-object-builder-api-v1 1.9.5+c88702897d via fabric
	- fabric-object-builders-v0 0.7.2+ca58154a7d via fabric
	- fabric-particles-v1 0.2.4+ca58154a7d via fabric
	- fabric-registry-sync-v0 0.7.4+ca58154a7d via fabric
	- fabric-renderer-api-v1 0.4.3+0ef801b67d via fabric
	- fabric-renderer-indigo 0.4.4+ca58154a7d via fabric
	- fabric-renderer-registries-v1 2.3.0+2868a2287d via fabric
	- fabric-rendering-data-attachment-v1 0.1.5+ca58154a7d via fabric
	- fabric-rendering-fluids-v1 0.1.13+ca58154a7d via fabric
	- fabric-rendering-v0 1.1.2+ca58154a7d via fabric
	- fabric-rendering-v1 1.6.0+2868a2287d via fabric
	- fabric-resource-loader-v0 0.4.6+2868a2287d via fabric
	- fabric-screen-api-v1 1.0.0+c045166c7d via fabric
	- fabric-screen-handler-api-v1 1.1.5+9354966b7d via fabric
	- fabric-structure-api-v1 1.1.11+ca0ef93d7d via fabric
	- fabric-tag-extensions-v0 1.1.1+ca58154a7d via fabric
	- fabric-textures-v0 1.0.6+ca58154a7d via fabric
	- fabric-tool-attribute-api-v1 1.2.7+8183d3957d via fabric
	- fabricloader 0.14.10
	- imm_ptl_core 0.99 via immersive_portals
	- immersive_portals 0.99
	- java 8
	- minecraft 1.16.5
	- modmenu v1.16.8+unknown.bd9230a via immersive_portals
[23:46:43] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/danmi/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[23:46:45] [main/ERROR]: Mixin apply for mod immersive_portals failed imm_ptl_peripheral.mixins.json:common.altius_world.MixinChunkStatus from mod immersive_portals -> net.minecraft.class_2806: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException 'static' modifier of handler method does not match target in net/minecraft/class_2806::redirectBuildSurface [PREINJECT Applicator Phase -> imm_ptl_peripheral.mixins.json:common.altius_world.MixinChunkStatus from mod immersive_portals -> Prepare Injections ->  -> handler$zlk000$redirectBuildSurface(Lnet/minecraft/class_3218;Lnet/minecraft/class_2794;Ljava/util/List;Lnet/minecraft/class_2791;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: 'static' modifier of handler method does not match target in net/minecraft/class_2806::redirectBuildSurface [PREINJECT Applicator Phase -> imm_ptl_peripheral.mixins.json:common.altius_world.MixinChunkStatus from mod immersive_portals -> Prepare Injections ->  -> handler$zlk000$redirectBuildSurface(Lnet/minecraft/class_3218;Lnet/minecraft/class_2794;Ljava/util/List;Lnet/minecraft/class_2791;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.checkTargetModifiers(Injector.java:347) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.sanityCheck(CallbackInjector.java:425) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:237) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) [fabric-loader-0.14.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at net.minecraft.class_2378.<clinit>(class_2378.java:164) [client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.10.jar:?]
[23:46:45] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.10.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_2966.method_12851(class_2966.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) ~[fabric-loader-0.14.10-1.16.5.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.10.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2806 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.class_2378.<clinit>(class_2378.java:164) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) ~[fabric-loader-0.14.10-1.16.5.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.10.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.class_2378.<clinit>(class_2378.java:164) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) ~[fabric-loader-0.14.10-1.16.5.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.10.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [imm_ptl_peripheral.mixins.json:common.altius_world.MixinChunkStatus from mod immersive_portals] from phase [DEFAULT] in config [imm_ptl_peripheral.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.class_2378.<clinit>(class_2378.java:164) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) ~[fabric-loader-0.14.10-1.16.5.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.10.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: 'static' modifier of handler method does not match target in net/minecraft/class_2806::redirectBuildSurface [PREINJECT Applicator Phase -> imm_ptl_peripheral.mixins.json:common.altius_world.MixinChunkStatus from mod immersive_portals -> Prepare Injections ->  -> handler$zlk000$redirectBuildSurface(Lnet/minecraft/class_3218;Lnet/minecraft/class_2794;Ljava/util/List;Lnet/minecraft/class_2791;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.checkTargetModifiers(Injector.java:347) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.sanityCheck(CallbackInjector.java:425) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:237) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.class_2378.<clinit>(class_2378.java:164) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) ~[fabric-loader-0.14.10-1.16.5.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.10.jar:?]
	... 2 more
```

**Comment by qouteall** [comment]
Maybe you can use older versions of Fabric loader.

**Comment by qouteall** [comment]
You should use the latest version for 1.16.5
