### ISSUE TITLE
Weird end portal block behaviour after an immptl portal

### ISSUE THREAD

**Issue by ghost** [qouteall/ImmersivePortalsMod#1219]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

Not yet tested

### Describe the issue

Edit: Teleporting to the end via a naturally generated vanilla end portal block after a portal leading to above/near it either makes you invincible in the end until rejoin or drops you off at the portal block's coordinates in the original dimension in the end instead of the obsidian platform. Read down the thread for videos and discussion, etc. 

Neither issue occurs without going into the portal block immediately after a portal. Whichever variant happens is very inconsistent and the exact conditionas are not determined yet.

**Comment by qouteall** [comment]
I cannot reproduce this issue on my side (latest version of ImmPtl). Can you explain how to trigger this issue in detail?

Can you test whether the issue occur with only Immersive Portals mod and Farbic API?

**Comment by ghost** [comment]
It doesn't appear to appear anymore for me either. If i can't reproduce it right now i'll close the issue

**Comment by ghost** [comment]
Does passing through portals give you momentary invincibility by chance?

**Comment by ghost** [comment]
https://user-images.githubusercontent.com/85982640/209426831-fb704b6c-d0e7-4cfe-9b0d-0b0adee2cf6b.mp4

Encountered a surprise when it loaded me off in the portal block's coords instead of the obi platform. This also happens i'd assume

**Comment by ghost** [comment]
Reproduced original issue. Will try to repdroduce in singleplayer, then with a minimal mod set.

https://user-images.githubusercontent.com/85982640/209427090-cff1abbf-cab0-4eae-9fdb-112fc83d6139.mp4

**Comment by ghost** [comment]
@qouteall sadly i can barely run the integrated server with all the optimization mods, i don't think i'll be able to load into an alternate 3/4 world in vanilla at all. Could you please try and reproduce it yourself because my PC is too potato  
In the meantime i'll try messing around with some settings on the server in case one of them helps, and update immptl to latest in case it's not

Edit: the server is running immptl 2.3.1-1.19.2 (latest for 1.19.2). I'll now see whether the rift/gate to the end portal is relevant at all and how exactly those 2 issues appear.

**Comment by ghost** [comment]
Apparently, you do need to have passed through that downwards portal for the bug to trigger.  If you fall into a portal that takes you to right above the end portal, there are two outcomes:

1. You get loaded off in the same coords in the end as the portal block's coords, in this case it's the middle of the void.
2. You get loaded off at the obsidian platform, invincible until rejoin.

Case 1 happens if you fall into the portal block quickly and hit the block below the portal block before getting teleported to the end, 2 happens if you fall in slowly without hitting the bottom block. This is inconsistent though, maybe it depends on you sneaking? I'll try with the human origin and report back. (Edit: it does indeed only depend on whether you're midair or not while being teleported.) (Edit 2: it's still very inconsistent and i have no idea how it works)

**Comment by ghost** [comment]
I might have a slight idea of what's going on. The dimension stack border between alternate 3 and 4 is exactly below the portal, and appatently the dimension below not being loaded yet while the player is teleporting may be relevant

**Comment by ghost** [comment]
Forget everything I said in the last 2 messages, i don't have any idea of what's going on. It's very inconsistent and i don't have the skills to actually determine what's happening in each case. Reproducing it in singleplayer might help a lot, but i literally can't lmao

Btw the invincibility state is so powerful it counters even the /kill command.

**Comment by ghost** [comment]
This might be a bit too comically large but it's accurate

**Comment by ghost** [comment]
```
[09:12:29] [Server thread/WARN]: HyperSoop moved too quickly! 0.0,-26.800617295347365,0.0
[09:12:29] [Server thread/ERROR]: Tries to send player pos packet to a removed player
[09:12:29] [Server thread/INFO]: [STDERR]: java.lang.Throwable
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3244.method_33563(class_3244.java:2169)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3244.method_14363(class_3244.java:1036)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3244.method_12063(class_3244.java:946)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2828.method_12272(class_2828.java:114)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2828$class_2829.method_11054(class_2828.java:42)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2600.method_11072(class_2600.java:22)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3738.run(class_3738.java:18)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_18859(class_1255.java:157)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_4093.method_18859(class_4093.java:23)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_16075(class_1255.java:131)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_18857(class_1255.java:140)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.handler$zha000$modifiedRunLoop(MinecraftServer.java:4394)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[09:12:29] [Server thread/INFO]: [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[09:12:29] [Server thread/WARN]: HyperSoop moved too quickly! 0.0,-10.39332350776317,0.0
[09:12:29] [Server thread/ERROR]: Tries to send player pos packet to a removed player
[09:12:29] [Server thread/INFO]: [STDERR]: java.lang.Throwable
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3244.method_33563(class_3244.java:2169)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3244.method_14363(class_3244.java:1036)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3244.method_12063(class_3244.java:946)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2828.method_12272(class_2828.java:114)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2828$class_2829.method_11054(class_2828.java:42)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2600.method_11072(class_2600.java:22)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3738.run(class_3738.java:18)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_18859(class_1255.java:157)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_4093.method_18859(class_4093.java:23)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_16075(class_1255.java:131)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_5383(class_1255.java:116)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.handler$zha000$modifiedRunLoop(MinecraftServer.java:4394)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[09:12:29] [Server thread/INFO]: [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[09:12:29] [Server thread/WARN]: HyperSoop moved too quickly! 0.0,-12.377952030004963,0.0
[09:12:29] [Server thread/ERROR]: Tries to send player pos packet to a removed player
[09:12:29] [Server thread/INFO]: [STDERR]: java.lang.Throwable
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3244.method_33563(class_3244.java:2169)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3244.method_14363(class_3244.java:1036)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3244.method_12063(class_3244.java:946)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2828.method_12272(class_2828.java:114)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2828$class_2829.method_11054(class_2828.java:42)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2600.method_11072(class_2600.java:22)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3738.run(class_3738.java:18)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_18859(class_1255.java:157)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_4093.method_18859(class_4093.java:23)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_16075(class_1255.java:131)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_1255.method_5383(class_1255.java:116)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.handler$zha000$modifiedRunLoop(MinecraftServer.java:4394)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
[09:12:29] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[09:12:29] [Server thread/INFO]: [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
```
That was spammed in the server's log when i tried to move around in the invincible state.
