### ISSUE TITLE
Randomly a portal will render nothing and then my game crashes immediately.

### ISSUE THREAD

**Issue by doctorricky** [qouteall/ImmersivePortalsMod#1260]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

Yes

### Describe the issue

At random times, either instantly or minutes into the game if I look at a portal itll just render only a void and then my game crashes. I only have immersive portals and pehkui 1.19.3 fabric

### Post the log here

```shell
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 2023-01-28 14:32:18
Description: Unexpected error

java.lang.IllegalStateException: Already building!
	at net.minecraft.class_287.method_1328(class_287.java:126)
	at net.minecraft.class_846$class_851.method_3655(class_846.java:343)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:573)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:489)
	at net.minecraft.class_846$class_851.method_22781(class_846.java:450)
	at net.minecraft.class_846.method_3627(class_846.java:211)
	at net.minecraft.class_761.method_3269(class_761.java:2374)
	at net.minecraft.class_761.method_22710(class_761.java:1243)
	at net.minecraft.class_757.method_3188(class_757.java:1085)
	at net.minecraft.class_757.redirect$zmo000$redirectRenderingWorld(class_757.java:2706)
	at net.minecraft.class_757.method_3192(class_757.java:864)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_287.method_1328(class_287.java:126)
	at net.minecraft.class_846$class_851.method_3655(class_846.java:343)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:573)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:489)
	at net.minecraft.class_846$class_851.method_22781(class_846.java:450)
	at net.minecraft.class_846.method_3627(class_846.java:211)
	at net.minecraft.class_761.method_3269(class_761.java:2374)
	at net.minecraft.class_761.method_22710(class_761.java:1243)
	at net.minecraft.class_757.method_3188(class_757.java:1085)
	at net.minecraft.class_757.redirect$zmo000$redirectRenderingWorld(class_757.java:2706)

-- Affected level --
Details:
	All players: 2 total; [class_746['HELIUMGUY'/18479, l='ClientWorld minecraft:overworld', x=-10349.12, y=77.00, z=-1032.00], class_745['brunco'/5650, l='ClientWorld minecraft:overworld', x=-10362.36, y=71.00, z=-1026.42]]
	Chunk stats: Client Chunks (ImmPtl) 250
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,80,0), Section: (at 0,0,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 509538 game time, 71004 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2390)
	at net.minecraft.class_310.method_1514(class_310.java:805)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 470203568 bytes (448 MiB) / 1677721600 bytes (1600 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) UHD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x3e92
	Graphics card #0 versionInfo: DriverVersion=31.0.101.2114
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 12044.97
	Virtual memory used (MB): 9948.41
	Swap memory total (MB): 4000.30
	Swap memory used (MB): 877.04
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.73.0+1.19.3
			fabric-api-base: Fabric API Base 0.4.20+afca2f3e85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.19+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.0+b5d379b085
			fabric-block-api-v1: Fabric Block API (v1) 1.0.4+e022e5d185
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.29+c6af733c85
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.11+1134c5b885
			fabric-command-api-v1: Fabric Command API (v1) 1.2.21+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.0+3fc4752e85
			fabric-commands-v0: Fabric Commands (v0) 0.2.38+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.46+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.13+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.2.0+06937c4b85
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.40+48349a3f85
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.6+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.39+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.43+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.29+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.9+c3530bb185
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.11+1134c5b885
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.30+bc01e09785
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.28+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.9+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.19+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.23+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.13+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.30+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.26+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.16+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.33+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.4.0+eb2a3ba985
			fabric-particles-v1: Fabric Particles (v1) 1.0.19+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.0+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.4+1134c5b885
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.0+9f179aa185
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.0+9f179aa185
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.29+df3654b385
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.24+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.17+f1e4495b85
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.32+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+eb2a3ba985
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.2+1134c5b885
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.4+a91e48b785
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.40+f1e4495b85
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.12+99f9db8085
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.7+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.14+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.0+5b9a588b85
		fabricloader: Fabric Loader 0.14.13
		immersive_portals: Immersive Portals 2.4.8
			cloth-config: Cloth Config v9 9.0.94
				cloth-basic-math: cloth-basic-math 0.6.1
			imm_ptl_core: Immersive Portals Core 2.4.8
			q_misc_util: QMiscUtil 2.4.8
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.3
		pehkui: Pehkui 3.6.3+1.14.4-1.19.3
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
	Launched Version: fabric-loader-0.14.13-1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel(R) UHD Graphics 630 GL version 3.2.0 - Build 31.0.101.2114, Intel
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
```

**Comment by qouteall** [comment]
This is probably a bug of Nvidia driver. https://github.com/CaffeineMC/sodium-fabric/issues/1486

You can install Sodium to workaround this issue. In future I will display a warning message that tells player to install sodium when using nvidia videocard.
