### ISSUE TITLE
Incompatible with Essential

### ISSUE THREAD

**Issue by BreadBod** [qouteall/ImmersivePortalsMod#1264]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

Yes

### Describe the issue

I have been playing with my friend using immersive portals, essential and other mods. although the other mods could of caused it, they should work as they are gravity api, pekhui, and blockus. Before the most recent update, i could place portals fine with my friend online but now when a portal is placed, they immediately get kicked. I know immersive portals is causing this as it happened only after we updated to the newest version.

### Post the log here

```shell
5:48:44] [Essential Thread 13/ERROR]: java.nio.channels.ClosedChannelException
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.incubator.codec.quic.QuicheQuicStreamChannel$QuicStreamChannelUnsafe.close(QuicheQuicStreamChannel.java:509)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.incubator.codec.quic.QuicheQuicChannel.closeStreams(QuicheQuicChannel.java:746)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.incubator.codec.quic.QuicheQuicChannel.forceClose(QuicheQuicChannel.java:434)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.incubator.codec.quic.QuicheQuicChannel$TimeoutHandler.run(QuicheQuicChannel.java:1702)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[15:48:44] [Essential Thread 13/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[15:48:44] [Essential Thread 13/ERROR]: java.nio.channels.ClosedChannelException
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.incubator.codec.quic.QuicheQuicStreamChannel$QuicStreamChannelUnsafe.close(QuicheQuicStreamChannel.java:509)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.incubator.codec.quic.QuicheQuicChannel.closeStreams(QuicheQuicChannel.java:746)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.incubator.codec.quic.QuicheQuicChannel.forceClose(QuicheQuicChannel.java:434)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.incubator.codec.quic.QuicheQuicChannel$TimeoutHandler.run(QuicheQuicChannel.java:1702)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[15:48:44] [Essential Thread 13/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[15:48:44] [Essential Thread 13/ERROR]: java.nio.channels.ClosedChannelException
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.incubator.codec.quic.QuicheQuicStreamChannel$QuicStreamChannelUnsafe.close(QuicheQuicStreamChannel.java:509)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.incubator.codec.quic.QuicheQuicChannel.closeStreams(QuicheQuicChannel.java:746)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.incubator.codec.quic.QuicheQuicChannel.forceClose(QuicheQuicChannel.java:434)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.incubator.codec.quic.QuicheQuicChannel$TimeoutHandler.run(QuicheQuicChannel.java:1702)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:48:44] [Essential Thread 13/ERROR]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[15:48:44] [Essential Thread 13/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[15:48:44] [netty<-quic (f2c458a2-e359-4aab-8006-f98b10c7abbd)/INFO]: Closing.
[15:48:44] [Netty Server IO ICE #2/INFO]: f2c458a2-e359-4aab-8006-f98b10c7abbd channel inactive, closing.
[15:48:44] [netty->quic (f2c458a2-e359-4aab-8006-f98b10c7abbd)/INFO]: Closing.
[15:48:44] [Netty Server IO ICE #2/INFO]: f2c458a2-e359-4aab-8006-f98b10c7abbd closing QUIC.
[15:48:44] [Netty Server IO ICE #2/INFO]: f2c458a2-e359-4aab-8006-f98b10c7abbd closed.
[15:48:45] [Server thread/INFO]: Boxell lost connection: Disconnected
[15:48:45] [Server thread/INFO]: Boxell left the game
[15:48:45] [Render thread/INFO]: [System] [CHAT] Boxell left the game
[15:48:47] [Render thread/INFO]: Changing agent ICE Agent (stream-count=0 ice-pwd:4gg32kjrquoflq9kebu9v1hak9 ice-ufrag:essential-qv52593-fba9c1go4pdnqi tie-breaker:3717785759019522360):
 role from controlling = true to controlling = false
[15:48:48] [Render thread/INFO]: Gathering candidates for component minecraft.RTP.
[15:48:48] [MergingDatagramSocket reader thread for: /[fe80:0:0:0:b0df:c3ff:fe9c:ba07%13]:55866 -> null/INFO]: Failed to receive: java.net.SocketException: Socket closed
[15:48:48] [Render thread/INFO]: Closing.
[15:48:48] [MergingDatagramSocket reader thread for: /192.168.68.57:58907 -> null/INFO]: Failed to receive: java.net.SocketException: Socket closed
[15:48:48] [MergingDatagramSocket reader thread for: /192.168.68.57:58907 -> null/ERROR]: Cannot find socket to remove.
```

**Comment by qouteall** [comment]
Can you provide a link to essential?

**Comment by qouteall** [comment]
There are two essential in curseforge

https://www.curseforge.com/minecraft/mc-mods/essential-mod

https://www.curseforge.com/minecraft/mc-mods/essentials

I assume that you mean the first. Added incompatibilty message.

**Comment by qouteall** [comment]
The first essential mod is not open-source. So I cannot debug this issue. This can only be fixed from essential mod's side.

**Comment by Blazzycrafter** [comment]
Got infos...

Qoute Geek
> I believe @Systemless may have tested immersive portals with Essential before and had it working
> 
> The log snippet the user in the GitHub issue posted is completely unrelated and therefore useless so if you could provide some details on the issue in the meantime, we can look into it later if it hasn't been tested & seen as working already

![image](https://user-images.githubusercontent.com/39300111/220596227-56b7ae4a-e4b9-4dc0-862e-b5e66d6cc480.png)
![image](https://user-images.githubusercontent.com/39300111/220596242-a8e5803c-7e0d-4817-97c3-92c50e653f50.png)

**Comment by Blazzycrafter** [comment]
chatlog (edited (removed ids and discriminators AKA Streamermode enabled)):
[blazzycrafter-756837435186610177.txt](https://github.com/iPortalTeam/ImmersivePortalsMod/files/10802772/blazzycrafter-756837435186610177.txt)

**Comment by master2bean** [comment]
I haven't had this problem when using immersive portals, create, and essential.

**Comment by cootshk** [comment]
try using [World Host](https://modrinth.com/mod/world-host)

Turn friends off and turn on dont try Upnp

**Comment by BreadBod** [comment]
sorry i forgot to check this post. Thanks for the help and i will try world host. what is Upnp though?

**Comment by cootshk** [comment]
https://en.wikipedia.org/wiki/Universal_Plug_and_Play

**Comment by kaloyancs** [comment]
as of today the mod works perfectly fine. Every menu in essential works, the mod itself works, no fps drops or crashes. Maybe it only works for me and so I think you should try it with the newest versions of Essential and ImmersivePortals, but for me it works with 0 issues.

**Comment by loloee** [comment]
![2023-08-25_16 53 33](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/84539710/8030df48-23fa-47f8-b9bc-d9c61f9c5805)
it said this for me

**Comment by qouteall** [comment]
Probably a data race issue of ImmPtl (only occur in LAN multiplaying, not in dedicated server). Going to be fixed.

**Comment by Legend-SCR-Official** [comment]
It works for me, I've played with a friend on Essential and Immersive Portals numerous times :P

**Comment by kingslayer-6009** [comment]
> It works for me, I've played with a friend on Essential and Immersive Portals numerous times :P

same! i have a concerning amount of mods that immersive portals claims to not work with - if i am asked I will send the full mod list! i'm on minecraft version 1.20.1

 (p.s. i love prism launcher, you can add mods all you want and it will find all the dependencies needed and add them. mod conflicts with another? change the mod's version (it will list all mod versions for your current minecraft version) and it almost always works.)
