### ISSUE TITLE
Incompatible with Pehkui?

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#1309]
```
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_757 failed
	at net.minecraft.class_4668.<clinit>(class_4668.java:125)
	at qouteall.imm_ptl.peripheral.platform_specific.PeripheralModEntryClient.registerBlockRenderLayers(PeripheralModEntryClient.java:12)
	at qouteall.imm_ptl.peripheral.platform_specific.PeripheralModEntryClient.onInitializeClient(PeripheralModEntryClient.java:18)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_757 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 12 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 16 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [pehkui.mixins.json:client.compat1193plus.GameRendererMixin from mod pehkui] from phase [DEFAULT] in config [pehkui.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 19 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Specified index 0 for @ModifyArg is invalid for args (Lnet/minecraft/class_4587;FFF), expected F on net/minecraft/class_757::pehkui$bobView$translate$x [INJECT Applicator Phase -> pehkui.mixins.json:client.compat1193plus.GameRendererMixin from mod pehkui -> Apply Injections ->  -> Inject -> pehkui.mixins.json:client.compat1193plus.GameRendererMixin from mod pehkui->@ModifyArg::pehkui$bobView$translate$x(F)F]
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.findArgIndex(ModifyArgInjector.java:158)

```

**Comment by qouteall** [comment]
```
[11:25:14] [Render thread/ERROR] (FabricLoader/pehkui) Current name lookup: method_5529
[11:25:14] [Render thread/WARN] (FabricLoader/pehkui) Catching java.lang.NoSuchMethodException: net.minecraft.world.damagesource.EntityDamageSource.method_5529()
 java.lang.NoSuchMethodException: net.minecraft.world.damagesource.EntityDamageSource.method_5529()
	at java.lang.Class.getMethod(Class.java:2227) ~[?:?]
	at virtuoel.pehkui.util.ReflectionUtils.<clinit>(ReflectionUtils.java:48) ~[Pehkui-3.7.2.jar:3.7.2+1.14.4-1.19.4]
	at virtuoel.pehkui.util.I18nUtils.<clinit>(I18nUtils.java:24) ~[Pehkui-3.7.2.jar:3.7.2+1.14.4-1.19.4]
	at virtuoel.pehkui.command.PehkuiEntitySelectorOptions.<clinit>(PehkuiEntitySelectorOptions.java:25) ~[Pehkui-3.7.2.jar:3.7.2+1.14.4-1.19.4]
	at virtuoel.pehkui.Pehkui.onInitialize(Pehkui.java:42) ~[Pehkui-3.7.2.jar:3.7.2+1.14.4-1.19.4]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52) ~[fabric-loader-0.14.17.jar:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:465) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.run(Main.java:205) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-project-@-merged-named.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
[11:25:15] [Render thread/INFO] (Portal) Loading Immersive Portals config

```

**Comment by qouteall** [comment]
```
[11:27:41] [Render thread/ERROR] (FabricLoader/pehkui) Current name lookup: method_5529
[11:27:41] [Render thread/WARN] (FabricLoader/pehkui) Catching java.lang.NoSuchMethodException: net.minecraft.world.damagesource.EntityDamageSource.method_5529()
 java.lang.NoSuchMethodException: net.minecraft.world.damagesource.EntityDamageSource.method_5529()
	at java.lang.Class.getMethod(Class.java:2227) ~[?:?]
	at virtuoel.pehkui.util.ReflectionUtils.<clinit>(ReflectionUtils.java:48) ~[Pehkui-3.7.2.jar:3.7.2+1.14.4-1.19.4]
	at virtuoel.pehkui.util.I18nUtils.<clinit>(I18nUtils.java:24) ~[Pehkui-3.7.2.jar:3.7.2+1.14.4-1.19.4]
	at virtuoel.pehkui.command.PehkuiEntitySelectorOptions.<clinit>(PehkuiEntitySelectorOptions.java:25) ~[Pehkui-3.7.2.jar:3.7.2+1.14.4-1.19.4]
	at virtuoel.pehkui.Pehkui.onInitialize(Pehkui.java:42) ~[Pehkui-3.7.2.jar:3.7.2+1.14.4-1.19.4]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52) ~[fabric-loader-0.14.17.jar:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:465) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.run(Main.java:205) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-project-@-merged-named.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
[11:27:41] [Render thread/ERROR] (FabricLoader/Mixin) Mixin apply for mod pehkui failed pehkui.mixins.json:client.compat1193plus.GameRendererMixin from mod pehkui -> net.minecraft.client.renderer.GameRenderer: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Specified index 0 for @ModifyArg is invalid for args (Lcom/mojang/blaze3d/vertex/PoseStack;FFF), expected F on net/minecraft/client/renderer/GameRenderer::pehkui$bobView$translate$x [INJECT Applicator Phase -> pehkui.mixins.json:client.compat1193plus.GameRendererMixin from mod pehkui -> Apply Injections ->  -> Inject -> pehkui.mixins.json:client.compat1193plus.GameRendererMixin from mod pehkui->@ModifyArg::pehkui$bobView$translate$x(F)F]
 org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Specified index 0 for @ModifyArg is invalid for args (Lcom/mojang/blaze3d/vertex/PoseStack;FFF), expected F on net/minecraft/client/renderer/GameRenderer::pehkui$bobView$translate$x [INJECT Applicator Phase -> pehkui.mixins.json:client.compat1193plus.GameRendererMixin from mod pehkui -> Apply Injections ->  -> Inject -> pehkui.mixins.json:client.compat1193plus.GameRendererMixin from mod pehkui->@ModifyArg::pehkui$bobView$translate$x(F)F]
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.findArgIndex(ModifyArgInjector.java:158) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.injectAtInvoke(ModifyArgInjector.java:113) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.invoke.InvokeInjector.inject(InvokeInjector.java:82) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.inject(ModifyArgInjector.java:103) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1378) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.17.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.renderer.RenderStateShard.<clinit>(RenderStateShard.java:125) ~[minecraft-project-@-merged-named.jar:?]
	at software.bernie.example.ClientListener.registerRenderers(ClientListener.java:52) ~[geckolib-fabric-1.19.3-4.0.4.jar:4.0.4]
	at software.bernie.example.ClientListener.onInitializeClient(ClientListener.java:30) ~[geckolib-fabric-1.19.3-4.0.4.jar:4.0.4]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) ~[fabric-loader-0.14.17.jar:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:465) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.run(Main.java:205) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-project-@-merged-named.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
[11:27:41] [Render thread/INFO] (Indigo) [Indigo] Different rendering plugin detected; not applying Indigo.
[11:27:42] [Render thread/INFO] (Portal) Sodium is present
[11:27:42] [Render thread/INFO] (Portal) Iris is not present
---- Minecraft Crash Report ----
// My bad.

Time: 2023-04-01 11:27:42
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'geckolib'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:465)
	at net.minecraft.client.main.Main.run(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.client.renderer.RenderType
		at qouteall.imm_ptl.peripheral.platform_specific.PeripheralModEntryClient.registerBlockRenderLayers(PeripheralModEntryClient.java:12)
		at qouteall.imm_ptl.peripheral.platform_specific.PeripheralModEntryClient.onInitializeClient(PeripheralModEntryClient.java:18)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 9 more
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.client.renderer.GameRenderer failed
	at net.minecraft.client.renderer.RenderStateShard.<clinit>(RenderStateShard.java:125)
	at software.bernie.example.ClientListener.registerRenderers(ClientListener.java:52)
	at software.bernie.example.ClientListener.onInitializeClient(ClientListener.java:30)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 9 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.client.renderer.GameRenderer failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 13 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 17 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [pehkui.mixins.json:client.compat1193plus.GameRendererMixin from mod pehkui] from phase [DEFAULT] in config [pehkui.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 20 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Specified index 0 for @ModifyArg is invalid for args (Lcom/mojang/blaze3d/vertex/PoseStack;FFF), expected F on net/minecraft/client/renderer/GameRenderer::pehkui$bobView$translate$x [INJECT Applicator Phase -> pehkui.mixins.json:client.compat1193plus.GameRendererMixin from mod pehkui -> Apply Injections ->  -> Inject -> pehkui.mixins.json:client.compat1193plus.GameRendererMixin from mod pehkui->@ModifyArg::pehkui$bobView$translate$x(F)F]
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.findArgIndex(ModifyArgInjector.java:158)
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.injectAtInvoke(ModifyArgInjector.java:113)
	at org.spongepowered.asm.mixin.injection.invoke.InvokeInjector.inject(InvokeInjector.java:82)
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.inject(ModifyArgInjector.java:103)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1378)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 20 more


```
