### ISSUE TITLE
Incompatiable with 'BiomeMakeover'?

### ISSUE THREAD

**Issue by Nickpop24** [qouteall/ImmersivePortalsMod#1311]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Fabric API?

No

### Describe the issue

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'biomemakeover'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:465)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_757 failed
	at net.minecraft.class_4668.<clinit>(class_4668.java:125)
	at party.lemons.taniwha.block.rtype.RType.getAsRenderType(RType.java:24)
	at party.lemons.taniwha.block.modifier.RTypeModifier.lambda$accept$0(RTypeModifier.java:22)
	at dev.architectury.utils.EnvExecutor.runInEnv(EnvExecutor.java:35)
	at party.lemons.taniwha.block.modifier.RTypeModifier.lambda$accept$2(RTypeModifier.java:21)
	at dev.architectury.utils.EnvExecutor.runInEnv(EnvExecutor.java:35)
	at party.lemons.taniwha.block.modifier.RTypeModifier.accept(RTypeModifier.java:18)
	at party.lemons.taniwha.block.modifier.RTypeModifier.accept(RTypeModifier.java:9)
	at party.lemons.taniwha.registry.ModifierContainer.initModifiers(ModifierContainer.java:13)
	at party.lemons.taniwha.block.modifier.BlockWithModifiers.initModifiers(BlockWithModifiers.java:17)
	at party.lemons.taniwha.block.BlockHelper.lambda$static$0(BlockHelper.java:16)
	at dev.architectury.registry.registries.fabric.RegistrarManagerImpl.lambda$listen$0(RegistrarManagerImpl.java:56)
	at net.minecraft.class_2370.md73852c$fabric-registry-sync-v0$lambda$new$0$5(class_2370.java:1111)
	at net.minecraft.class_2370.handler$bib000$fabric-registry-sync-v0$setPost(class_2370.java:1219)
	at net.minecraft.class_2370.method_46744(class_2370.java:181)
	at net.minecraft.class_2348.method_46744(class_2348.java:23)
	at net.minecraft.class_2370.method_10272(class_2370.java:186)
	at net.minecraft.class_2378.method_39197(class_2378.java:118)
	at net.minecraft.class_2378.method_10230(class_2378.java:114)
	at dev.architectury.registry.registries.fabric.RegistrarManagerImpl$RegistrarImpl.register(RegistrarManagerImpl.java:210)
	at dev.architectury.registry.registries.DeferredRegister.register(DeferredRegister.java:76)
	at party.lemons.biomemakeover.init.BMBlocks.init(BMBlocks.java:200)
	at party.lemons.biomemakeover.BiomeMakeover.init(BiomeMakeover.java:39)
	at party.lemons.biomemakeover.fabric.BMFabric.onInitialize(BMFabric.java:41)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_757 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 33 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 37 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [pehkui.mixins.json:client.compat1193plus.GameRendererMixin from mod pehkui] from phase [DEFAULT] in config [pehkui.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 40 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Specified index 0 for @ModifyArg is invalid for args (Lnet/minecraft/class_4587;FFF), expected F on net/minecraft/class_757::pehkui$bobView$translate$x [INJECT Applicator Phase -> pehkui.mixins.json:client.compat1193plus.GameRendererMixin from mod pehkui -> Apply Injections ->  -> Inject -> pehkui.mixins.json:client.compat1193plus.GameRendererMixin from mod pehkui->@ModifyArg::pehkui$bobView$translate$x(F)F]
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.findArgIndex(ModifyArgInjector.java:158)
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.injectAtInvoke(ModifyArgInjector.java:113)
	at org.spongepowered.asm.mixin.injection.invoke.InvokeInjector.inject(InvokeInjector.java:82)
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.inject(ModifyArgInjector.java:103)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1378)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)

**Comment by qouteall** [comment]
The crash message is related with pehkui

**Comment by qouteall** [comment]
Are you sure that this issue is related with ImmPtl?
