### ISSUE TITLE
Crash with QSL

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#1319]
```
[15:54:50] [Server thread/ERROR]: Mixin apply for mod quilt_networking failed #quilt_networking:quilt_networking.mixins.json:EntityTrackerEntryMixin from mod quilt_networking -> net.minecraft.class_3231: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_3231::afterStartTracking with priority 1000 cannot inject into net/minecraft/class_3231::method_18760(Lnet/minecraft/class_3222;)V merged by qouteall.imm_ptl.core.mixin.common.entity_sync.MixinServerEntity with priority 1200 [PREINJECT Applicator Phase -> #quilt_networking:quilt_networking.mixins.json:EntityTrackerEntryMixin from mod quilt_networking -> Prepare Injections ->  -> handler$zho000$quilt_networking$afterStartTracking(Lnet/minecraft/class_3222;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_3231::afterStartTracking with priority 1000 cannot inject into net/minecraft/class_3231::method_18760(Lnet/minecraft/class_3222;)V merged by qouteall.imm_ptl.core.mixin.common.entity_sync.MixinServerEntity with priority 1200 [PREINJECT Applicator Phase -> #quilt_networking:quilt_networking.mixins.json:EntityTrackerEntryMixin from mod quilt_networking -> Prepare Injections ->  -> handler$zho000$quilt_networking$afterStartTracking(Lnet/minecraft/class_3222;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:453) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:244) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:164) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:150) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:228) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_3898$class_3208.<init>(class_3898.java:1388) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3898.method_18701(class_3898.java:1209) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3215.method_18755(class_3215.java:482) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1541) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1519) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31847(class_5579.java:217) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31820(class_5579.java:187) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31857(class_5579.java:352) ~[transformed-mod-minecraft.i0:0/:?]
	at java.util.Collections$2.tryAdvance(Collections.java:4853) ~[?:?]
	at java.util.Collections$2.forEachRemaining(Collections.java:4861) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.class_5579.method_31853(class_5579.java:352) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31809(class_5579.java:358) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:380) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266) ~[transformed-mod-minecraft.i0:0/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:54:50] [Server thread/WARN]: Mixin transformation of net.minecraft.class_3231 failed
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:453) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:244) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:164) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:150) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:228) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_3898$class_3208.<init>(class_3898.java:1388) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3898.method_18701(class_3898.java:1209) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3215.method_18755(class_3215.java:482) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1541) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1519) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31847(class_5579.java:217) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31820(class_5579.java:187) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31857(class_5579.java:352) ~[transformed-mod-minecraft.i0:0/:?]
	at java.util.Collections$2.tryAdvance(Collections.java:4853) ~[?:?]
	at java.util.Collections$2.forEachRemaining(Collections.java:4861) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.class_5579.method_31853(class_5579.java:352) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31809(class_5579.java:358) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:380) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266) ~[transformed-mod-minecraft.i0:0/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [#quilt_networking:quilt_networking.mixins.json:EntityTrackerEntryMixin from mod quilt_networking] from phase [DEFAULT] in config [#quilt_networking:quilt_networking.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	... 28 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_3231::afterStartTracking with priority 1000 cannot inject into net/minecraft/class_3231::method_18760(Lnet/minecraft/class_3222;)V merged by qouteall.imm_ptl.core.mixin.common.entity_sync.MixinServerEntity with priority 1200 [PREINJECT Applicator Phase -> #quilt_networking:quilt_networking.mixins.json:EntityTrackerEntryMixin from mod quilt_networking -> Prepare Injections ->  -> handler$zho000$quilt_networking$afterStartTracking(Lnet/minecraft/class_3222;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	... 28 more
[15:54:50] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception ticking world
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:905) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266) ~[transformed-mod-minecraft.i0:0/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3231 failed
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:458) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:244) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:164) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:150) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:228) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_3898$class_3208.<init>(class_3898.java:1388) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3898.method_18701(class_3898.java:1209) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3215.method_18755(class_3215.java:482) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1541) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1519) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31847(class_5579.java:217) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31820(class_5579.java:187) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31857(class_5579.java:352) ~[transformed-mod-minecraft.i0:0/:?]
	at java.util.Collections$2.tryAdvance(Collections.java:4853) ~[?:?]
	at java.util.Collections$2.forEachRemaining(Collections.java:4861) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.class_5579.method_31853(class_5579.java:352) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31809(class_5579.java:358) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:380) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[transformed-mod-minecraft.i0:0/:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:453) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:244) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:164) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:150) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:228) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_3898$class_3208.<init>(class_3898.java:1388) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3898.method_18701(class_3898.java:1209) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3215.method_18755(class_3215.java:482) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1541) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1519) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31847(class_5579.java:217) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31820(class_5579.java:187) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31857(class_5579.java:352) ~[transformed-mod-minecraft.i0:0/:?]
	at java.util.Collections$2.tryAdvance(Collections.java:4853) ~[?:?]
	at java.util.Collections$2.forEachRemaining(Collections.java:4861) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.class_5579.method_31853(class_5579.java:352) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31809(class_5579.java:358) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:380) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[transformed-mod-minecraft.i0:0/:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [#quilt_networking:quilt_networking.mixins.json:EntityTrackerEntryMixin from mod quilt_networking] from phase [DEFAULT] in config [#quilt_networking:quilt_networking.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:453) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:244) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:164) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:150) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:228) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_3898$class_3208.<init>(class_3898.java:1388) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3898.method_18701(class_3898.java:1209) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3215.method_18755(class_3215.java:482) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1541) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1519) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31847(class_5579.java:217) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31820(class_5579.java:187) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31857(class_5579.java:352) ~[transformed-mod-minecraft.i0:0/:?]
	at java.util.Collections$2.tryAdvance(Collections.java:4853) ~[?:?]
	at java.util.Collections$2.forEachRemaining(Collections.java:4861) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.class_5579.method_31853(class_5579.java:352) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31809(class_5579.java:358) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:380) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[transformed-mod-minecraft.i0:0/:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_3231::afterStartTracking with priority 1000 cannot inject into net/minecraft/class_3231::method_18760(Lnet/minecraft/class_3222;)V merged by qouteall.imm_ptl.core.mixin.common.entity_sync.MixinServerEntity with priority 1200 [PREINJECT Applicator Phase -> #quilt_networking:quilt_networking.mixins.json:EntityTrackerEntryMixin from mod quilt_networking -> Prepare Injections ->  -> handler$zho000$quilt_networking$afterStartTracking(Lnet/minecraft/class_3222;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:453) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:244) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:164) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:150) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:228) ~[quilt-loader-0.19.0-beta.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_3898$class_3208.<init>(class_3898.java:1388) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3898.method_18701(class_3898.java:1209) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3215.method_18755(class_3215.java:482) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1541) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1519) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31847(class_5579.java:217) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31820(class_5579.java:187) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31857(class_5579.java:352) ~[transformed-mod-minecraft.i0:0/:?]
	at java.util.Collections$2.tryAdvance(Collections.java:4853) ~[?:?]
	at java.util.Collections$2.forEachRemaining(Collections.java:4861) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.class_5579.method_31853(class_5579.java:352) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5579.method_31809(class_5579.java:358) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:380) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[transformed-mod-minecraft.i0:0/:?]
	... 5 more
```

**Comment by qouteall** [comment]
https://github.com/QuiltMC/quilt-standard-libraries/blob/a46a589b0d28e7e4d2da08cfafcc5c0653599a50/library/core/networking/src/main/java/org/quiltmc/qsl/networking/mixin/EntityTrackerEntryMixin.java
