### ISSUE TITLE
Crash when launching

### ISSUE THREAD

**Issue by Euxiniar** [qouteall/ImmersivePortalsMod#134]
By launching the game with the mod, with fabric, my game crashes with this error:

> [19:39:53] [main/INFO]: Loading for game Minecraft 1.15.2
> [19:39:56] [main/FATAL]: A critical error occurred
> net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: immersive_portals requires {fabric @ [*]}
> 	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:169) ~[fabric-loader-0.7.8+build.189.jar:?]
> 	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:602) ~[fabric-loader-0.7.8+build.189.jar:?]
> 	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:177) ~[fabric-loader-0.7.8+build.189.jar:?]
> 	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:167) [fabric-loader-0.7.8+build.189.jar:?]
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127) [fabric-loader-0.7.8+build.189.jar:?]
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.7.8+build.189.jar:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
> 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
> Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
> 	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
> 	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
> 	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
> 	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
> 	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:167) ~[fabric-loader-0.7.8+build.189.jar:?]
> 	... 13 more

Any idea?

**Comment by Euxiniar** [comment]
OK, I hadn't installed the Fabric API ^^' Sorry for that
