### ISSUE TITLE
Cannot generate a netherportal

### ISSUE THREAD

**Issue by AlexanderDotH** [qouteall/ImmersivePortalsMod#1376]
### Is it a mod compatibility issue?

Yes

### Minecraft version

1.20.1

### Describe the issue

As the title says, I can't create a netherportal.

Thats in the console:
[17:59:02] [Server thread/ERROR]: Failed to process task qouteall.imm_ptl.core.portal.nether_portal.NetherPortalGeneration$$Lambda$11007/0x0000000801fbc448@2ab3f64b
[17:59:02] [Server thread/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "com.ishland.c2me.threading.worldgen.common.IChunkStatus.getReducedTaskRadius()" because "chunkStatus" is null
[17:59:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3233.handler$zoe000$c2me-threading-worldgen$onInit(class_3233.java:2070)
[17:59:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3233.<init>(class_3233.java:106)
[17:59:02] [Server thread/INFO]: [STDERR]:      at qouteall.imm_ptl.core.chunk_loading.LenientChunkRegion.<init>(LenientChunkRegion.java:18)
[17:59:02] [Server thread/INFO]: [STDERR]:      at qouteall.imm_ptl.core.chunk_loading.LenientChunkRegion.createLenientChunkRegion(LenientChunkRegion.java:32)
[17:59:02] [Server thread/INFO]: [STDERR]:      at qouteall.imm_ptl.core.chunk_loading.ChunkLoader.createChunkRegion(ChunkLoader.java:60)
[17:59:02] [Server thread/INFO]: [STDERR]:      at qouteall.imm_ptl.core.portal.nether_portal.NetherPortalGeneration.lambda$startGeneratingPortal$5(NetherPortalGeneration.java:209)
[17:59:02] [Server thread/INFO]: [STDERR]:      at qouteall.q_misc_util.my_util.MyTaskList.lambda$processTasks$1(MyTaskList.java:42)
[17:59:02] [Server thread/INFO]: [STDERR]:      at qouteall.q_misc_util.Helper.removeIf(Helper.java:653)
[17:59:02] [Server thread/INFO]: [STDERR]:      at qouteall.q_misc_util.my_util.MyTaskList.processTasks(MyTaskList.java:40)
[17:59:02] [Server thread/INFO]: [STDERR]:      at qouteall.q_misc_util.my_util.Signal.lambda$emit$0(Signal.java:18)
[17:59:02] [Server thread/INFO]: [STDERR]:      at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[17:59:02] [Server thread/INFO]: [STDERR]:      at qouteall.q_misc_util.my_util.Signal.emit(Signal.java:18)
[17:59:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.handler$bif000$imm_ptl_core$onServerTick(MinecraftServer.java:5828)
[17:59:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:920)
[17:59:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3176.method_3813(class_3176.java:283)
[17:59:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
[17:59:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
[17:59:02] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
[17:59:02] [Server thread/INFO]: [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by qouteall** [comment]
Incompatibility with c2me

**Comment by qouteall** [comment]
Duplicate to https://github.com/iPortalTeam/ImmersivePortalsMod/issues/1036
