### ISSUE TITLE
GuiPortalRendering.submitNextFrameRendering crash when player changes dimensions

### ISSUE THREAD

**Issue by wagyourtail** [qouteall/ImmersivePortalsMod#1432]
### Is it a mod compatibility issue?

no

### Minecraft version

1.20.1

### Describe the issue

game crashes when changing world while using `GuiPortalRendering.submitNextFrameRendering`
oddly, don't happen every time. perhaps a race condition
also, on a related note, sometimes entities don't render through the gui portal either, I'm doing a chunkloader to get far away chunks or chunks in another dimension.

<details><summary>stacktrace</summary>

```
java.lang.NullPointerException: Cannot invoke "qouteall.imm_ptl.core.ducks.IEWorldRenderer.portal_getTransparencyShader()" because "worldRenderer" is null
	at qouteall.imm_ptl.core.render.MyGameRenderer.switchAndRenderTheWorld(MyGameRenderer.java:148) ~[imm_ptl_core-v3.2.6-mc1.20.1-mapped-intermediary-1.20.1-mojmap-1.20.1-mojmap-intermediary.jar:?]
	at qouteall.imm_ptl.core.render.MyGameRenderer.renderWorldNew(MyGameRenderer.java:97) ~[imm_ptl_core-v3.2.6-mc1.20.1-mapped-intermediary-1.20.1-mojmap-1.20.1-mojmap-intermediary.jar:?]
	at qouteall.imm_ptl.core.render.PortalRenderer.invokeWorldRendering(PortalRenderer.java:229) ~[imm_ptl_core-v3.2.6-mc1.20.1-mapped-intermediary-1.20.1-mojmap-1.20.1-mojmap-intermediary.jar:?]
	at qouteall.imm_ptl.core.render.GuiPortalRendering.renderWorldIntoFrameBuffer(GuiPortalRendering.java:63) ~[imm_ptl_core-v3.2.6-mc1.20.1-mapped-intermediary-1.20.1-mojmap-1.20.1-mojmap-intermediary.jar:?]
	at qouteall.imm_ptl.core.render.GuiPortalRendering.lambda$onGameRenderEnd$0(GuiPortalRendering.java:100) ~[imm_ptl_core-v3.2.6-mc1.20.1-mapped-intermediary-1.20.1-mojmap-1.20.1-mojmap-intermediary.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at qouteall.imm_ptl.core.render.GuiPortalRendering.onGameRenderEnd(GuiPortalRendering.java:99) ~[imm_ptl_core-v3.2.6-mc1.20.1-mapped-intermediary-1.20.1-mojmap-1.20.1-mojmap-intermediary.jar:?]
	at net.minecraft.client.renderer.GameRenderer.handler$zom000$imm_ptl_core$onAfterRenderingCenter(GameRenderer.java:3719) ~[minecraft-client-1.20.1-fixed-mojmap+intermediary.jar:?]
	at net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:880) ~[minecraft-client-1.20.1-fixed-mojmap+intermediary.jar:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1219) ~[minecraft-client-1.20.1-fixed-mojmap+intermediary.jar:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:802) ~[minecraft-client-1.20.1-fixed-mojmap+intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-client-1.20.1-fixed-mojmap+intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
```

</details>

**Comment by qouteall** [comment]
Can you post the code that triggered the issue?

**Comment by wagyourtail** [comment]
https://github.com/wagYourtail/imm_prtl_bug_test
`/execute in minecraft:the_nether run tp @s ~ ~ ~`

**Comment by qouteall** [comment]
Should be fixed. Will be in the next version.
