### ISSUE TITLE
Failed to apply dimension stack | Error during server dimensions load event [...] overworld is null

### ISSUE THREAD

**Issue by gomhaille** [qouteall/ImmersivePortalsMod#1467]
### Is it a mod compatibility issue?

No

### Minecraft version

1.20.2

### Describe the issue

I'm unable to enable the dimension stack upon world creation, due to it saying I'm missing dimensions: 
```
Failed to apply dimension stack. Missing dimension immersive_portals:chaos
Failed to apply dimension stack. Missing dimension immersive_portals:bright_skyland
Failed to apply dimension stack. Missing dimension immersive_portals:bright_void
```
It works correctly with Minecraft version `1.20.1` and Immersive Portals `3.3.5`.

The versions I've tried which failed were `4.0.3`, `4.0.2`, `4.0.1`, and `4.0.0` since all of those have `1.20.2` support. Each of them returned the same error as above about failing to apply the dimension stack.

There's also a rather large NPE in the log saying the overworld is null in each of those versions, but not in the functional `3.3.5` for `1.20.1`: 

```
[23:45:10] [Server thread/ERROR]: Error during server dimensions load event
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_8621()" because "overworld" is null
	at qouteall.q_misc_util.dimension.DynamicDimensionsImpl.addDimensionDynamically(DynamicDimensionsImpl.java:79) ~[q_misc_util-4.0.3-3f29f9b844c5752d.jar:?]
	at qouteall.q_misc_util.api.DimensionAPI.addDimensionDynamically(DimensionAPI.java:121) ~[q_misc_util-4.0.3-3f29f9b844c5752d.jar:?]
	at qouteall.q_misc_util.api.DimensionAPI.addDimension(DimensionAPI.java:70) ~[q_misc_util-4.0.3-3f29f9b844c5752d.jar:?]
	at qouteall.q_misc_util.api.DimensionAPI.addDimensionIfNotExists(DimensionAPI.java:107) ~[q_misc_util-4.0.3-3f29f9b844c5752d.jar:?]
	at qouteall.imm_ptl.peripheral.alternate_dimension.AlternateDimensions.addAltDimsIfUsedInDimStack(AlternateDimensions.java:146) ~[immersive-portals-4.0.3-mc1.20.2-fabric.jar:?]
	at qouteall.imm_ptl.peripheral.dim_stack.DimensionStackAPI.lambda$static$2(DimensionStackAPI.java:65) ~[immersive-portals-4.0.3-mc1.20.2-fabric.jar:?]
	at qouteall.imm_ptl.peripheral.dim_stack.DimStackManagement.lambda$init$0(DimStackManagement.java:49) ~[immersive-portals-4.0.3-mc1.20.2-fabric.jar:?]
	at qouteall.q_misc_util.api.DimensionAPI.lambda$static$0(DimensionAPI.java:49) ~[q_misc_util-4.0.3-3f29f9b844c5752d.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bbl000$q_misc_util$onBeforeCreateWorlds(MinecraftServer.java:6352) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:322) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3823(class_1132.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:642) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:45:11] [Server thread/INFO]: literal{Failed to apply dimension stack. Missing dimension immersive_portals:chaos}
[23:45:11] [Server thread/INFO]: Immersive Portals' Dimension Id Record File Does Not Exist
[23:45:11] [Server thread/INFO]: Immersive Portals' dimension id record is missing
[23:45:11] [Server thread/INFO]: Dimension Id Record is Missing
[23:45:11] [Server thread/INFO]: Start Completing Dimension Id Record
```
Here is the full log for the above error: [latest.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/13197376/latest.log)

I have tested with just Immersive Portals *(no other mods)* and it persists.
I also tested with Sodium added, just to sort of grasp at straws lol. It persists with this as well.

### Edit:

So, I fiddled around with the settings at world creation and managed to get `4.0.3` to work. It successfully initialises the dimension stack when using only the three vanilla dimensions -- `the_end`, `the_nether`, and `overworld`. With the default stack which includes `bright_skyland` and `bright_void` in addition to two of the vanilla ones, it always fails to initialise for me.

## The default stack which does not work:

![image](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/116980373/4ba49ce6-dd16-462b-9ac8-4724b8ed2b64)

## The edited stack which works:

![image](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/116980373/0915256d-6812-4ac7-9f94-9f15e96d2c42)

**Comment by qouteall** [comment]
Fixed in 4.1.0 https://modrinth.com/mod/immersiveportals/version/v4.1.0-mc1.20.2
That version also contains portal shape system refactoring which is still experimental
