### ISSUE TITLE
Crash at startup 1.16

### ISSUE THREAD

**Issue by maicol07** [qouteall/ImmersivePortalsMod#147]
Error in console:
```
Mixin apply failed immersive_portals.mixins.json:block_manipulation/MixinLivingEntity -> net.minecraft.class_1309: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method method_6127 in immersive_portals.mixins.json:block_manipulation/MixinLivingEntity was not located in the target class net.minecraft.class_1309. Using refmap immersive-portals-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method method_6127 in immersive_portals.mixins.json:block_manipulation/MixinLivingEntity was not located in the target class net.minecraft.class_1309. Using refmap immersive-portals-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:423)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:399)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:286)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.client.main.Main.main(Main.java:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
```

**Comment by maicol07** [comment]
@qouteall I can confirm this happens again with 1.16.1

Crash log:

```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 27/06/20, 12:30
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1081)
at net.minecraft.class_310.<init>(class_310.java:527)
at net.minecraft.client.main.Main.main(Main.java:177)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [immersive_portals.mixins_client.json:MixinWorldRenderer] from phase [DEFAULT] in config [immersive_portals.mixins_client.json] FAILED during APPLY
at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_761::redirectGetTranslucent with priority 1000 cannot inject into net/minecraft/class_761::method_3251(Lnet/minecraft/class_1921;Lnet/minecraft/class_4587;DDD)V merged by me.jellysquid.mods.sodium.mixin.chunk_rendering.MixinWorldRenderer with priority 1000 [PREINJECT Applicator Phase -> immersive_portals.mixins_client.json:MixinWorldRenderer -> Prepare Injections ->  -> redirect$bca000$redirectGetTranslucent()Lnet/minecraft/class_1921; -> Prepare]
at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:367)
at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1244)
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
... 15 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1081)
at net.minecraft.class_310.<init>(class_310.java:527)

-- Initialization --
Details:
Stacktrace:
at net.minecraft.client.main.Main.main(Main.java:177)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
Minecraft Version: 1.16.1
Minecraft Version ID: 1.16.1
Operating System: Windows 10 (amd64) version 10.0
Java Version: 14.0.1, AdoptOpenJDK
Java VM Version: Eclipse OpenJ9 VM (JRE 14 Windows 10 amd64-64-Bit Compressed References 20200422_50 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - 5757187cae based on jdk-14.0.1+7), Eclipse OpenJ9
Memory: 303289672 bytes (289 MB) / 567541760 bytes (541 MB) up to 8589934592 bytes (8192 MB)
CPUs: 8
JVM Flags: 8 total; -Xoptionsfile=D:\Program Files\AdoptOpenJDK\jdk-14.0.1.7-openj9\lib\options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC
Fabric Mods:
 amecsapi: Amecs API 1.0.2+1.16-rc1
 appleskin: AppleSkin 1.0.11
 autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
 beenfo: Beenfo 1.16-fabric0.13.1-1.0.3
 blue_endless_jankson: jankson +
 cloth-basic-math: Cloth Basic Math 0.5.1
 cloth-client-events-v0: Cloth Client Events v0 1.0.4
 cloth-config2: Cloth Config v4 4.5.6
 craftpresence: CraftPresence 1.6.6
 durabilityviewer: Giselbaers Durability Viewer 1.16-fabric0.13.1-1.7.1
 dynamicfps: Dynamic FPS 1.1.4
 enchantedtooltips: Enchanted ToolTips 1.3.1-1.16
 fabric: Fabric API 0.14.0+build.371-1.16
 fabric-api-base: Fabric API Base 0.1.3+12a8474cb0
 fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
 fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
 fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
 fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
 fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
 fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
 fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
 fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
 fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030fb0
 fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
 fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
 fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
 fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+e16a9774b0
 fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c5b0
 fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.0.0+b0993bc102
 fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.10+059ea86602
 fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
 fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
 fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
 fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
 fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.5+e00ecb5f02
 fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.0+da175ad602
 fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
 fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
 fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
 fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.2+4d66bed502
 fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
 fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
 fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
 fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
 fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
 fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.5+059ea866b0
 fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.0.1+f362c86e02
 fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
 fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
 fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e02
 fabricloader: Fabric Loader 0.8.8+build.202
 fiber: fiber 0.23.0-1
 gbfabrictools: GBfabrictools 1.2.2+1.16
 immersive_portals: Immersive Portals 0.14
 inventoryprofiles: Inventory Profiles 0.2.0
 kyrptconfig: Kytpt Config 1.0.4-1.16
 lightoverlay: Light Overlay 5.4.0
 lithium: Lithium 0.5.0-rc1
 mambience: MAmbience 2.0.0-1.16
 minecraft: Minecraft 1.16.1
 modmenu: Mod Menu 1.12.2+build.17
 mousewheelie: Mouse Wheelie 1.4.16+mc1.16-rc1
 okzoomer: Ok Zoomer 4.0.0-alpha.3.1.16.pre5
 orderly: Orderly 2.0.0-alpha.10-1.16
 phosphor: Phosphor 0.6.0+build.7
 roughlyenoughitems: Roughly Enough Items 4.5.5
 shulkerboxtooltip: Shulker Box Tootip 2.1.0+1.16.1
 smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
 sodium: Sodium 0.1.0-SNAPSHOT
 tweed: Tweed API 3.0.0-beta.9
 voxelmap: VoxelMap 1.10.1
 waila: Hwyla 1.9.22
Launched Version: fabric-loader-0.8.8+build.202-1.16.1
Backend library: LWJGL version 3.2.2 build 10
Backend API: Intel(R) UHD Graphics 620 GL version 4.6.0 - Build 27.20.100.7990, Intel
GL Caps: Using framebuffer using OpenGL 3.0
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fabric'
Type: Client (map_client.txt)
CPU: 8x Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
```

**Comment by qouteall** [comment]
This mod is currently incompatible with sodium
