### ISSUE TITLE
Crash in dedicated server due to missing field

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#1478]
### Is it a mod compatibility issue?

No

### Minecraft version

Select One

### Describe the issue

https://discord.com/channels/662271867431682058/671895714527182920/1180026058989383710

```
java.lang.NoSuchFieldError: clientLastFramePortalStateCounter
	at qouteall.imm_ptl.core.portal.animation.PortalAnimation.<init>(PortalAnimation.java:62) ~[imm_ptl_core-3.3.4-8c6f46acb93329ae.jar:?]
	at qouteall.imm_ptl.core.portal.Portal.<init>(Portal.java:247) ~[imm_ptl_core-3.3.4-8c6f46acb93329ae.jar:?]
```

**Comment by Kuinox** [comment]
Got the same problem when I lit a portal for the first time after installing the mod.
On 3 tries, it crashed the server, so I'm gonna remove the mods for now.  
Do you need additional info to fix this ? I see that you have put the label "Hard to Reproduce".

**Comment by qouteall** [comment]
@Kuinox Which MC version? If 1.20.1, 1.20.2, 1.19.4, 1.19.3 the latest version on modrinth may fix th issue

**Comment by Kuinox** [comment]
1.20.1, I'll try.
