### ISSUE TITLE
Not compatible with Vanish mod (Mixin Conflict)

### ISSUE THREAD

**Issue by Caedorus** [qouteall/ImmersivePortalsMod#1479]
### Is it a mod compatibility issue?

Yes

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

https://modrinth.com/mod/vanish/

### Minecraft version

1.19.2

### Describe the issue

[latest.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/13530745/latest.log)
Just thought I'd mention it, unlikely to get fixed

**Comment by qouteall** [comment]
```
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [vanish.mixins.json:PlayerListMixin from mod melius-vanish] from phase [DEFAULT] in config [vanish.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.24.jar:?]
	... 12 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_3324::vanish_hideGameEvents with priority 1000 cannot inject into net/minecraft/class_3324::method_14605(Lnet/minecraft/class_1657;DDDDLnet/minecraft/class_5321;Lnet/minecraft/class_2596;)V merged by qouteall.imm_ptl.core.mixin.common.other_sync.MixinPlayerList with priority 1000 [PREINJECT Applicator Phase -> vanish.mixins.json:PlayerListMixin from mod melius-vanish -> Prepare Injections ->  -> wrapWithCondition$bfj000$melius-vanish$vanish_hideGameEvents(Lnet/minecraft/class_3244;Lnet/minecraft/class_2596;Lnet/minecraft/class_1657;)Z -> Prepare]

```
