### ISSUE TITLE
Fabric 1.20.1: Random occassional kick

### ISSUE THREAD

**Issue by LokeYourC3PH** [qouteall/ImmersivePortalsMod#1485]
### Is it a mod compatibility issue?

No

### Minecraft version

1.20.1

### Describe the issue

Sometimes, me and my friends get randomly kicked from the server with the following error:

```
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(11) + length(1) exceeds writerIndex(11): PooledUnsafeDirectByteBuf(ridx: 11, widx: 11, cap: 11)
 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.82.Final.jar:?]
 	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-buffer-4.1.82.Final.jar:?]
 	at net.minecraft.network.PacketByteBuf.readByte(PacketByteBuf.java:1303) ~[client-intermediary.jar:?]
 	at net.minecraft.network.packet.s2c.play.EntityEquipmentUpdateS2CPacket.<init>(EntityEquipmentUpdateS2CPacket.java:28) ~[client-intermediary.jar:?]
 	at net.minecraft.network.NetworkState$PacketHandler.createPacket(NetworkState.java:459) ~[client-intermediary.jar:?]
 	at net.minecraft.network.NetworkState.getPacketHandler(NetworkState.java:522) ~[client-intermediary.jar:?]
 	at qouteall.imm_ptl.core.network.PacketRedirection.createPacketById(PacketRedirection.java:161) ~[imm_ptl_core-3.3.7-f6ec9a0b46a5a264.jar:?]
 	at net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket.handler$fgd000$imm_ptl_core$readTheActualRedirectedPacket(CustomPayloadS2CPacket.java:1563) ~[client-intermediary.jar:?]
 	at net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket.<init>(CustomPayloadS2CPacket.java:50) ~[client-intermediary.jar:?]
 	at net.minecraft.network.NetworkState$PacketHandler.createPacket(NetworkState.java:459) ~[client-intermediary.jar:?]
 	at net.minecraft.network.NetworkState.getPacketHandler(NetworkState.java:522) ~[client-intermediary.jar:?]
 	at net.minecraft.network.DecoderHandler.decode(DecoderHandler.java:32) ~[client-intermediary.jar:?]
 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519) ~[netty-codec-4.1.82.Final.jar:?]
 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458) ~[netty-codec-4.1.82.Final.jar:?]
 	... 37 more
```

**Comment by qouteall** [comment]
Is it LAN multiplaying or dedicated server?

To know whether it's a mod compatibility issue, does this issue occur with only immersive portals mod and fabric api in a freshly created new world?

**Comment by LokeYourC3PH** [comment]
> Is it LAN multiplaying or dedicated server?
> 
> To know whether it's a mod compatibility issue, does this issue occur with only immersive portals mod and fabric api in a freshly created new world?

Dedicated Server.

And I cannot remove 300 mods from an actively played on server, but suffice to say it probably doesn't happen on its own no.
