### ISSUE TITLE
Allow newer versions of dependencies [MC 1.20.1]

### ISSUE THREAD

**Issue by Mrgaton** [qouteall/ImmersivePortalsMod#1536]
### Is it a mod compatibility issue?

No

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
Hemos encontrado una solución prometedora:
	 - Quita el mod 'Iris' (iris) 1.7.0-snapshot+mc1.20.1-7edecd1 (C:\Users\Mrgaton\AppData\Roaming\.minecraft\mods\iris-1.7.0-snapshot+mc1.20.1-7edecd1.jar).
	 - Cambia el mod 'Immersive Portals' (immersive_portals) 3.3.7 por cualquier versión que sea compatible con:
		 - sodium, la versión 0.5.8
	 - Cambia el mod 'Sodium' (sodium) 0.5.8+mc1.20.1 por la versión 0.5.8 que sea compatible con:
		 - immersive_portals, cualquier versión
Dependencias no satisfechas:
	 - ¡El mod 'Immersive Portals' (immersive_portals) 3.3.7 no es compatible con cualquier versión anterior a 1.6.11 o cualquier versión tras 1.6.11 de el mod 'Iris' (iris), pero tienes una versión coincidente presente : 1.7.0-snapshot+mc1.20.1-7edecd1!
	 - ¡El mod 'Immersive Portals' (immersive_portals) 3.3.7 no es compatible con cualquier versión anterior a 0.5.3 o cualquier versión tras 0.5.3 de el mod 'Sodium' (sodium), pero tienes una versión coincidente presente : 0.5.8+mc1.20.1!
	 - ¡El mod 'Sodium' (sodium) 0.5.8+mc1.20.1 no es compatible con la versión 3.3.9 o una anterior de el mod 'Immersive Portals' (immersive_portals), pero tienes una versión coincidente presente : 3.3.7!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Minecraft version

1.20.1

### Describe the issue

Im using beta versions of iris and it trows error without even tryng

**Comment by Mrgaton** [comment]
just imagine immersive portals + distants horrizons + physics mod pro + iris shaders

it would be unbelievable

**Comment by Mrgaton** [comment]
but better wait to the official release of dh + iris

**Comment by LOSEARDES77** [comment]
I found that what breaks immersive portals irish compatibility is that iris is currently doing a big code refactor and the package names are changind but it should only be that

**Comment by Mrgaton** [comment]
i said that better wait for the official releases of iris and dh

**Comment by TriibuNupsik** [comment]
I need sodium compatibility to be increased to update my modpack.

**Comment by Mrgaton** [comment]
Now is a good time to update it yes @qouteall

**Comment by qouteall** [comment]
The development efforts are limited (and I am kind of burnt out now) and I will focus on MC 1.21. This fork exists https://modrinth.com/mod/immersive-portals-continued

**Comment by Mrgaton** [comment]
Interesting

**Comment by Mortycio** [comment]
> The development efforts are limited (and I am kind of burnt out now) and I will focus on MC 1.21. This fork exists https://modrinth.com/mod/immersive-portals-continued

Even this mod is incompatible with Sodium and does not work properly.

https://mclo.gs/Wg6jbNW

![image](https://github.com/user-attachments/assets/fb12abd3-8032-4a10-8e75-516cf377ae3c)

**Comment by Mrgaton** [comment]
Oh, then we will just wait to @qouteall to someday he doesn't have anything to do to fix it

**Comment by Mortycio** [comment]
@qouteall You just marked both posts as "closed" simply by mentioning one to the other and vice versa without actually providing a solution... or did I misunderstand?

**Comment by qouteall** [comment]
@Mortycio Because that issue is duplicate to this issue.

**Comment by Mortycio** [comment]
@qouteall Ok, but... why did you close both of them? The issue hasn't been resolved. Close the duplicate and leave the "original" post open while waiting for a solution 😅😓

**Comment by SalTeyJek004** [comment]
this issue is not closed

**Comment by Mortycio** [comment]
Oh! I saw the "closed" purple button on the mention line and thought it was referring to this post! Sorry, I'm not used to Github! 🥹

**Comment by TSEG6** [comment]
this is also an issue on 1.21 as well
