### ISSUE TITLE
Minecraft crash when rendering the overworld while i'm in the nether

### ISSUE THREAD

**Issue by ClosedTheDor** [qouteall/ImmersivePortalsMod#1557]
### Is it a mod compatibility issue?

No

### Minecraft version

1.20.4

### Describe the issue

I made a modpack and evrything worked fine, i opened the nether with all my mods Immersive portl work fine i go to the nether then i save and quit in the nether i come back then it's crashing and crashing idk what to do  
here the log : [latest.log]([latest.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/15446729/latest.log)

**Comment by ArcaneAlloy** [comment]
It happens the same error for me but in Fabric 1.20.1 0.15.11

[latest.log](https://github.com/user-attachments/files/16041398/latest.log)

**Comment by qouteall** [comment]
~~Seem to be related to JEI and better nether~~
```
[09:54:38] [Render thread/ERROR]: Caught an error from mod plugin: class jeresources.jei.JEIConfig minecraft:jeresources
java.lang.ExceptionInInitializerError: null
	at jeresources.api.restrictions.Restriction.<init>(Restriction.java:23) ~[JustEnoughResources-Fabric-1.20.4-1.5.0.4.jar:?]
	at jeresources.api.restrictions.Restriction.<clinit>(Restriction.java:6) ~[JustEnoughResources-Fabric-1.20.4-1.5.0.4.jar:?]
	at jeresources.compatibility.minecraft.MinecraftCompat.registerOres(MinecraftCompat.java:67) ~[JustEnoughResources-Fabric-1.20.4-1.5.0.4.jar:?]
	at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:37) ~[JustEnoughResources-Fabric-1.20.4-1.5.0.4.jar:?]
	at jeresources.compatibility.Compatibility.init(Compatibility.java:27) ~[JustEnoughResources-Fabric-1.20.4-1.5.0.4.jar:?]
	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14) ~[JustEnoughResources-Fabric-1.20.4-1.5.0.4.jar:?]
	at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:98) ~[JustEnoughResources-Fabric-1.20.4-1.5.0.4.jar:?]
	at mezz.jei.library.load.PluginLoader.lambda$createRecipeCategories$4(PluginLoader.java:97) ~[jei-1.20.4-fabric-17.3.0.52.jar:?]
	at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:27) ~[jei-1.20.4-fabric-17.3.0.52.jar:?]
	at mezz.jei.library.load.PluginLoader.createRecipeCategories(PluginLoader.java:97) ~[jei-1.20.4-fabric-17.3.0.52.jar:?]
	at mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:126) ~[jei-1.20.4-fabric-17.3.0.52.jar:?]
	at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:132) ~[jei-1.20.4-fabric-17.3.0.52.jar:?]
	at mezz.jei.fabric.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:84) ~[jei-1.20.4-fabric-17.3.0.52.jar:?]
	at mezz.jei.fabric.startup.ClientLifecycleHandler.lambda$registerEvents$1(ClientLifecycleHandler.java:53) ~[jei-1.20.4-fabric-17.3.0.52.jar:?]
	at mezz.jei.fabric.events.JeiLifecycleEvents.lambda$static$4(JeiLifecycleEvents.java:28) ~[jei-1.20.4-fabric-17.3.0.52.jar:?]
	at net.minecraft.class_634.handler$egh002$jei$handleUpdateRecipes(class_634.java:11443) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11106(class_634.java:1442) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.method_11997(class_2788.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.method_11054(class_2788.java:15) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[client-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
Caused by: java.lang.IllegalStateException: Errors during registry creation
	at net.minecraft.class_7877$class_7878.method_46798(class_7877.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_7877.method_46780(class_7877.java:291) ~[client-intermediary.jar:?]
	at net.minecraft.class_7887.method_46817(class_7887.java:96) ~[client-intermediary.jar:?]
	at jeresources.api.util.BiomeHelper.getBiome(BiomeHelper.java:20) ~[JustEnoughResources-Fabric-1.20.4-1.5.0.4.jar:?]
	at jeresources.api.restrictions.BiomeRestriction.<init>(BiomeRestriction.java:46) ~[JustEnoughResources-Fabric-1.20.4-1.5.0.4.jar:?]
	at jeresources.api.restrictions.BiomeRestriction.<clinit>(BiomeRestriction.java:19) ~[JustEnoughResources-Fabric-1.20.4-1.5.0.4.jar:?]
	... 30 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / betternether:old_warped_woods]
		at net.minecraft.class_7877$class_7878.method_55299(class_7877.java:167) ~[client-intermediary.jar:?]
		at net.minecraft.class_7877.method_46780(class_7877.java:289) ~[client-intermediary.jar:?]
		at net.minecraft.class_7887.method_46817(class_7887.java:96) ~[client-intermediary.jar:?]

```

**Comment by qouteall** [comment]
```
java.lang.NullPointerException: Cannot read field "field_27383" because "this.field_27368" is null
	at net.minecraft.class_291.method_35665(class_291.java:109) ~[client-intermediary.jar:?]
	at net.minecraft.class_291.method_34431(class_291.java:181) ~[client-intermediary.jar:?]
	at net.minecraft.class_291.method_34427(class_291.java:123) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_3257(class_761.java:1851) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1014) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1098) ~[client-intermediary.jar:?]
	at qouteall.imm_ptl.core.render.MyGameRenderer.lambda$switchAndRenderTheWorld$1(MyGameRenderer.java:229) ~[immersive-portals-5.1.8-mc1.20.4-fabric.jar:?]
	at qouteall.imm_ptl.core.render.MyGameRenderer.switchAndRenderTheWorld(MyGameRenderer.java:227) ~[immersive-portals-5.1.8-mc1.20.4-fabric.jar:?]
	at qouteall.imm_ptl.core.render.MyGameRenderer.renderWorldNew(MyGameRenderer.java:103) ~[immersive-portals-5.1.8-mc1.20.4-fabric.jar:?]

```

**Comment by qouteall** [comment]
Log shows that many mods are installed. This may be a mod compatibility issue.

**Comment by qouteall** [comment]
Please find out whether this issue occurs with only iPortal or which specific mod is incompatible

If you don't know which specific mod is incompatible, binary search is a way of finding the incompatible mod without removing the mods one-by-one. The procedure is simple:

Backup the world (because removing mod cause its content to be removed).
Remove half of the existing mods, and put them aside.
Run the game.
Does the issue still exist?
If YES: Repeat from step 2 with the current mods.
If NO: Swap out the current mods with the ones set aside, and repeat from step 1.
Repeat this process until the problematic mod(s) have been found.

**Comment by qouteall** [comment]
Issue closed because the issue opener haven't provided requested information for a long time.

**Comment by ClosedTheDor** [comment]
Oh yes it fixed, it was an error from iris (not sodium whopps) had to update it thx anyways
