### ISSUE TITLE
Redstone Resistor entity tick (compatibility with Valkyrien skies)

### ISSUE THREAD

**Issue by fartunrus** [qouteall/ImmersivePortalsMod#1565]
### Is it a mod compatibility issue?

Select One

### Minecraft version

1.20.1

### Describe the issue

With the clockwork redstone resistor at some speed the game just crashes and  the world doesn't load.
[crash-2024-06-12_10.03.26-client.txt](https://github.com/user-attachments/files/15799968/crash-2024-0
[crash-2024-06-12_09.59.56-server.txt](https://github.com/user-attachments/files/15799983/crash-2024-06-12_09.59.56-server.txt)
6-12_10.03.26-client.txt)

**Comment by qouteall** [comment]
The crash is related to valkyrien skies

```
java.lang.StackOverflowError: Ticking block entity
	at org.valkyrienskies.core.impl.game.ships.ShipObjectWorld.isChunkInShipyard(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23417!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at org.valkyrienskies.mod.common.VSGameUtilsKt.isChunkInShipyard(VSGameUtilsKt.java:224) ~[valkyrienskies-120-2.3.0-beta.5.jar%23417!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at org.valkyrienskies.mod.common.VSGameUtilsKt.getShipManagingPosImpl(VSGameUtilsKt.java:287) ~[valkyrienskies-120-2.3.0-beta.5.jar%23417!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at org.valkyrienskies.mod.common.VSGameUtilsKt.getShipManagingPos(VSGameUtilsKt.java:311) ~[valkyrienskies-120-2.3.0-beta.5.jar%23417!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at org.valkyrienskies.mod.common.VSGameUtilsKt.getShipManagingPos(VSGameUtilsKt.java:314) ~[valkyrienskies-120-2.3.0-beta.5.jar%23417!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at org.valkyrienskies.create_interactive.code.Foster.geographical(Unknown Source) ~[create_interactive-1201-forge-1.0.2-beta.2.jar%23323!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at com.simibubi.create.content.kinetics.RotationPropagator.handler$dli000$somebody(RotationPropagator.java) ~[create-1.20.1-0.5.1.f.jar%23317!/:0.5.1.f] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:vs_clockwork-common.mixins.json:content.universal_joint.MixinRotationPropagator,pl:mixin:APP:create_connected.mixins.json:chaincogwheel.RotationPropagatorMixin,pl:mixin:APP:create_interactive-common.mixins.json:kinetics.MixinRotationPropagator,pl:mixin:A}
	at com.simibubi.create.content.kinetics.RotationPropagator.getPotentialNeighbourLocations(RotationPropagator.java:445) ~[create-1.20.1-0.5.1.f.jar%23317!/:0.5.1.f] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:vs_clockwork-common.mixins.json:content.universal_joint.MixinRotationPropagator,pl:mixin:APP:create_connected.mixins.json:chaincogwheel.RotationPropagatorMixin,pl:mixin:APP:create_interactive-common.mixins.json:kinetics.MixinRotationPropagator,pl:mixin:A}
	at com.simibubi.create.content.kinetics.RotationPropagator.getConnectedNeighbours(RotationPropagator.java:417) ~[create-1.20.1-0.5.1.f.jar%23317!/:0.5.1.f] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:vs_clockwork-common.mixins.json:content.universal_joint.MixinRotationPropagator,pl:mixin:APP:create_connected.mixins.json:chaincogwheel.RotationPropagatorMixin,pl:mixin:APP:create_interactive-common.mixins.json:kinetics.MixinRotationPropagator,pl:mixin:A}
	at com.simibubi.create.content.kinetics.RotationPropagator.propagateNewSource(RotationPropagator.java:225) ~[create-1.20.1-0.5.1.f.jar%23317!/:0.5.1.f] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:vs_clockwork-common.mixins.json:content.universal_joint.MixinRotationPropagator,pl:mixin:APP:create_connected.mixins.json:chaincogwheel.RotationPropagatorMixin,pl:mixin:APP:create_interactive-common.mixins.json:kinetics.MixinRotationPropagator,pl:mixin:A}
	at com.simibubi.create.content.kinetics.RotationPropagator.propagateNewSource(RotationPropagator.java:263) ~[create-1.20.1-0.5.1.f.jar%23317!/:0.5.1.f] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:vs_clockwork-common.mixins.json:content.universal_joint.MixinRotationPropagator,pl:mixin:APP:create_connected.mixins.json:chaincogwheel.RotationPropagatorMixin,pl:mixin:APP:create_interactive-common.mixins.json:kinetics.MixinRotationPropagator,pl:mixin:A}
	at com.simibubi.create.content.kinetics.RotationPropagator.propagateNewSource(RotationPropagator.java:263) ~[create-1.20.1-0.5.1.f.jar%23317!/:0.5.1.f] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:vs_clockwork-common.mixins.json:content.universal_joint.MixinRotationPropagator,pl:mixin:APP:create_connected.mixins.json:chaincogwheel.RotationPropagatorMixin,pl:mixin:APP:create_interactive-common.mixins.json:kinetics.MixinRotationPropagator,pl:mixin:A}

```

**Comment by qouteall** [comment]
https://github.com/iPortalTeam/ImmersivePortalsMod/issues/1530
