### ISSUE TITLE
incompatible mods error even if i am using the latest versions of sodium and iris

### ISSUE THREAD

**Issue by nohansantosfrancos** [qouteall/ImmersivePortalsMod#1650]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Remove mod 'Iris' (iris) 1.8.0-beta.7+mc1.21.1 (C:\Users\nohan\AppData\Roaming\.tlauncher\legacy\Minecraft\game\mods\iris-fabric-1.8.0-beta.7+mc1.21.1.jar).
	 - Replace mod 'Immersive Portals' (immersive_portals) 6.0.4 with any version that is compatible with:
		 - sodium 0.6.0-beta.4+mc1.21.1
More details:
	 - Mod 'Immersive Portals' (immersive_portals) 6.0.4 is incompatible with any version before 1.7.3 or any version after 1.7.3 of mod 'Iris' (iris), but a matching version is present: 1.8.0-beta.7+mc1.21.1!
	 - Mod 'Immersive Portals' (immersive_portals) 6.0.4 is incompatible with any version before 0.5.11 or any version after 0.5.11 of mod 'Sodium' (sodium), but a matching version is present: 0.6.0-beta.4+mc1.21.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by TPK-91** [comment]
Same problem here (on Minecraft version 1.21.1). Switching to Iris version to 1.7.3 and Sodium version 0.5.11 works, but you may need to change the version of other mods.
I'm also using Distant Horizons 2.2, which seems to be incompatible with Iris versions below 1.7.5 (at least with MC 1.21.1). So running with Iris 1.7.3 gives:

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Remove mod 'Iris' (iris) 1.7.3+mc1.21 (C:\Users\***\AppData\Roaming\.minecraft\mods\iris-1.7.3+mc1.21.jar).
More details:
	 - Mod 'Distant Horizons' (distanthorizons) 2.2.0-a is incompatible with version 1.7.4 or earlier of mod 'Iris' (iris), but a matching version is present: 1.7.3+mc1.21!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by yakirfranko** [comment]
same issue do you know of a list  of mods incompatible with those versions of iris and sodium so that i may check if i have any installed
