### ISSUE TITLE
Immersive_portals:dimension_confirm causing issue with length of channels

### ISSUE THREAD

**Issue by Xplodin** [qouteall/ImmersivePortalsMod#18]
Couldn't register custom payload
--
org.bukkit.plugin.messaging.ChannelNameTooLongException: Attempted to send a Plugin Message to a channel that was too large. The maximum length a channel may be is 32 chars (attempted 35 - 'immersive_portals:dimension_confirm.
at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:500) ~[spigot-1.14.4.jar:git-Spigot-a596182-edd8fdf]
at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.addChannel(CraftPlayer.java:1258) ~[spigot-1.14.4.jar:git-Spigot-a596182-edd8fdf]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2442) ~[spigot-1.14.4.jar:git-Spigot-a596182-edd8fdf]
at net.minecraft.server.v1_14_R1.PacketPlayInCustomPayload.a(SourceFile:45) ~[spigot-1.14.4.jar:git-Spigot-a596182-edd8fdf]
at net.minecraft.server.v1_14_R1.PacketPlayInCustomPayload.a(SourceFile:9) ~[spigot-1.14.4.jar:git-Spigot-a596182-edd8fdf]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-a596182-edd8fdf]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-a596182-edd8fdf]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-a596182-edd8fdf]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-a596182-edd8fdf]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-a596182-edd8fdf]
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot-1.14.4.jar:git-Spigot-a596182-edd8fdf]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot-1.14.4.jar:git-Spigot-a596182-edd8fdf]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.14.4.jar:git-Spigot-a596182-edd8fdf]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot-1.14.4.jar:git-Spigot-a596182-edd8fdf]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot-1.14.4.jar:git-Spigot-a596182-edd8fdf]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by qouteall** [comment]
I changed it to dim_confirm. This should fix it.

**Comment by qouteall** [comment]
check 0.14 and see whether this issue still exists

**Comment by Xplodin** [comment]
That fixed that issue. Does this require servers to have this installed?

**Comment by qouteall** [comment]
yes
