### ISSUE TITLE
Crash with Rendering Double Slabs Through Portal

### ISSUE THREAD

**Issue by da3dsoul** [qouteall/ImmersivePortalsMod#211]
```
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
	at cjminecraft.doubleslabs.client.model.DoubleSlabBakedModel.getQuads(DoubleSlabBakedModel.java:75) ~[?:1.0.3] {re:classloading}
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:99) ~[?:?] {re:classloading}
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:84) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:50) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:60) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRender.func_178581_b(ChunkRender.java:190) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:90) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:39) ~[?:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_51] {}
```

**Comment by da3dsoul** [comment]
Okay, I didn't notice that those weren't vanilla double slabs. They are Double Slabs from cjminecraft (a mod that lets you mix and match slabs), which make a pretty big difference. I actually have no idea what might cause or fix this. I had them as just oak slabs on both halves, so realistically, I can fix this in my world and avoid it.

**Comment by qouteall** [comment]
Close because outdated.
