### ISSUE TITLE
I get this crash on entering the nether through dimension stack

### ISSUE THREAD

**Issue by lukec3131** [qouteall/ImmersivePortalsMod#365]
The game crashed whilst exception generating new chunk
Error: java.util.ConcurrentModificationException

**Comment by qouteall** [comment]
Did you install any mod that changes world generation?

**Comment by lukec3131** [comment]
Yeah I have terrestria installed

**Comment by qouteall** [comment]
Show the full crash report

**Comment by lukec3131** [comment]
Okay I think its this one


---- Minecraft Crash Report ----
// Why did you do that?

Time: 31/07/20 11:54
Description: Exception generating new chunk

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
	at net.minecraft.class_2794.carve(class_2794.java:1078)
	at net.minecraft.class_2806.handler$zpg000$carveSanelyAir(class_2806.java:1024)
	at net.minecraft.class_2806.method_16563(class_2806.java)
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:263)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)
	at net.minecraft.class_3898.method_17225(class_3898.java:568)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)
	at net.minecraft.class_3846.run(class_3846.java:105)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
	at net.minecraft.class_2794.carve(class_2794.java:1078)
	at net.minecraft.class_2806.handler$zpg000$carveSanelyAir(class_2806.java:1024)
	at net.minecraft.class_2806.method_16563(class_2806.java)
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:263)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)

-- Chunk to be generated --
Details:
	Location: -2,-23
	Position hash: -94489280514
	Generator: net.minecraft.class_3754@42c1bcee
Stacktrace:
	at net.minecraft.class_3898.method_17225(class_3898.java:568)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 3249
	Level dimension: minecraft:overworld
	Level spawn location: World: (192,72,-128), Chunk: (at 0,4,0 in 12,-8; contains blocks 192,0,-128 to 207,255,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 81 game time, 81 day time
	Level name: FABRIC WORLD STSKC
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 129353 (now: false), thunder time: 65049 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:876)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:813)
	at net.minecraft.class_1132.method_3748(class_1132.java:93)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:672)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Mac OS X (x86_64) version 10.15.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 868746576 bytes (828 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		campanion: Campanion 1.1.13+build.35
		cavebiomes: Cave Biomes 0.2.4
		cinderscapes: Cinderscapes 1.0.7+build.43-1.16.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.6.0
		convenient-mobgriefing: Convenient mobGriefing Gamerules 1.1.2
		cotton: Cotton 1.0.7
		cotton-commons: Cotton Commons 1.0.4
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-datapack: Cotton Datapack 1.0.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		cotton-player-events: Cotton Player Events 1.0.2
		ecotones: Ecotones 0.5.1
		fabric: Fabric API 0.16.2+build.385-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c02
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+e83e061c02
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.6+a2d21ddd02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+34d6c87102
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.0+55e0cc5f02
		fabricloader: Fabric Loader 0.9.0+build.204
		immersive_portals: Immersive Portals 0.24
		jankson: Jankson 2.0.1+j1.2.0
		libstructure: Libstructure 1.3
		lithium: Lithium 0.5.1
		logical_zoom: Logical Zoom 0.0.4
		minecraft: Minecraft 1.16.1
		modmenu: Mod Menu 1.14.5+build.30
		pehkui: Pehkui 1.5.3+1.16.1
		phosphor: Phosphor 0.6.0+build.7
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		shapes: Shapes 2.0.0+build.10
		terraform: Terraform 2.1.7+build.31
		terrestria: Terrestria 2.0.4+build.50
		traverse: Traverse 2.2.14+build.28
		vanillaenhanced: VanillaEnhanced 0.3.1
		wendigoism: Wendigoism r6
		white_rabbit: White Rabbit 1.0.3+1.16.1
		xaerominimap: Xaero's Minimap 20.18.0
		xaeroworldmap: Xaero's World Map 1.8.0
	Player Count: 1 / 8; [class_3222['lukec_'/185, l='ServerLevel[FABRIC WORLD STSKC]', x=205.53, y=125.00, z=-135.61]]
	Data Packs: vanilla (incompatible), fabric/terrestria, fabric/white_rabbit, fabric/campanion, fabric/ecotones, fabric/traverse, fabric/wendigoism, fabric/cotton-commons, fabric/fabric-tool-attribute-api-v1, fabric/vanillaenhanced, fabric/cinderscapes, global/cotton_generated (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by lukec3131** [comment]
[crash-2020-07-31_11.54.32-server.txt](https://github.com/qouteall/ImmersivePortalsMod/files/5006857/crash-2020-07-31_11.54.32-server.txt)

**Comment by qouteall** [comment]
I added lock for world generation carving when dimension stack is enabled. This should be fixed in the next version
