### ISSUE TITLE
Optifine Crashing

### ISSUE THREAD

**Issue by tetonis** [qouteall/ImmersivePortalsMod#38]
When I used optifine fabric and the portals mod it doesn't load the game, here is the crash report:
`---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 11/3/19 8:58 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at com.qouteall.immersive_portals.optifine_compatibility.ShaderCullingManager.init(ShaderCullingManager.java:52)
	at net.minecraft.class_310.handler$onInitEnded$zga000(class_310.java:4987)
	at net.minecraft.class_310.method_1503(class_310.java:613)
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:188)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.qouteall.immersive_portals.optifine_compatibility.ShaderCullingManager.init(ShaderCullingManager.java:52)
	at net.minecraft.class_310.handler$onInitEnded$zga000(class_310.java:4987)
	at net.minecraft.class_310.method_1503(class_310.java:613)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:188)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 932166784 bytes (888 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.4.1+build.245-1.14
		fabric-api-base: Fabric API Base 0.1.1+2ac73e7242
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.0+591e97ae42
		fabric-commands-v0: Fabric Commands (v0) 0.1.1+591e97ae42
		fabric-containers-v0: Fabric Containers (v0) 0.1.2+591e97ae42
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.1+591e97ae42
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.1+591e97ae42
		fabric-dimensions-v1: fabric-dimensions-v1 0.1.0+369ab22e42
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.1.1+591e97ae42
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.1+591e97ae42
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.0+591e97ae42
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+591e97ae42
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.0+591e97ae42
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.0+591e97ae42
		fabric-models-v0: Fabric Models (v0) 0.1.0+591e97ae42
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.0+c877038942
		fabric-networking-v0: Fabric Networking (v0) 0.1.3+591e97ae42
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.1+591e97ae42
		fabric-particles-v1: fabric-particles-v1 0.1.1+c877038942
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.2+591e97ae42
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.1.1+591e97ae42
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.1.13+591e97ae42
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.1+c877038942
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.2+36f27aa342
		fabric-rendering-v0: Fabric Rendering (v0) 0.1.1+591e97ae42
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.3+591e97ae42
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.1+591e97ae42
		fabric-textures-v0: Fabric Textures (v0) 0.1.4+591e97ae42
		fabricloader: Fabric Loader 0.6.3+build.168
		immersive_portals: Immersive Portals 0.25
		minecraft: Minecraft 1.14.4
		mm: Manningham Mills 1.6
		net_fabricmc_stitch: stitch 0.2.1.61
		optifabric: Optifabric 0.5.2
		org_slf4j_slf4j-api: slf4j-api 1.7.26
		org_slf4j_slf4j-simple: slf4j-simple 1.7.26
		org_zeroturnaround_zt-zip: zt-zip 1.13
	Launched Version: fabric-loader-0.6.3+build.168-1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 436.02, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x AMD Ryzen 3 1200 Quad-Core Processor `

**Comment by qouteall** [comment]
Which version of optifine are you using? it's currently not compatible with the newest optifine version
