### ISSUE TITLE
Crashing after touching blocks after reentering portal

### ISSUE THREAD

**Issue by J-61042** [qouteall/ImmersivePortalsMod#40]
When I was play in a single player world trying to find content to post on my dead Instagram account, I made the portal for the first time and crash many times for some reason. Then I was testing around to see why and the key factor on this is that when I hit a block after I am in the over-world it would crash my game. This will happen if I re enter to break a block in the nether or in the over-world. I do hope you can fix this m8s. First time sending a report on this site, so I hope this is properly formatted to your liking. 
`---- Minecraft Crash Report ----
// Shall we play a game?

Time: 11/18/19 6:29 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.class_798.method_3471(class_798.java:22)
	at net.minecraft.class_798.<init>(class_798.java:15)
	at net.minecraft.class_1093$class_1094.<init>(class_1093.java:100)
	at net.minecraft.class_776.method_3354(class_776.java:47)
	at net.minecraft.class_761.method_3256(class_761.java:2034)
	at net.minecraft.class_757.method_3178(class_757.java:882)
	at net.minecraft.class_757.method_3188(class_757.java:766)
	at net.minecraft.class_757.method_3192(class_757.java:630)
	at net.minecraft.class_310.method_1523(class_310.java:954)
	at net.minecraft.class_310.method_1514(class_310.java:410)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:188)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.class_798.method_3471(class_798.java:22)
	at net.minecraft.class_798.<init>(class_798.java:15)
	at net.minecraft.class_1093$class_1094.<init>(class_1093.java:100)
	at net.minecraft.class_776.method_3354(class_776.java:47)
	at net.minecraft.class_761.method_3256(class_761.java:2034)
	at net.minecraft.class_757.method_3178(class_757.java:882)
	at net.minecraft.class_757.method_3188(class_757.java:766)

-- Affected level --
Details:
	All players: 1 total; [class_746['X_Event'/169, l='MpServer', x=-40.93, y=32.00, z=17.81]]
	Chunk stats: Client Chunk Manager Hacked by Immersive Portals Mod
	Level dimension: minecraft:the_nether
	Level name: MpServer
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (-208,65,149), Chunk: (at 0,4,5 in -13,9; contains blocks -208,0,144 to -193,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 85650 game time, 85650 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:421)
	at net.minecraft.class_310.method_1587(class_310.java:1923)
	at net.minecraft.class_310.method_1514(class_310.java:430)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:188)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 514849248 bytes (490 MB) / 2147483648 bytes (2048 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 12
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xmx3G
	Fabric Mods: 
		fabric: Fabric API 0.4.1+build.245-1.14
		fabric-api-base: Fabric API Base 0.1.1+2ac73e7242
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.0+591e97ae42
		fabric-commands-v0: Fabric Commands (v0) 0.1.1+591e97ae42
		fabric-containers-v0: Fabric Containers (v0) 0.1.2+591e97ae42
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.1+591e97ae42
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.1+591e97ae42
		fabric-dimensions-v1: fabric-dimensions-v1 0.1.0+369ab22e42
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.1.1+591e97ae42
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.1+591e97ae42
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.0+591e97ae42
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+591e97ae42
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.0+591e97ae42
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.0+591e97ae42
		fabric-models-v0: Fabric Models (v0) 0.1.0+591e97ae42
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.0+c877038942
		fabric-networking-v0: Fabric Networking (v0) 0.1.3+591e97ae42
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.1+591e97ae42
		fabric-particles-v1: fabric-particles-v1 0.1.1+c877038942
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.2+591e97ae42
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.1.1+591e97ae42
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.1.13+591e97ae42
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.1+c877038942
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.2+36f27aa342
		fabric-rendering-v0: Fabric Rendering (v0) 0.1.1+591e97ae42
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.3+591e97ae42
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.1+591e97ae42
		fabric-textures-v0: Fabric Textures (v0) 0.1.4+591e97ae42
		fabricloader: Fabric Loader 0.6.4+build.169
		immersive_portals: Immersive Portals 0.7
		minecraft: Minecraft 1.14.4
	Launched Version: fabric-loader-0.6.4+build.169-1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.73, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz`

**Comment by J-61042** [comment]
Turns out that this was because I used the 0.07UPDATE since a site used an outdated version I did not notice until I did more research on this and found a more updated version of this mode. And that update has the fix to my problem.
