### ISSUE TITLE
Issue with age of exile

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#419]
```
[21:29:03] [main/INFO]: [STDERR]: java.lang.NullPointerException
[21:29:03] [main/INFO]: [STDERR]: 	at java.util.Objects.requireNonNull(Unknown Source)
[21:29:03] [main/INFO]: [STDERR]: 	at com.robertx22.age_of_exile.uncommon.utilityclasses.EntityFinder$Setup.<init>(EntityFinder.java:209)
[21:29:03] [main/INFO]: [STDERR]: 	at com.robertx22.age_of_exile.uncommon.utilityclasses.EntityFinder.start(EntityFinder.java:180)
[21:29:03] [main/INFO]: [STDERR]: 	at com.robertx22.age_of_exile.database.data.spells.entities.SimpleProjectileEntity.getEntityHit(SimpleProjectileEntity.java:128)
[21:29:03] [main/INFO]: [STDERR]: 	at com.robertx22.age_of_exile.database.data.spells.entities.SimpleProjectileEntity.onImpact(SimpleProjectileEntity.java:292)
[21:29:03] [main/INFO]: [STDERR]: 	at com.robertx22.age_of_exile.database.data.spells.entities.SimpleProjectileEntity.method_7488(SimpleProjectileEntity.java:283)
[21:29:03] [main/INFO]: [STDERR]: 	at net.minecraft.class_1665.method_5773(class_1665.java:227)
[21:29:03] [main/INFO]: [STDERR]: 	at com.robertx22.age_of_exile.database.data.spells.entities.SimpleProjectileEntity.method_5773(SimpleProjectileEntity.java:215)
[21:29:03] [main/INFO]: [STDERR]: 	at net.minecraft.class_638.method_18646(class_638.java:252)
[21:29:03] [main/INFO]: [STDERR]: 	at net.minecraft.class_1937.method_18472(class_1937.java:561)
[21:29:03] [main/INFO]: [STDERR]: 	at net.minecraft.class_638.method_18116(class_638.java:210)
[21:29:03] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1574(class_310.java:1531)
[21:29:03] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:996)
[21:29:03] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:656)
[21:29:03] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:215)
[21:29:03] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:29:03] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:29:03] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:29:03] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:29:03] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
[21:29:03] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
[21:29:03] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
[21:29:03] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:29:03] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:29:03] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:29:03] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:29:03] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[21:29:03] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[21:29:03] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[21:29:03] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by qouteall** [comment]
Close because outdated.
