### ISSUE TITLE
Requiem 1.1.0 and IP 0.2 crash upon entering world

### ISSUE THREAD

**Issue by zeflap** [qouteall/ImmersivePortalsMod#46]
java.lang.NullPointerException: null
	at Not Enough Crashes deobfuscated stack trace.(1.15+build.2) ~[?:?]
	at com.qouteall.immersive_portals.SatinCompatibility.isSatinShaderEnabled(SatinCompatibility.java:40) ~[immersive-portals-1.15.1-2.jar:?]
	at com.qouteall.immersive_portals.ModMainClient.switchToCorrectRenderer(ModMainClient.java:64) ~[immersive-portals-1.15.1-2.jar:?]
	at net.minecraft.client.render.GameRenderer.handler$bde000$onBeforeRenderingCenter(GameRenderer:2940) ~[?:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:543) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:947) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:7042) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:202) [intermediary-minecraft-1.15.1-pre1-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193) [fabric-loader-0.7.2+build.174.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) [fabric-loader-0.7.2+build.174.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.7.2+build.174.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

**Comment by qouteall** [comment]
fixed in 1.15-3 version
