### ISSUE TITLE
Crash on World entry

### ISSUE THREAD

**Issue by archonsd** [qouteall/ImmersivePortalsMod#47]
Loading world causes stack trace that refers to Immersive Portals.  I'm not running Optifine.

```
Stack Trace:
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.qouteall.immersive_portals.SatinCompatibility.isSatinShaderEnabled(SatinCompatibility.java:40)
	at com.qouteall.immersive_portals.ModMainClient.switchToCorrectRenderer(ModMainClient.java:64)
	at net.minecraft.class_757.handler$zhe000$onBeforeRenderingCenter(class_757.java:1440)
	at net.minecraft.class_757.method_3192(class_757.java:543)
	at net.minecraft.class_310.method_1523(class_310.java:947)
	at net.minecraft.class_310.method_1514(class_310.java:585)
	at net.minecraft.client.main.Main.main(Main.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
```

Full Log:  https://pastebin.com/17Fyhfg6

**Comment by archonsd** [comment]
New world, never launched before.

**Comment by DatrixTHLK** [comment]
Having this similar issue as well:

Minecraft 1.15.1
Fabric: 0.7.2.build.175
Immersive Portals: 1.15.1-2

**Comment by qouteall** [comment]
should be fixed in 1.15-3 version

**Comment by archonsd** [comment]
Confirmed, crash is resolved.

FWIW, I don't know if it was true prior to the fix (my first attempt to use this mod), but without a portal I get 60 fps (4.2GHz Intel 7700k with 32GB RAM and a GeForce GTX 1080), but once I create a portal, that drops to about 19 fps once the world on the other side is visible.  It doesn't seem to improve over time.

**Comment by qouteall** [comment]
Viewing a portal usually decrease fps from 10% to 40%. That's abnormal.
Does this happen without other mods? What's your render distance?

**Comment by archonsd** [comment]
Render Distance was 16.  I dropped it to 8 and it's improved quite a bit.  I have a lot of other mods, some are worldgen-related, so I'm presuming to display the other side for the first time, there's a lot of worldgen happening once the portal is displayed.

Modlist:

```
12/23/2019  08:33 PM         2,053,500 Adorn-1.6.3+1.15.1.jar
12/23/2019  08:07 PM            76,104 bettersleeping-0.3.0.jar
12/22/2019  11:36 PM            86,502 chickenfeathers-1.2.0.jar
12/22/2019  11:46 PM            65,817 climaticworldtype-1.1.4.jar
12/22/2019  11:50 PM            22,787 Couplings-1.3.1.jar
12/23/2019  08:35 PM            72,435 demeter-1.15.1-1.1.2.jar
12/21/2019  03:33 PM           385,260 expandedstorage-4.9.35+1.15.1.jar
12/23/2019  12:00 AM           275,932 extra-pressure-plates-1.1.3.jar
12/22/2019  11:50 PM           155,180 extradoors-1.3.0-1.15.jar
12/21/2019  03:39 PM           501,460 fabric-api-0.4.25+build.282-1.15.jar
12/22/2019  11:33 PM            30,103 fabric-diagonal-panes-0.1.5.jar
12/22/2019  11:48 PM           207,253 fabric-furnaces_1.15pre4-1.2.0.jar
12/21/2019  03:56 PM         5,248,933 fabric-language-kotlin-1.3.61+build.1.jar
12/21/2019  03:27 PM           811,020 fabricmod_VoxelMap-1.9.13_for_1.15.1.jar
12/22/2019  11:49 PM            57,720 glassdoor-1.4.3.jar
12/21/2019  03:34 PM           237,762 Hwyla-fabric-1.15-pre4-1.9.19-70.jar
12/24/2019  08:21 AM           345,524 immersive-portals-1.15-3.jar
12/22/2019  11:34 PM           640,357 ironbarrels-2.1.0.jar
12/22/2019  11:37 PM           199,382 Just_Another_Redstone_Gate_Mod-1.1.1.jar
12/22/2019  11:40 PM        40,215,720 Mambience-1.0.0.jar
12/23/2019  08:08 PM           661,571 Materialisation-2.1.0.jar
12/22/2019  11:39 PM           116,938 Mo-Glass-v1.1-MC1.15.jar
12/23/2019  12:01 AM           173,738 moreberries-1.2.3.jar
12/21/2019  03:30 PM           849,839 nice-to-have-1.3.0-beta.2.jar
12/22/2019  11:36 PM         6,784,712 PresenceFootsteps-r21+1.15.jar
12/21/2019  03:17 PM           502,467 RebornCore-1.15-4.0.28+build.48.jar
12/21/2019  03:26 PM           568,750 requiem-1.1.0.jar
12/23/2019  11:10 PM         1,060,515 RoughlyEnoughItems-3.2.29.jar
12/23/2019  07:51 PM         1,860,972 spatialcrafting-1.4.1+1.15.1-modpack.jar
12/21/2019  03:17 PM         3,180,061 TechReborn-1.15-3.1.0+build.59.jar
12/22/2019  11:47 PM         1,088,842 terrestria-1.1.1+build.18.jar
12/22/2019  11:16 PM           286,204 traverse-2.1.4+build.10.jar
12/22/2019  11:52 PM            26,257 yet-another-gravestone-mod-1.2.1.jar
```

**Comment by archonsd** [comment]
The smoothness with which you can traverse the portal is stunning, though.
