### ISSUE TITLE
Players unable to log in- Payload may not be larger than 1048576 bytes

### ISSUE THREAD

**Issue by ProsperCraft** [qouteall/ImmersivePortalsMod#474]
Players are unable to log in when this starts, and the error message is below.  I noticed that it seems to be saving the same world multiple times each save, where normally it doesn't do that.

Modpack-[The Adventures of Halk for 1.16 ](https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk) Version 0.14

immersive-portals-0.41-mc1.16.3-fabric

java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
        at net.minecraft.class_2658.<init>(class_2658.java:43) ~[intermediary-server.jar:?]
        at com.qouteall.hiding_in_the_bushes.MyNetwork.createRedirectedMessage(MyNetwork.java:94)

Stacktrace in console-
https://gist.github.com/ProsperCraft/d473deb26040ae34915ffd33ba8e34e8

Full log-
https://gist.github.com/ProsperCraft/517df9ded73776cea7f307467e7a648b

**Comment by qouteall** [comment]
This looks weird. The player spawn packets should not be force redirected. I changed it a little bit and need you to test it using this preview version https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.47-1.16

**Comment by ProsperCraft** [comment]
Requires 1.16.4..... let me work on updating the pack to 1.16.4

I will need a version that matches the one on curse so players can log in, it only happens randomly after players have been playing for a while.

**Comment by SelfMadeSystem** [comment]
I get this too but I'm on 1.16.5. My mods are:
bitsandchisels-2.1.4.jar      fabric-api-0.32.0+1.16.jar                  lithium-fabric-mc1.16.5-0.6.4.jar  worldedit-mod-7.2.4.jar
chiseldecor-1.16.5-1.1.3.jar  immersive-portals-0.80-mc1.16.5-fabric.jar  Pehkui-1.9.0+21w10a.jar
It happened to me multiple times.

**Comment by qouteall** [comment]
@True-cc post the log and crash report

**Comment by SelfMadeSystem** [comment]
<details>
  <summary>Big Log</summary>

```
[03:46:00] [main/INFO]: Loading for game Minecraft 1.16.5
[03:46:01] [main/INFO]: [FabricLoader] Loading 61 mods: fabric-renderer-api-v1@0.4.1+ca58154a7d, fabric-keybindings-v0@0.2.1+ca58154a7d, fabricloader@0.11.3, stacc@1.0.1, fabric-structure-api-v1@1.1.4+ca58154a7d, xlpackets@1.1, fabric-containers-v0@0.1.11+9354966b7d, lithium@0.6.4, fabric-dimensions-v1@2.0.6+9354966b7d, fabric-object-builder-api-v1@1.9.4+9354966b7d, pehkui@1.9.0+21w10a, java@8, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.1+9354966b7d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-renderer-registries-v1@2.2.1+ca58154a7d, immersive_portals@0.80, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.32.0+1.16, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-api-lookup-api-v1@1.0.0+dc716ea17d, imm_ptl_core@0.80, chiseldecor@1.1.3, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, minecraft@1.16.5, fabric-screen-handler-api-v1@1.1.5+9354966b7d, bitsandchisels@2.1.4, modmenu@1.14.6+build.31, cloth-basic-math@0.5.1, fabric-command-api-v1@1.1.0+f9b3753b7d, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, oro_config@1.2.0, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.4+9354966b7d, fabric-rendering-v1@1.5.1+ca58154a7d, cloth-config2@4.8.2, fabric-resource-loader-v0@0.4.2+ca58154a7d, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, worldedit@7.2.4+5723-e3bfc64, fabric-biome-api-v1@3.1.1+ca58154a7d, advanced_runtime_resource_pack@0.3.7, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.3+ca58154a7d, fabric-models-v0@0.2.1+ca58154a7d, fabric-object-builders-v0@0.7.2+ca58154a7d
[03:46:01] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/sms/DunkanCreative/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[03:46:01] [main/INFO]: Loaded configuration file for Lithium: 80 options available, 1 override(s) found
[03:46:02] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [immersive_portals]) disables it and children
[03:46:02] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
[03:46:02] [main/WARN]: Error loading class: net/minecraft/class_634 (java.lang.ClassNotFoundException: net/minecraft/class_634)
[03:46:02] [main/WARN]: @Mixin target net.minecraft.class_634 was not found imm_ptl_fabric.mixins.json:common.MixinDebugClientPlayNetworkHandler
[03:46:02] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in imm_ptl.mixins.json:common.entity_sync.MixinEntityTracker and should be specified in value
[03:46:02] [main/INFO]: I used the json to destroy the json
[03:46:15] [main/INFO]: Immersive Portals Mod Initializing
[03:46:15] [main/INFO]: Reach entity attributes mod is not present
[03:46:15] [main/INFO]: Pehkui is present
[03:46:15] [main/INFO]: Found 1 blockpack(s): [classic].
[03:46:17] [main/INFO]: WorldEdit for Fabric (version 7.2.4+5723-e3bfc64) is loaded
[03:46:17] [main/INFO]: initializing dedicated server
[03:46:19] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[03:46:24] [main/WARN]: Ambiguity between arguments [scale, delay, get, scale_type] and [scale, delay, get, entity] with inputs: [base]
[03:46:24] [main/WARN]: Ambiguity between arguments [scale, get, scale_type] and [scale, get, entity] with inputs: [base]
[03:46:24] [main/WARN]: Ambiguity between arguments [scale, reset, scale_type] and [scale, reset, targets] with inputs: [base]
[03:46:24] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[03:46:24] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[03:46:24] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[03:46:24] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[03:46:24] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[03:46:24] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Immersive Portals, BitsAndChisels, Fabric Tool Attribute API (v1))
[03:46:24] [main/INFO]: ARRP register
[03:46:27] [Worker-Main-11/INFO]: Loaded 7 recipes
[03:46:29] [Worker-Main-11/INFO]: Loaded 927 advancements
[03:46:30] [main/INFO]: Applied 136 biome modifications to 68 of 79 new biomes in 76.52 ms
[03:46:31] [main/INFO]: IP Config Applied
[03:46:31] [Server thread/INFO]: Starting minecraft server version 1.16.5
[03:46:31] [Server thread/INFO]: Loading properties
[03:46:31] [Server thread/INFO]: Default game type: SURVIVAL
[03:46:31] [Server thread/INFO]: Generating keypair
[03:46:31] [Server thread/INFO]: Starting Minecraft server on *:42069
[03:46:32] [Server thread/INFO]: Using epoll channel type
[03:46:32] [Server thread/INFO]: Preparing level "world"
[03:46:33] [Server thread/INFO]: Successfully read IP's dimension id record
[03:46:33] [Server thread/INFO]: Start Completing Dimension Id Record
[03:46:33] [Server thread/INFO]: Before:
minecraft:overworld -> 0
immersive_portals:alternate1 -> 2
immersive_portals:alternate2 -> 3
minecraft:the_nether -> -1
immersive_portals:alternate3 -> 4
immersive_portals:alternate4 -> 5
minecraft:the_end -> 1
immersive_portals:alternate5 -> 6
[03:46:33] [Server thread/INFO]: Server Loaded Dimensions:
immersive_portals:alternate1
immersive_portals:alternate2
immersive_portals:alternate3
immersive_portals:alternate4
immersive_portals:alternate5
minecraft:overworld
minecraft:the_end
minecraft:the_nether

[03:46:33] [Server thread/INFO]: After:
minecraft:overworld -> 0
immersive_portals:alternate1 -> 2
immersive_portals:alternate2 -> 3
minecraft:the_nether -> -1
immersive_portals:alternate3 -> 4
immersive_portals:alternate4 -> 5
minecraft:the_end -> 1
immersive_portals:alternate5 -> 6
[03:46:33] [Server thread/INFO]: Dimension Id Info Saved to File
[03:46:33] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[03:46:37] [Server thread/INFO]: Preparing spawn area: 0%
[03:46:37] [Server thread/INFO]: Preparing spawn area: 0%
[03:46:37] [Server thread/INFO]: Preparing spawn area: 0%
[03:46:37] [Server thread/INFO]: Preparing spawn area: 0%
[03:46:37] [Server thread/INFO]: Preparing spawn area: 0%
[03:46:37] [Server thread/INFO]: Preparing spawn area: 0%
[03:46:37] [Server thread/INFO]: Preparing spawn area: 0%
[03:46:37] [Server thread/INFO]: Preparing spawn area: 0%
[03:46:37] [Server thread/INFO]: Preparing spawn area: 0%
[03:46:37] [Server thread/INFO]: Preparing spawn area: 0%
[03:46:38] [Server thread/INFO]: Preparing spawn area: 66%
[03:46:39] [Server thread/INFO]: Time elapsed: 5861 ms
[03:46:39] [Server thread/INFO]: Loading custom portal gen
[03:46:39] [Server thread/INFO]: Done (6.627s)! For help, type "help"
[03:46:39] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.fabric.FabricPlatform with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@3a027c11]
[03:46:41] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.fabric.FabricPlatform
[03:46:42] [Server thread/WARN]: Ambiguity between arguments [scale, delay, get, scale_type] and [scale, delay, get, entity] with inputs: [base]
[03:46:42] [Server thread/WARN]: Ambiguity between arguments [scale, get, scale_type] and [scale, get, entity] with inputs: [base]
[03:46:42] [Server thread/WARN]: Ambiguity between arguments [scale, reset, scale_type] and [scale, reset, targets] with inputs: [base]
[03:46:42] [Server thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[03:46:42] [Server thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[03:46:42] [Server thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[03:46:42] [Server thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[03:46:42] [Server thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[03:46:42] [Server thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Immersive Portals, BitsAndChisels, Fabric Tool Attribute API (v1))
[03:46:42] [Server thread/INFO]: ARRP register
[03:46:44] [Server thread/INFO]: Loaded 7 recipes
[03:46:45] [Server thread/INFO]: Loaded 927 advancements
[03:46:46] [Server thread/INFO]: Loading custom portal gen
[03:46:46] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 4251ms or 85 ticks behind
[03:46:58] [User Authenticator #1/INFO]: UUID of player Sms_Gamer_3808 is d8ab1ac6-51a5-482c-a7ca-2097662ccb31
[03:46:59] [Server thread/INFO]: Sms_Gamer_3808[/MY-IP] logged in with entity id 52 at (106.5, 70.0, -258.5)
[03:46:59] [Server thread/INFO]: Sms_Gamer_3808 joined the game
[03:46:59] [Server thread/WARN]: Failed to handle packet for /MY-IP
java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
	at net.minecraft.class_2658.<init>(class_2658.java:43) ~[intermediary-server.jar:?]
	at com.qouteall.hiding_in_the_bushes.MyNetwork.createRedirectedMessage(MyNetwork.java:115) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at com.qouteall.immersive_portals.chunk_loading.ChunkDataSyncManager.sendChunkDataPacketNow(ChunkDataSyncManager.java:62) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at com.qouteall.immersive_portals.chunk_loading.ChunkDataSyncManager.onBeginWatch(ChunkDataSyncManager.java:45) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at com.qouteall.immersive_portals.my_util.SignalBiArged.lambda$connectWithWeakRef$1(SignalBiArged.java:35) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at com.qouteall.immersive_portals.my_util.SignalBiArged.lambda$emit$0(SignalBiArged.java:18) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_275]
	at com.qouteall.immersive_portals.my_util.SignalBiArged.emit(SignalBiArged.java:18) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at com.qouteall.immersive_portals.chunk_loading.NewChunkTrackingGraph.lambda$null$9(NewChunkTrackingGraph.java:181) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at com.qouteall.immersive_portals.chunk_loading.NewChunkTrackingGraph.updateWatchingStatus(NewChunkTrackingGraph.java:67) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at com.qouteall.immersive_portals.chunk_loading.NewChunkTrackingGraph.lambda$updatePlayerForChunkLoader$10(NewChunkTrackingGraph.java:175) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at com.qouteall.immersive_portals.chunk_loading.ChunkLoader.foreachChunkPos(ChunkLoader.java:45) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at com.qouteall.immersive_portals.chunk_loading.NewChunkTrackingGraph.updatePlayerForChunkLoader(NewChunkTrackingGraph.java:169) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at com.qouteall.immersive_portals.chunk_loading.NewChunkTrackingGraph.lambda$updateForPlayer$5(NewChunkTrackingGraph.java:154) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_275]
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175) ~[?:1.8.0_275]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419) ~[?:1.8.0_275]
	at com.google.common.collect.CollectSpliterators$1FlatMapSpliterator.lambda$forEachRemaining$1(CollectSpliterators.java:246) ~[fabric-server-launch.jar:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_275]
	at com.google.common.collect.CollectSpliterators$1FlatMapSpliterator.forEachRemaining(CollectSpliterators.java:246) ~[fabric-server-launch.jar:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_275]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_275]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_275]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_275]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_275]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_275]
	at com.qouteall.immersive_portals.chunk_loading.NewChunkTrackingGraph.updateForPlayer(NewChunkTrackingGraph.java:154) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at net.minecraft.class_3324.handler$zna001$onOnPlayerConnect(class_3324.java:3003) ~[intermediary-server.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:273) ~[intermediary-server.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:113) ~[intermediary-server.jar:?]
	at net.minecraft.class_3248.redirect$zll000$handlePlayerJoin(class_3248.java:562) ~[intermediary-server.jar:?]
	at net.minecraft.class_3248.method_18785(class_3248.java:65) ~[intermediary-server.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:228) ~[intermediary-server.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:173) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
[03:47:00] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
	at net.minecraft.class_2658.<init>(class_2658.java:43) ~[intermediary-server.jar:?]
	at com.qouteall.hiding_in_the_bushes.MyNetwork.createRedirectedMessage(MyNetwork.java:115) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at com.qouteall.immersive_portals.chunk_loading.ChunkDataSyncManager.sendChunkDataPacketNow(ChunkDataSyncManager.java:62) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at com.qouteall.immersive_portals.chunk_loading.ChunkDataSyncManager.onBeginWatch(ChunkDataSyncManager.java:45) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at com.qouteall.immersive_portals.my_util.SignalBiArged.lambda$connectWithWeakRef$1(SignalBiArged.java:35) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at com.qouteall.immersive_portals.my_util.SignalBiArged.lambda$emit$0(SignalBiArged.java:18) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_275]
	at com.qouteall.immersive_portals.my_util.SignalBiArged.emit(SignalBiArged.java:18) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at com.qouteall.immersive_portals.chunk_loading.NewChunkTrackingGraph.lambda$null$9(NewChunkTrackingGraph.java:181) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at com.qouteall.immersive_portals.chunk_loading.NewChunkTrackingGraph.updateWatchingStatus(NewChunkTrackingGraph.java:67) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at com.qouteall.immersive_portals.chunk_loading.NewChunkTrackingGraph.lambda$updatePlayerForChunkLoader$10(NewChunkTrackingGraph.java:175) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at com.qouteall.immersive_portals.chunk_loading.ChunkLoader.foreachChunkPos(ChunkLoader.java:45) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at com.qouteall.immersive_portals.chunk_loading.NewChunkTrackingGraph.updatePlayerForChunkLoader(NewChunkTrackingGraph.java:169) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at com.qouteall.immersive_portals.chunk_loading.NewChunkTrackingGraph.lambda$updateForPlayer$5(NewChunkTrackingGraph.java:154) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_275]
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175) ~[?:1.8.0_275]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419) ~[?:1.8.0_275]
	at com.google.common.collect.CollectSpliterators$1FlatMapSpliterator.lambda$forEachRemaining$1(CollectSpliterators.java:246) ~[fabric-server-launch.jar:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_275]
	at com.google.common.collect.CollectSpliterators$1FlatMapSpliterator.forEachRemaining(CollectSpliterators.java:246) ~[fabric-server-launch.jar:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_275]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_275]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_275]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_275]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_275]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_275]
	at com.qouteall.immersive_portals.chunk_loading.NewChunkTrackingGraph.updateForPlayer(NewChunkTrackingGraph.java:154) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at com.qouteall.immersive_portals.chunk_loading.NewChunkTrackingGraph.lambda$tick$23(NewChunkTrackingGraph.java:292) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_275]
	at com.qouteall.immersive_portals.chunk_loading.NewChunkTrackingGraph.tick(NewChunkTrackingGraph.java:290) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at com.qouteall.immersive_portals.my_util.Signal.lambda$emit$0(Signal.java:18) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_275]
	at com.qouteall.immersive_portals.my_util.Signal.emit(Signal.java:18) ~[11f71b01-4873-444e-9b7d-dec1e3555c6c.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zmp000$onServerTick(MinecraftServer.java:3753) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:894) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
[03:47:00] [Server thread/ERROR]: This crash report has been saved to: /home/sms/DunkanCreative/./crash-reports/crash-2021-03-26_03.47.00-server.txt
[03:47:00] [Server thread/INFO]: Unregistering com.sk89q.worldedit.fabric.FabricPlatform from WorldEdit
[03:47:00] [Server thread/INFO]: Stopping server
[03:47:00] [Server thread/INFO]: Saving players
[03:47:00] [Server thread/INFO]: Saving worlds
[03:47:00] [Server thread/INFO]: Saving chunks for level 'ServerWorld minecraft:overworld world'/minecraft:overworld
[03:47:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[03:47:02] [Server thread/INFO]: Saving chunks for level 'ServerWorld minecraft:the_nether world'/minecraft:the_nether
[03:47:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[03:47:02] [Server thread/INFO]: Saving chunks for level 'ServerWorld minecraft:the_end world'/minecraft:the_end
[03:47:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[03:47:02] [Server thread/INFO]: Saving chunks for level 'ServerWorld immersive_portals:alternate1 world'/immersive_portals:alternate1
[03:47:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate1): All chunks are saved
[03:47:02] [Server thread/INFO]: Saving chunks for level 'ServerWorld immersive_portals:alternate2 world'/immersive_portals:alternate2
[03:47:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate2): All chunks are saved
[03:47:02] [Server thread/INFO]: Saving chunks for level 'ServerWorld immersive_portals:alternate3 world'/immersive_portals:alternate3
[03:47:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate3): All chunks are saved
[03:47:02] [Server thread/INFO]: Saving chunks for level 'ServerWorld immersive_portals:alternate4 world'/immersive_portals:alternate4
[03:47:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate4): All chunks are saved
[03:47:02] [Server thread/INFO]: Saving chunks for level 'ServerWorld immersive_portals:alternate5 world'/immersive_portals:alternate5
[03:47:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate5): All chunks are saved
[03:47:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[03:47:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[03:47:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[03:47:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate1): All chunks are saved
[03:47:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate2): All chunks are saved
[03:47:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate3): All chunks are saved
[03:47:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate4): All chunks are saved
[03:47:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate5): All chunks are saved
```
</details>
