### ISSUE TITLE
Teleportation inconsistencies

### ISSUE THREAD

**Issue by SpaceBrave** [qouteall/ImmersivePortalsMod#54]
I've set up two overworld portals by creating nether portals, marking them unbreakable and leaving only the two I need, then changing their location. It all seems to work until I go through them more than two, three times it doesn't let me through. I get this error in the server console:

[17:04:54] [Server thread/ERROR]: [Portal] Player cannot teleport through portal SpaceHQ minecraft:overworld (1002.9524334924786, 64.24918707874468, -61.95168866408649) b5843675-a500-4fb6-b58e-ba24ed932413
[17:05:00] [Server thread/WARN]: SpaceHQ moved too quickly! -2.9939387799696533,11.0,96.79905694428004
[17:05:00] [Server thread/INFO]: [Portal] request teleport SpaceHQ in minecraft:overworld to 1003.113041221492 63.0 -62.57619643143297
[17:05:00] [Server thread/WARN]: SpaceHQ moved too quickly! 3.0,-11.0,-97.0
[17:05:00] [Server thread/INFO]: [Portal] request teleport SpaceHQ in minecraft:overworld to 1003.113041221492 63.0 -62.57619643143297
[17:05:08] [Server thread/WARN]: SpaceHQ moved too quickly! -3.025981621943174,10.988802559555054,96.51556397015523
[17:05:08] [Server thread/INFO]: [Portal] request teleport SpaceHQ in minecraft:overworld to 1002.4274028561213 64.02342449698943 -62.693219638157515
[17:05:08] [Server thread/WARN]: SpaceHQ moved too quickly! 3.0,-11.0,-97.0
[17:05:08] [Server thread/INFO]: [Portal] request teleport SpaceHQ in minecraft:overworld to 1002.4274028561213 64.02342449698943 -62.693219638157515
[17:05:08] [Server thread/WARN]: SpaceHQ moved too quickly! 3.0,-11.0,-97.0
[17:05:08] [Server thread/INFO]: [Portal] request teleport SpaceHQ in minecraft:overworld to 1002.4274028561213 64.02342449698943 -62.693219638157515
[17:05:10] [Server thread/WARN]: SpaceHQ moved too quickly! -2.8709906858794056,11.0,96.29926938206228
[17:05:10] [Server thread/INFO]: [Portal] request teleport SpaceHQ in minecraft:overworld to 1002.6844512630094 64.02342449698943 -62.717472166217185
[17:05:10] [Server thread/WARN]: SpaceHQ moved too quickly! 3.0,-11.0,-97.0
[17:05:10] [Server thread/INFO]: [Portal] request teleport SpaceHQ in minecraft:overworld to 1002.6844512630094 64.02342449698943 -62.717472166217185
[17:05:10] [Server thread/WARN]: SpaceHQ moved too quickly! 3.0,-11.0,-97.0
[17:05:10] [Server thread/INFO]: [Portal] request teleport SpaceHQ in minecraft:overworld to 1002.6844512630094 64.02342449698943 -62.717472166217185
[17:05:11] [Server thread/WARN]: SpaceHQ moved too quickly! -2.9919581221574845,11.0,96.65316579825904
[17:05:11] [Server thread/INFO]: [Portal] request teleport SpaceHQ in minecraft:overworld to 1003.3522797605538 64.02342449698943 -62.78089502517186
[17:05:11] [Server thread/WARN]: SpaceHQ moved too quickly! 3.0,-11.0,-97.0
[17:05:11] [Server thread/INFO]: [Portal] request teleport SpaceHQ in minecraft:overworld to 1003.3522797605538 64.02342449698943 -62.78089502517186
[17:05:11] [Server thread/WARN]: SpaceHQ moved too quickly! 3.0,-11.0,-97.0
[17:05:11] [Server thread/INFO]: [Portal] request teleport SpaceHQ in minecraft:overworld to 1003.3522797605538 64.02342449698943 -62.78089502517186
[17:05:13] [Server thread/WARN]: SpaceHQ moved too quickly! -3.0,11.0,96.70596432905052
[17:05:13] [Server thread/INFO]: [Portal] request teleport SpaceHQ in minecraft:overworld to 1003.3561976234314 64.02342449698943 -62.780208677659935
[17:05:13] [Server thread/WARN]: SpaceHQ moved too quickly! 3.0,-11.0,-97.0
[17:05:13] [Server thread/INFO]: [Portal] request teleport SpaceHQ in minecraft:overworld to 1003.3561976234314 64.02342449698943 -62.780208677659935
[17:05:13] [Server thread/WARN]: SpaceHQ moved too quickly! 3.0,-11.0,-97.0
[17:05:13] [Server thread/INFO]: [Portal] request teleport SpaceHQ in minecraft:overworld to 1003.3561976234314 64.02342449698943 -62.780208677659935
[17:05:13] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
        at net.minecraft.class_3244.method_12050(class_3244.java:389) ~[intermediary-server.jar:?]
        at net.minecraft.class_2793.method_12085(class_2793.java:30) ~[intermediary-server.jar:?]
        at net.minecraft.class_2793.method_11054(class_2793.java:8) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:724) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:718) [intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:703) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]

**Comment by qouteall** [comment]
After relogging do you still see the portals? Does this happen when you slowly cross them one by one?

**Comment by qouteall** [comment]
1.15 or 1.14?

**Comment by SpaceBrave** [comment]
1.15.1 After relogging I can still see the portals, same after restarting the server. The problem isn't a visual one. I've also noticed that speed doesn't matter, It can happen at any speed.

**Comment by SpaceBrave** [comment]
Here're some warnings I get when starting the server

[09:51:01] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/D:/Server_Fabric_1.15.1/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[09:51:28] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[09:51:28] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[09:51:28] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[09:51:28] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[09:51:28] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[09:51:31] [main/INFO]: [Portal] initializing common
[09:51:32] [main/INFO]: [Portal] initializing dedicated server

**Comment by qouteall** [comment]
Outdated
