### ISSUE TITLE
Incompatible with mod Superaxes

### ISSUE THREAD

**Issue by linzexin022** [qouteall/ImmersivePortalsMod#540]
Hi there, I found your mod incompatible with Superaxes. Immersive Portal mod will stop Superaxes to chop down the whole tree, and the console says:
`[20:31:48] [Thread-178/INFO]: [STDERR]: java.lang.IllegalArgumentException: The validated expression is false
[20:31:48] [Thread-178/INFO]: [STDERR]: 	at org.apache.commons.lang3.Validate.isTrue(Validate.java:183)
[20:31:48] [Thread-178/INFO]: [STDERR]: 	at com.qouteall.immersive_portals.network.CommonNetwork.withForceRedirect(CommonNetwork.java:24)
[20:31:48] [Thread-178/INFO]: [STDERR]: 	at net.minecraft.class_3898$class_3208.updateEntityTrackingStatus(class_3898.java:1956)
[20:31:48] [Thread-178/INFO]: [STDERR]: 	at net.minecraft.class_3898$class_3208.method_18729(class_3898.java:1912)
[20:31:48] [Thread-178/INFO]: [STDERR]: 	at net.minecraft.class_3898.method_18701(class_3898.java:1020)
[20:31:48] [Thread-178/INFO]: [STDERR]: 	at net.minecraft.class_3215.method_18755(class_3215.java:477)
[20:31:48] [Thread-178/INFO]: [STDERR]: 	at net.minecraft.class_3218.method_18778(class_3218.java:933)
[20:31:48] [Thread-178/INFO]: [STDERR]: 	at net.minecraft.class_3218.method_14175(class_3218.java:835)
[20:31:48] [Thread-178/INFO]: [STDERR]: 	at net.minecraft.class_3218.method_8649(class_3218.java:765)
[20:31:48] [Thread-178/INFO]: [STDERR]: 	at net.minecraft.class_1264.method_5449(class_1264.java:52)
[20:31:48] [Thread-178/INFO]: [STDERR]: 	at com.github.levoment.superaxes.Items.SuperAxeItem.lambda$mineBlockWithLootContext$2(SuperAxeItem.java:96)
[20:31:48] [Thread-178/INFO]: [STDERR]: 	at java.util.ArrayList.forEach(ArrayList.java:1259)
[20:31:48] [Thread-178/INFO]: [STDERR]: 	at com.github.levoment.superaxes.Items.SuperAxeItem.mineBlockWithLootContext(SuperAxeItem.java:94)
[20:31:48] [Thread-178/INFO]: [STDERR]: 	at com.github.levoment.superaxes.TreeChopper.breakLogs(TreeChopper.java:286)
[20:31:48] [Thread-178/INFO]: [STDERR]: 	at com.github.levoment.superaxes.TreeChopper.parallelTraverseTreeAndBreakBlocks(TreeChopper.java:221)
[20:31:48] [Thread-178/INFO]: [STDERR]: 	at com.github.levoment.superaxes.TreeChopper.cutTree(TreeChopper.java:66)
[20:31:48] [Thread-178/INFO]: [STDERR]: 	at com.github.levoment.superaxes.Items.SuperAxeItem.lambda$canMine$0(SuperAxeItem.java:59)
[20:31:48] [Thread-178/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:748)`

I have reported [this issue](https://github.com/Levoment/SuperAxes/issues/7) to the author of Superaxes, but I found he has deleted this project on CurseForge and I'm afraid he is no longer maintain this project, so I came here to ask you for help...

**Comment by qouteall** [comment]
Seems that Superaxes tries to invoke spawning an item entity in a non-server thread.
Even without Immersive Portals this operation of Superaxes may cause random concurrency issues. Immersive Portals just did the thread check.
