### ISSUE TITLE
Issue with hyper lighting core

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#547]
```
[21Jan2021 02:44:07.786] [Thread-87/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[21Jan2021 02:44:07.786] [Thread-87/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:     at com.qouteall.immersive_portals.render.FrustumCuller.canDetermineInvisible(FrustumCuller.java:31)
[21Jan2021 02:44:07.786] [Thread-87/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:     at net.minecraft.client.renderer.culling.ClippingHelper.handler$bcn000$onIntersectionTest(SourceFile:546)
[21Jan2021 02:44:07.786] [Thread-87/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:     at net.minecraft.client.renderer.culling.ClippingHelper.func_228953_a_(SourceFile)
[21Jan2021 02:44:07.786] [Thread-87/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:     at net.minecraft.client.renderer.culling.ClippingHelper.func_228957_a_(SourceFile:47)
[21Jan2021 02:44:07.786] [Thread-87/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:     at net.hypherionmc.hypcore.event.GatherLightsEvent.add(GatherLightsEvent.java:86)
[21Jan2021 02:44:07.786] [Thread-87/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:     at net.hypherionmc.hypcore.lighting.ColoredLightRegistration.lambda$null$2(ColoredLightRegistration.java:45)
[21Jan2021 02:44:07.786] [Thread-87/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:     at net.hypherionmc.hypcore.EventManager.lambda$startThread$0(EventManager.java:69)
[21Jan2021 02:44:07.786] [Thread-87/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:     at java.lang.Thread.run(Thread.java:748)
```

**Comment by Mysticpasta1** [comment]
new crash with hlc on 1.16.5 fabric 
[crash-2021-04-29_14.21.40-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/6401199/crash-2021-04-29_14.21.40-client.txt)

**Comment by qouteall** [comment]
```
java.lang.NullPointerException: at index 1
	at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:236)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:226)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:220)
	at com.google.common.collect.ImmutableList.construct(ImmutableList.java:347)
	at com.google.common.collect.ImmutableList.of(ImmutableList.java:102)
	at com.google.common.collect.FluentIterable.concat(FluentIterable.java:189)
	at com.google.common.collect.Iterables.concat(Iterables.java:428)
	at net.minecraft.class_1297.method_5743(class_1297.java:1986)
	at net.hypherionmc.hypcore.lighting.LightManager.update(LightManager.java:98)
	at net.hypherionmc.hypcore.EventManager.onProfilerChange(EventManager.java:102)
	at net.hypherionmc.hypcore.client.HypCoreClient$$Lambda$2792/1973649083.profilerEvent(Unknown Source)
	at net.minecraft.class_3694.handler$zzf000$swap(class_3694.java:517)
	at net.minecraft.class_3694.method_15405(class_3694.java)
	at net.minecraft.class_761.method_22710(class_761.java:1151)
	at net.minecraft.class_757.method_3188(class_757.java:727)
	at net.minecraft.class_757.redirect$zkp000$redirectRenderingWorld(class_757.java:2552)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
```

**Comment by qouteall** [comment]
Close because outdated.
