### ISSUE TITLE
ImmersivePortals is not compatible with the Reroll mod, crashes game upon startup

### ISSUE THREAD

**Issue by guysimtheprinter** [qouteall/ImmersivePortalsMod#631]
Hi there. I have recently started an Origins server with a large modpack, and I wanted to add IP to the modpack. I went to test out the mod, to see if it worked at least on a singleplayer world, but I can't even open the game. Whenever I press the play button on the launcher, the game loads, then exits with the same crash report: exit code 0 with no report document. Before you ask, yes, I did try to restart the launcher. Same error. I also tried to launch the game with Optifine and OptiFabric removed from the mods folder, and I received the same error. For some reason, when I first did this before restarting the launcher, the following crash report showed up:

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 3/10/21 11:14 AM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'modmenu'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.NoClassDefFoundError: com/terraformersmc/modmenu/api/ModMenuApi
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:163)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
	at net.fabricmc.loader.EntrypointStorage$$Lambda$2260/1587390806.get(Unknown Source)
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
	at io.github.prospector.modmenu.ModMenu.lambda$onInitializeClient$0(ModMenu.java:75)
	at io.github.prospector.modmenu.ModMenu$$Lambda$3814/1703877211.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at io.github.prospector.modmenu.ModMenu.onInitializeClient(ModMenu.java:74)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$3580/543431252.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: java.lang.ClassNotFoundException: com.terraformersmc.modmenu.api.ModMenuApi
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 30 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 709648184 bytes (676 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		architectury: Architectury 1.5.105
		artifice: Artifice 0.14.6+1.16.5
		autoconfig1u: Auto Config v1 Updated 3.3.1
		betterend: Better End 0.9.1-pre
		betternether: Better Nether 5.0.7
		bettersleeping: Better Sleeping 0.4.0
		blockshifter: Blockshifter 1.3.2+fabric-1.16.4
		cardinal-components-base: Cardinal Components API (base) 2.7.1
		cardinal-components-entity: Cardinal Components API (entities) 2.7.1
		carpet: Carpet Mod in Fabric 1.4.28
		celib: Celib - CebbyS Library Mod 0.3.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.14
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.2.1
		colorfulcut: Colorful Cut 1.0.0
		com_github_mouse0w0_fastreflection: FastReflection 1.0.1
		croptopia: Croptopia 1.2.0
		crowdin-translate: CrowdinTranslate 1.2
		crumbs: Crumbs 1.0.6
		decorative: Decorative 4.0.0
		elhuevo: El Huevo 1.16.5-1.0.0
		enderores: Ender Ores 1.0.0
		equip: EquipZ 1.6.2
		extraorigins: Extra Origins 1.16.5-8
		fabric: Fabric API 0.31.0+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.0+f9b3753b7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-language-scala: Fabric Language Scala 1.0.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.2
		fallflyinglib: FallFlyingLib 1.1.0
		fiber: fiber 0.23.0-2
		flytre_lib: FlytreLib 0.2.8
		geckolib3: Geckolib 3.0.23
		guillotine: Guillotine 1.0.0
		image2map: Image2Map 0.2.0
		imm_ptl_core: Immersive Portals Core 0.80
		immersive_portals: Immersive Portals 0.80
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		libgui: LibGui 3.3.3+1.16.5
		midnight-hats: Midnight Hats 2.0.1
		minecraft: Minecraft 1.16.5
		moborigins: Mob Origins 1.2.1
		modmenu: Mod Menu 1.14.6+build.31
		multi_item_lib: Multi Item Lib 1.1.1
		netherite_plus: Netherite Plus Mod 1.3.17-1.16.5
		noenchantcap: NoEnchantCap 2.0.0
		org_aeonbits_owner_owner: owner 1.0.12
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		origins: Origins 0.5.2
		origins-classes: Origins: Classes 1.1.1
		oro_config: OroArmor Config 1.2.0
		paintingcycle: Painting Cycle 1.0.0
		paradoxslabs: ParadoxSlabs 0.1.0
		patchouli: Patchouli 1.16.4-50-FABRIC
		pehkui: Pehkui 1.8.0+21w08b
		ratsmischief: Rat's Mischief 1.0.2
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		reroll: Reroll 1.2.0-1.16.5
		rocks: This Rocks! 1.3.1
		roughlyenoughitems: Roughly Enough Items 5.10.184
		roughlyenoughitems-api: REI (API) 5.10.184
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.10.184
		roughlyenoughitems-runtime: REI (Runtime) 5.10.184
		sakurarosea: Sakura Rosea 1.6.0-MC1.16.3-fabric
		sandwichable: Sandwichable 1.1.2
		silky_spawners: Silky Spawners 2.1.0+build.2-1.16
		slabref: Refabricated Slabs 0.3.1
		untitledduckmod: Untitled Duck Mod 0.1.1
		vexc: Vein Excavator 1.0.0
		villagerhats: Villager Hats fabric-1.16.4-1.0.1
		walljump: Wall-Jump! 1.3.3+1.16.1
		wandering_collector: Wandering Collector 1.0.0+mc1.16.5
		xykey: XYKey 1.1
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.11.2-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
	
	--------------------------------------------------
What should I do? Let me know if there's any other information I should provide. Thanks,
- guysimtheprinter

**Comment by detective-wraith** [comment]
Well, I know that optifine isn't the problem, but to get this out of the way, are you using optifine g7?

**Comment by guysimtheprinter** [comment]
> Well, I know that optifine isn't the problem, but to get this out of the way, are you using optifine g7?

No, actually. Idk why I didn't think of that before. I am using G6. I will try with G7.

**Comment by detective-wraith** [comment]
Ok, because G6 is incompatable

**Comment by froyo4u** [comment]
I mean you were still crashing without OptiFine so there must be a bigger issue

**Comment by detective-wraith** [comment]
One problem at a time cat

**Comment by froyo4u** [comment]
please stop calling me that...

**Comment by detective-wraith** [comment]
Not the place for this conversation. Icoslation, it's most likely one of your mods being incompatible if switching to G7 doesn't work

**Comment by guysimtheprinter** [comment]
What I am trying to do right now is load ONLY optifine, Fabric API, and IP. Then I'll go through and try to figure out which mod is causing errors. And yes, the game does in fact launch now with Optifine G7.

**Comment by detective-wraith** [comment]
If I knew how to do a thumbs-up emoji, I would put it here

**Comment by froyo4u** [comment]
👍

**Comment by guysimtheprinter** [comment]
You can react with it :0

**Comment by froyo4u** [comment]
you can send it

**Comment by detective-wraith** [comment]
And I would try out dimension based mods first, such as better end, better nether, etc.. You never know if one of them changes something weird about the dimensions on a whim

**Comment by guysimtheprinter** [comment]
Okay, good idea.

**Comment by guysimtheprinter** [comment]
Well so far all of my dimension mods work fine with IP, so I'll be trying vanilla game stuff like walljump and other mods that dont add items.

**Comment by guysimtheprinter** [comment]
And all vanilla fix mods work fine, including Origins. I had a problem with REI that was unrelated to IP, and I will be testing that last.

**Comment by guysimtheprinter** [comment]
Found it. The [Reroll](https://www.curseforge.com/minecraft/mc-mods/reroll) mod (v1.2.0) is incompatible with ImmersivePortals (v0.80). The game works fine without Reroll in my mods folder.

**Comment by qouteall** [comment]
Maybe it's caused by that reroll uses com.terraformersmc:modmenu but IP includes prospector's modmenu. The two modmenus have the same mod id and may conflict
