### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SilverHatTrick** [qouteall/ImmersivePortalsMod#647]
https://pastebin.com/A18uWAnu

**Comment by Razboy20** [comment]
Looking at the crash log, it seems like you are trying to use Sodium with immersive portals. 

Sodium by default does not currently support the usage of immersive portals; However, you can use a modified version of sodium which is compatible with IP, which can be found here: https://github.com/qouteall/ImmersivePortalsMod/issues/url

**Comment by ry0shi** [comment]
```
[16:50:29] [main/INFO]: Loading for game Minecraft 1.16.5
[16:50:30] [ForkJoinPool-1-worker-3/WARN]: Non-Fabric mod JAR at "C:\Users\ry0shi\AppData\Roaming\.randommodpack\mods\OptiFine_1.16.5_HD_U_G6.jar", ignoring
[16:50:30] [main/INFO]: [FabricLoader] Loading 56 mods: fabric-renderer-api-v1@0.4.1+ca58154a7d, fabric-keybindings-v0@0.2.1+ca58154a7d, fabricloader@0.11.1, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.10+ca58154a7d, fabric-object-builder-api-v1@1.9.3+ca58154a7d, fabric-dimensions-v1@2.0.2+ca58154a7d, pehkui@1.7.1+21w03a, java@8, fabric-game-rule-api-v1@1.0.6+ca58154a7d, com_googlecode_efficient-java-matrix-library_ejml@0.25, fabric-api-base@0.2.0+daa38b3d7d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, mm@2.1, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-renderer-registries-v1@2.2.1+ca58154a7d, immersive_portals@0.80, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.30.0+1.16, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, imm_ptl_core@0.84, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, minecraft@1.16.5, fabric-screen-handler-api-v1@1.1.1+ca58154a7d, portalgun@1.1.5, modmenu@1.14.6+build.31, fabric-command-api-v1@1.0.10+ca58154a7d, cloth-basic-math@0.5.1, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.2+ca58154a7d, fabric-rendering-v1@1.5.1+ca58154a7d, cloth-config2@4.8.2, fabric-resource-loader-v0@0.4.2+ca58154a7d, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, optifabric@1.9.2, fabric-biome-api-v1@3.1.1+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.3+ca58154a7d, fabric-models-v0@0.2.1+ca58154a7d, fabric-object-builders-v0@0.7.2+ca58154a7d
[16:50:30] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/ry0shi/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[16:50:31] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
[16:50:31] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in imm_ptl.mixins.json:common.entity_sync.MixinEntityTracker and should be specified in value
[16:50:33] [main/INFO]: [OptiFine] (Reflector) Field not found: World.tileEntitiesToBeRemoved
[16:50:40] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:50:41] [main/INFO]: Setting user: ry0shi1337
[16:50:41] [main/INFO]: Definitely not up to no good
[16:50:41] [main/INFO]: Immersive Portals Mod Initializing
[16:50:42] [main/INFO]: Reach entity attributes mod is not present
[16:50:42] [main/INFO]: Pehkui is present
[16:50:42] [main/INFO]: [PortalGun Mod] Initializing
[16:50:42] [main/WARN]: Error loading class: net/optifine/util/LineBuffer (java.lang.ClassNotFoundException: net/optifine/util/LineBuffer)
[16:50:42] [main/INFO]: [STDERR]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[16:50:42] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
[16:50:42] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
[16:50:42] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
[16:50:42] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[16:50:42] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:50:42] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:50:42] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:50:42] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[16:50:42] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
[16:50:42] [main/INFO]: [STDERR]: 	... 2 more
[16:50:42] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[16:50:42] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[16:50:42] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
[16:50:42] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[16:50:42] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[16:50:42] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
[16:50:42] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
[16:50:42] [main/INFO]: [STDERR]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[16:50:42] [main/INFO]: [STDERR]: 	at net.optifine.CrashReporter.extendCrashReport(CrashReporter.java:126)
[16:50:42] [main/INFO]: [STDERR]: 	at net.optifine.CrashReporter.onCrashReport(CrashReporter.java:38)
[16:50:42] [main/INFO]: [STDERR]: 	at net.minecraft.class_128.method_568(class_128.java:227)
[16:50:42] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1565(class_310.java:785)
[16:50:42] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:186)
[16:50:42] [main/INFO]: [STDERR]: 	... 7 more
[16:50:42] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for imm_ptl_optifine.mixins.json:MixinShaders during activity: [Transform -> Method modifyFragShaderCode(Lnet/optifine/util/LineBuffer;)Ljava/lang/String; -> INVOKEVIRTUAL -> net/optifine/util/LineBuffer::toString()Ljava/lang/String;]
[16:50:42] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:300)
[16:50:42] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264)
[16:50:42] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272)
[16:50:42] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
[16:50:42] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[16:50:42] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[16:50:42] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[16:50:42] [main/INFO]: [STDERR]: 	... 18 more
[16:50:42] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.optifine.util.LineBuffer
[16:50:42] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:768)
[16:50:42] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:754)
[16:50:42] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:720)
[16:50:42] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:294)
[16:50:42] [main/INFO]: [STDERR]: 	... 24 more
[16:50:42] [main/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: net.optifine.util.LineBuffer
[16:50:42] [main/INFO]: [STDERR]: 	... 28 more

```

**Comment by ry0shi** [comment]
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 23.03.21 17:16
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'immersive_portals'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: java.lang.NoSuchMethodError: com.qouteall.immersive_portals.portal.custom_portal_gen.CustomPortalGeneration.<init>(Ljava/util/List;Lnet/minecraft/class_5321;IIZLcom/qouteall/immersive_portals/portal/custom_portal_gen/form/PortalGenForm;Lcom/qouteall/immersive_portals/portal/custom_portal_gen/PortalGenTrigger;Ljava/util/List;)V
	at com.qouteall.imm_ptl_peripheral.portal_generation.IntrinsicPortalGeneration.<clinit>(IntrinsicPortalGeneration.java:24)
	at com.qouteall.imm_ptl_peripheral.PeripheralModMain.init(PeripheralModMain.java:28)
	at com.qouteall.hiding_in_the_bushes.PeripheralModEntry.onInitialize(PeripheralModEntry.java:88)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2292/1876649539.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4814988368 bytes (4591 MB) / 5939134464 bytes (5664 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 4
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.2
		com_googlecode_efficient-java-matrix-library_ejml: ejml 0.25
		fabric: Fabric API 0.30.0+1.16
		fabric-api-base: Fabric API Base 0.2.0+daa38b3d7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.10+ca58154a7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.2+ca58154a7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.2+ca58154a7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.3+ca58154a7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.1+ca58154a7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.1
		imm_ptl_core: Immersive Portals Core 0.84
		immersive_portals: Immersive Portals 0.80
		java: Java HotSpot(TM) 64-Bit Server VM 8
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.1
		modmenu: Mod Menu 1.14.6+build.31
		optifabric: OptiFabric 1.9.2
		portalgun: Portal Gun 1.1.5
	Launched Version: fabric-loader-0.11.1-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.16.5_HD_U_G7
	OptiFine Build: 20210219-144623
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 0

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.16.5
	OptiFine jar version: OptiFine_1.16.5_HD_U_G7
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:\Users\ry0shi\AppData\Roaming\.randommodpack\.optifine\OptiFine_1.16.5_HD_U_G7\Optifine-mapped.jar
	OptiFabric error: <None>
```

**Comment by froyo4u** [comment]
update your Immersive portals, portal gun needs the newest preview version which you can find in this repository

**Comment by ry0shi** [comment]
> update your Immersive portals, portal gun needs the newest preview version which you can find in this repository

this is already the latest version (0.80)

**Comment by froyo4u** [comment]
It is not, This is: https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.87-1.16

**Comment by ry0shi** [comment]
thank you!

**Comment by qouteall** [comment]
@SilverHatTrick https://github.com/qouteall/sodium-fabric/releases
