### ISSUE TITLE
Game crashed on startup

### ISSUE THREAD

**Issue by MagierStein** [qouteall/ImmersivePortalsMod#663]
Game crashed on startup saying it was due to Immersive Portals Core

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 4/5/21 5:31 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'imm_ptl_core'!
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.6)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.client.MinecraftClient.redirect$bom000$catchFabricInit(MinecraftClient:8877)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:437)
	at net.minecraft.client.main.Main.main(Main:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$58/1388278453.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
Caused by: java.lang.RuntimeException: The sodium version that you use is incompatible with Immersive Portals. Check https://github.com/qouteall/sodium-fabric/releases
	at com.qouteall.hiding_in_the_bushes.ModEntryClient.onInitializeClient(ModEntryClient.java:77)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$5338/1066028017.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Initialization --
Details:
Stacktrace:
	at fudge.notenoughcrashes.mixinhandlers.EntryPointCatcher.handleEntryPointError(EntryPointCatcher.java:31)
	at net.minecraft.class_310.redirect$bom000$catchFabricInit(class_310.java:8879)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$58/1388278453.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2209270488 bytes (2106 MB) / 3459776512 bytes (3299 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 12
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8192m -Xms256m -XX:PermSize=256m
	Suspected Mods: Immersive Portals Core (imm_ptl_core), Fabric Loader (fabricloader)
	Fabric Mods: 
		addendum: Addendum 1.16.5-1.0.2
		adorn: Adorn 1.13.0+1.16.5
		adventurez: AdventureZ 1.2.2
		alaskanativecraft: Alaska Native Craft 1.1.1
		amecsapi: Amecs API 1.1.1+mc1.16-rc1
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		animal_feeding_trough: Animal Feeding Trough 1.0.2
		architectury: Architectury 1.10.139
		artifacts: Artifacts 3.1.0+fabric
		artifice: Artifice 0.14.6+1.16.5
		autoconfig1u: Auto Config v1 Updated 3.3.1
		backslot: BackSlot 1.1.9
		bambootweaks: Bamboo Tweaks 2.0.1+1.16.5
		bedspreads: Bedspreads 1.3.1-1.16.4
		bettercaves: YUNG's Better Caves 1.16.5-1.1
		betterend: Better End 0.9.1-pre
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.1
		betternether: Better Nether 5.0.7
		bettersleepplus: BetterSleepPlus 2.4.0
		biomemakeover: Biome Makeover 1.16.4-1.2.13
		blockus: Blockus 2.1.0+1.16.5
		brokennametags: Broken Name Tags 1.0.0
		byg: BYG 1.1.7
		caelus: Caelus API 0.0.15-1.16.4
		campanion: Campanion 1.3.5
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.0.2
		cardinal-components-base: Cardinal Components API (base) 2.7.12
		cardinal-components-block: Cardinal Components API (blocks) 2.7.10
		cardinal-components-entity: Cardinal Components API (entities) 2.7.12
		cardinal-components-item: Cardinal Components API (items) 2.7.10
		cardinal-components-world: Cardinal Components API (worlds) 2.7.10
		cavebiomes: Cave Biomes 0.6.2
		ce_foodstuffs: Common Expansion: Foodstuffs 1.1.5
		chainmail: Chainmail 0.5.0
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cinderscapes: Cinderscapes 1.3.3
		classicalart: Classical Art 1.1.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.19
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.2.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_udojava_evalex: EvalEx 2.5
		companion_bats: Companion Bats 1.9.0
		controlling: Controlling For Fabric 1.1.2
		couplings: Couplings 1.3.3
		crimsonmoon: Crimson Moon 2.0.4-1.16.5
		croptopia: Croptopia 1.3.1
		croptosis: Croptosis 1.0.1
		crowdin-translate: CrowdinTranslate 1.2
		curios: Curios API 0.0.13-1.16.5
		curiouselytra: Curious Elytra 1.1.1-1.16.5
		customizableelytra-fabric: Customizableelytra Fabric 1.2.0
		customportalapi: customportalapi 0.0.1-beta20-1.16
		dawn: Dawn API 1.8
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.2
		dragonloot: DragonLoot 1.0.5
		dual_riders: DualRiders 1.0.5
		dynamicfps: Dynamic FPS 2.0.1
		enva: Environmental Armor 1.2.0
		expandedstorage: ExpandedStorage 5.6.33
		extraalchemy: Extra Alchemy 1.4.3
		extraorigins: Extra Origins 1.16.5-10
		fabric: Fabric API 0.32.5+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.5+351679a77d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.3
		fallflyinglib: FallFlyingLib 1.1.0
		fallingleaves: Falling Leaves 1.5.0+1.16.5
		fantasycraft: Fantasycraft 1.1.2
		fatxporbs: Fat Experience Orbs 0.0.9
		fiber: fiber 0.23.0-2
		geckolib3: Geckolib 3.0.29
		gentlefawn: GentleFawn 1.1.4-MC1.16.5-fabric
		givemehats: Give Me Hats! 1.5
		go-fish: Go Fish 1.2.1-beta-1.16.4
		golemsgalore: Golems Galore 0.2.1+mc.1.16.5
		gravestones: Gravestones v1.9
		haema: Haema 1.6.0
		illuminations: Illuminations 1.4.8
		imm_ptl_core: Immersive Portals Core 0.88
		immersive_portals: Immersive Portals 0.88
		improved-stations: Improved Stations 2.0.3
		inmis: Inmis 2.2.0-1.16.5
		ironfurnaces: Iron Furnaces 2.4.1
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		jumploader: Jumploader 2.1.3
		lambdynlights: LambDynamicLights 1.3.4+1.16
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.5+1.16.5
		libstructure: Libstructure 1.3
		lightoverlay: Light Overlay 5.8.0
		lightstones: Lightstones 1.3.0
		lithium: Lithium 0.6.4
		magna: Magna 1.5.1-1.16.5
		mambience: MAmbience 3.1.1+1.16.5
		maybe-data: Maybe data 1.0.0-1.16.2
		minecraft: Minecraft 1.16.5
		moborigins: Mob Origins 1.3.1
		modmenu: Mod Menu 1.16.8
		moreberries: More Berries 1.3.4
		mostructures: Mo' Structures 1.1.1+mc.1.16.5
		notenoughcrashes: Not Enough Crashes 3.1.8
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		omega-config: OmegaConfig 1.0.4
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		origins: Origins 0.7.0
		origins-classes: Origins: Classes 1.1.1
		originsumbrellas: Origins: Umbrellas 1.1.0
		patchouli: Patchouli 1.16.4-50-FABRIC
		pehkui: Pehkui 1.9.0+21w10a
		phosphor: Phosphor 0.7.1+build.11
		ratsmischief: Rat's Mischief 1.1
		reach-entity-attributes: Reach Entity Attributes 1.1.0
		repurposed_structures: Repurposed Structures 1.16.5-1.10.1-fabric
		retail: Retail 0.1.1
		riverredux: River Redux 0.1.6
		roughlyenoughitems: Roughly Enough Items 5.11.188
		roughlyenoughitems-api: REI (API) 5.11.188
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.188
		roughlyenoughitems-runtime: REI (Runtime) 5.11.188
		roughlyenoughresources: Roughly Enough Resources 2.1.3
		rpgstats: RPGStats 3.2.6+1.16.5
		sandwichable: Sandwichable 1.2-beta5
		satin: Satin 1.6.0-nightly.20w48a
		secretrooms: Secret Rooms 0.9.3+1.16.5
		seedy-behavior: Seedy Behavior 1.0.1
		slimeorigin: Slimeorigin 2.1.0
		smithee: Smithee 0.2.3
		sodium: Sodium 0.1.0
		somnus: Somnus API 0.0.10-1.16.4
		spruceui: SpruceUI 2.0.4+1.16
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		structurized: Structurized 1.2.0-1.16.5
		team_reborn_energy: Energy 0.1.1
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.5
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
		terrestria: Terrestria 2.2.0
		the_aether: The Aether 1.16.5-1.0.1
		the_bumblezone: The Bumblezone - Fabric 1.16.5-2.3.0
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		traverse: Traverse 3.3.2
		trinkets: Trinkets 2.6.7
		unforgivingvoid: Unforgiving Void 2.0.0
		untitledduckmod: Untitled Duck Mod 0.1.1
		vanguard: Vanguard 1.0.5
		vanilla-hammers: Vanilla Hammers 3.0.2-1.16.5
		vanillaenhanced: VanillaEnhanced 1.4.0
		voxelmap: VoxelMap 1.10.15
		voyager: Voyager 1.0.0
		wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
		wthit: wthit 2.5.4
		yungsapi: YUNG's API 1.16.5-Fabric-2
		zoob: Monster Of The Ocean Depths 3.0.0
	Patchouli open book context: n/a
	Launched Version: 1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by MagierStein** [comment]
It appears the issue was due to incompatibility with Sodium

**Comment by qouteall** [comment]
https://github.com/qouteall/sodium-fabric/releases
