### ISSUE TITLE
Minecraft keeps crashing with immersive portals.

### ISSUE THREAD

**Issue by Begnom** [qouteall/ImmersivePortalsMod#670]
This not only happens on fabric, but also on forge. It just crashes without any crash log. on fabric, it just shuts down in one second and on forge it almost loads completely but then crashes.

**Comment by qouteall** [comment]
Post the log `logs/latest.log`

**Comment by notAndr3i** [comment]
Do you have sodium installed? If you do, then it doesn't work.There is an special sodium in the IP page.If you are using the special version then i do not know what is causing this.I had the same problem and changing my sodium version to the special one worked.

**Comment by Tawab123** [comment]
I get this error ---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 12/12/21 2:24 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'imm_ptl_core'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils$$Lambda$2780/1397813881.apply(Unknown Source)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: ---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 12/12/21 2:24 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'imm_ptl_core'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils$$Lambda$2780/1397813881.apply(Unknown Source)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: The sodium version that you use is incompatible with Immersive Portals. Check https://github.com/qouteall/sodium-fabric/releases
	at com.qouteall.hiding_in_the_bushes.ModEntryClient.onInitializeClient(ModEntryClient.java:77)
	at net.fabricmc.loader.impl.game.minecraft.Hooks$$Lambda$2570/559361838.accept(Unknown Source)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	
	at com.qouteall.hiding_in_the_bushes.ModEntryClient.onInitializeClient(ModEntryClient.java:77)
	at net.fabricmc.loader.impl.game.minecraft.Hooks$$Lambda$2570/559361838.accept(Unknown Source)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	     
whenever i launch the game it says ("The sodium version that you use is incompatible with Immersive Portals. Check https://github.com/qouteall/sodium-fabric/releases") i checked and i still cant find the solution

**Comment by qouteall** [comment]
@Tawab123 use this sodium https://github.com/qouteall/sodium-fabric/releases/tag/ipc1165_2
