### ISSUE TITLE
Game crashes when trying to scale with Pehkui mod

### ISSUE THREAD

**Issue by Foxygamer3001** [qouteall/ImmersivePortalsMod#677]
When ever I try to scale bigger or smaller, the game instantly crashes. I have the latest version of bothe Pehkui and Immersive Portals.

**Comment by Foxygamer3001** [comment]
Here's the Crash Report

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 18/04/21 21:32
Description: Unexpected error

java.lang.NoClassDefFoundError: net/minecraft/command/arguments/IArgumentSerializer
	at virtuoel.pehkui.api.ScaleRegistries.create(ScaleRegistries.java:45)
	at virtuoel.pehkui.api.ScaleRegistries.<clinit>(ScaleRegistries.java:20)
	at virtuoel.pehkui.api.ScaleType.<clinit>(ScaleType.java:18)
	at com.qouteall.hiding_in_the_bushes.PehkuiInterfaceInitializer.onPlayerTeleportedClient(PehkuiInterfaceInitializer.java:46)
	at com.qouteall.hiding_in_the_bushes.PehkuiInterfaceInitializer$$Lambda$2455/1622096108.accept(Unknown Source)
	at com.qouteall.immersive_portals.teleportation.ClientTeleportationManager.teleportPlayer(ClientTeleportationManager.java:217)
	at com.qouteall.immersive_portals.teleportation.ClientTeleportationManager.tryTeleport(ClientTeleportationManager.java:170)
	at com.qouteall.immersive_portals.teleportation.ClientTeleportationManager.manageTeleportation(ClientTeleportationManager.java:119)
	at net.minecraft.class_757.handler$zkl000$onFarBeforeRendering(class_757.java:2487)
	at net.minecraft.class_757.method_3192(class_757.java)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.command.arguments.IArgumentSerializer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at virtuoel.pehkui.api.ScaleRegistries.create(ScaleRegistries.java:45)
	at virtuoel.pehkui.api.ScaleRegistries.<clinit>(ScaleRegistries.java:20)
	at virtuoel.pehkui.api.ScaleType.<clinit>(ScaleType.java:18)
	at com.qouteall.hiding_in_the_bushes.PehkuiInterfaceInitializer.onPlayerTeleportedClient(PehkuiInterfaceInitializer.java:46)
	at com.qouteall.hiding_in_the_bushes.PehkuiInterfaceInitializer$$Lambda$2455/1622096108.accept(Unknown Source)
	at com.qouteall.immersive_portals.teleportation.ClientTeleportationManager.teleportPlayer(ClientTeleportationManager.java:217)
	at com.qouteall.immersive_portals.teleportation.ClientTeleportationManager.tryTeleport(ClientTeleportationManager.java:170)
	at com.qouteall.immersive_portals.teleportation.ClientTeleportationManager.manageTeleportation(ClientTeleportationManager.java:119)
	at net.minecraft.class_757.handler$zkl000$onFarBeforeRendering(class_757.java:2487)

-- Affected level --
Details:
	All players: 1 total; [class_746['Foxygamer3001'/13, l='ClientWorld minecraft:overworld', x=-203.97, y=7.24, z=-140.95]]
	Chunk stats: Client Chunks (ImmPtl) 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (-208,4,-128), Chunk: (at 0,0,0 in -13,-8; contains blocks -208,0,-128 to -193,255,-113), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 16570 game time, 6000 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1284474264 bytes (1224 MB) / 2013265920 bytes (1920 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.11.15
		fabric: Fabric API 0.32.9+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.3
		imm_ptl_core: Immersive Portals Core 0.90
		immersive_portals: Immersive Portals 0.90
		java: Java HotSpot(TM) 64-Bit Server VM 8
		minecraft: Minecraft 1.16.5
		modmenu: Mod Menu v1.16.8+unknown.bd9230a
		pehkui: Pehkui (Forge Version) 0.0.0+forge
		worldedit: WorldEdit 7.2.4+5723-e3bfc64
	Launched Version: fabric-loader-0.11.3-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) Vega 8 Graphics GL version 4.6.13587 Compatibility Profile Context 19.40.46 26.20.14046.3, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 8x AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx

**Comment by qouteall** [comment]
You seem to be using pehkui forge version in fabric

**Comment by StupidRepo** [comment]
To save space, please close this question @qouteall/@Foxygamer3001

**Comment by hjhyhg** [comment]
you are using the forge version on fabric

**Comment by StupidRepo** [comment]
> you are using the forge version on fabric

Please, do not post here and shut up. (Sorry for saying shut up, this really just triggered me). It has already been answered unless you are blind and cannot see it's already been answered.
