### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nullified33** [qouteall/ImmersivePortalsMod#732]
[03/06/2021 19:02:29 PM] [19:02:29] [main/FATAL]: Unreported exception thrown!
[03/06/2021 19:02:29 PM] java.lang.NoSuchMethodError: me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.createNewRenderContext()Lme/jellysquid/mods/sodium/client/render/chunk/ChunkRenderManager$RenderContext;
[03/06/2021 19:02:29 PM] 	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.9) ~[?:?]
[03/06/2021 19:02:29 PM] 	at com.qouteall.hiding_in_the_bushes.sodium_compatibility.SodiumInterfaceInitializer.lambda$init$0(SodiumInterfaceInitializer.java:19) ~[44c3c776-5c70-4dd8-ad27-3ecc602bcae4.jar:?]
[03/06/2021 19:02:29 PM] 	at com.qouteall.hiding_in_the_bushes.sodium_compatibility.SodiumInterfaceInitializer$$Lambda$7651/927944849.apply(Unknown Source) ~[?:?]
[03/06/2021 19:02:29 PM] 	at com.qouteall.immersive_portals.render.MyGameRenderer.switchAndRenderTheWorld(MyGameRenderer.java:177) ~[44c3c776-5c70-4dd8-ad27-3ecc602bcae4.jar:?]
[03/06/2021 19:02:29 PM] 	at com.qouteall.immersive_portals.render.MyGameRenderer.renderWorldNew(MyGameRenderer.java:75) ~[44c3c776-5c70-4dd8-ad27-3ecc602bcae4.jar:?]
[03/06/2021 19:02:29 PM] 	at com.qouteall.immersive_portals.render.PortalRenderer.invokeWorldRendering(PortalRenderer.java:226) ~[44c3c776-5c70-4dd8-ad27-3ecc602bcae4.jar:?]
[03/06/2021 19:02:29 PM] 	at com.qouteall.immersive_portals.render.PortalRenderer.renderPortalContent(PortalRenderer.java:191) ~[44c3c776-5c70-4dd8-ad27-3ecc602bcae4.jar:?]
[03/06/2021 19:02:29 PM] 	at com.qouteall.immersive_portals.render.RendererUsingStencil.doRenderPortal(RendererUsingStencil.java:140) ~[44c3c776-5c70-4dd8-ad27-3ecc602bcae4.jar:?]
[03/06/2021 19:02:29 PM] 	at com.qouteall.immersive_portals.render.PortalRenderer.renderPortals(PortalRenderer.java:110) ~[44c3c776-5c70-4dd8-ad27-3ecc602bcae4.jar:?]
[03/06/2021 19:02:29 PM] 	at com.qouteall.immersive_portals.render.RendererUsingStencil.doPortalRendering(RendererUsingStencil.java:53) ~[44c3c776-5c70-4dd8-ad27-3ecc602bcae4.jar:?]
[03/06/2021 19:02:29 PM] 	at com.qouteall.immersive_portals.render.RendererUsingStencil.onBeforeTranslucentRendering(RendererUsingStencil.java:48) ~[44c3c776-5c70-4dd8-ad27-3ecc602bcae4.jar:?]
[03/06/2021 19:02:29 PM] 	at net.minecraft.client.render.WorldRenderer.handler$zkf000$onBeforeTranslucentRendering(WorldRenderer:6724) ~[?:?]
[03/06/2021 19:02:29 PM] 	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1360) ~[?:?]
[03/06/2021 19:02:29 PM] 	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:727) ~[?:?]
[03/06/2021 19:02:29 PM] 	at net.minecraft.client.render.GameRenderer.redirect$zkb000$redirectRenderingWorld(GameRenderer:3052) ~[?:?]
[03/06/2021 19:02:29 PM] 	at net.minecraft.client.render.GameRenderer.render(GameRenderer:546) ~[?:?]
[03/06/2021 19:02:29 PM] 	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1048) ~[?:?]
[03/06/2021 19:02:29 PM] 	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681) ~[?:?]
[03/06/2021 19:02:29 PM] 	at net.minecraft.client.main.Main.main(Main:215) [intermediary-client-1.16.5.jar:?]
[03/06/2021 19:02:29 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
[03/06/2021 19:02:29 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
[03/06/2021 19:02:29 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
[03/06/2021 19:02:29 PM] 	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
[03/06/2021 19:02:29 PM] 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
[03/06/2021 19:02:29 PM] 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
[03/06/2021 19:02:29 PM] 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
[03/06/2021 19:02:29 PM] [19:02:29] [main/FATAL]: Minecraft ran into a problem! Report saved to: **USERSDIR**\instances\CCTesting\crash-reports\crash-2021-06-03_19.02.29-client.txt
[03/06/2021 19:02:29 PM] ---- Minecraft Crash Report ----
[03/06/2021 19:02:29 PM] // Hi. I'm Minecraft, and I'm a crashaholic.
[03/06/2021 19:02:29 PM] 
[03/06/2021 19:02:29 PM] Time: 6/3/21 7:02 PM
[03/06/2021 19:02:29 PM] Description: Unexpected error
[03/06/2021 19:02:29 PM] 
[03/06/2021 19:02:29 PM] java.lang.NoSuchMethodError: me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.createNewRenderContext()Lme/jellysquid/mods/sodium/client/render/chunk/ChunkRenderManager$RenderContext;
[03/06/2021 19:02:29 PM] 	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.9)
[03/06/2021 19:02:29 PM] 	at com.qouteall.hiding_in_the_bushes.sodium_compatibility.SodiumInterfaceInitializer.lambda$init$0(SodiumInterfaceInitializer.java:19)
[03/06/2021 19:02:29 PM] 	at com.qouteall.hiding_in_the_bushes.sodium_compatibility.SodiumInterfaceInitializer$$Lambda$7651/927944849.apply(Unknown Source)
[03/06/2021 19:02:29 PM] 	at com.qouteall.immersive_portals.render.MyGameRenderer.switchAndRenderTheWorld(MyGameRenderer.java:177)
[03/06/2021 19:02:29 PM] 	at com.qouteall.immersive_portals.render.MyGameRenderer.renderWorldNew(MyGameRenderer.java:75)
[03/06/2021 19:02:29 PM] 	at com.qouteall.immersive_portals.render.PortalRenderer.invokeWorldRendering(PortalRenderer.java:226)
[03/06/2021 19:02:29 PM] 	at com.qouteall.immersive_portals.render.PortalRenderer.renderPortalContent(PortalRenderer.java:191)
[03/06/2021 19:02:29 PM] 	at com.qouteall.immersive_portals.render.RendererUsingStencil.doRenderPortal(RendererUsingStencil.java:140)
[03/06/2021 19:02:29 PM] 	at com.qouteall.immersive_portals.render.PortalRenderer.renderPortals(PortalRenderer.java:110)
[03/06/2021 19:02:29 PM] 	at com.qouteall.immersive_portals.render.RendererUsingStencil.doPortalRendering(RendererUsingStencil.java:53)
[03/06/2021 19:02:30 PM] 	at com.qouteall.immersive_portals.render.RendererUsingStencil.onBeforeTranslucentRendering(RendererUsingStencil.java:48)
[03/06/2021 19:02:30 PM] 	at net.minecraft.client.render.WorldRenderer.handler$zkf000$onBeforeTranslucentRendering(WorldRenderer:6724)
[03/06/2021 19:02:30 PM] 	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1360)
[03/06/2021 19:02:30 PM] 	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:727)
[03/06/2021 19:02:30 PM] 	at net.minecraft.client.render.GameRenderer.redirect$zkb000$redirectRenderingWorld(GameRenderer:3052)
[03/06/2021 19:02:30 PM] 	at net.minecraft.client.render.GameRenderer.render(GameRenderer:546)
[03/06/2021 19:02:30 PM] 	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1048)
[03/06/2021 19:02:30 PM] 	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
[03/06/2021 19:02:30 PM] 	at net.minecraft.client.main.Main.main(Main:215)
[03/06/2021 19:02:30 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03/06/2021 19:02:30 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[03/06/2021 19:02:31 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03/06/2021 19:02:31 PM] 	at java.lang.reflect.Method.invoke(Method.java:497)
[03/06/2021 19:02:31 PM] 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
[03/06/2021 19:02:31 PM] 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
[03/06/2021 19:02:31 PM] 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
[03/06/2021 19:02:31 PM] 
[03/06/2021 19:02:31 PM] 
[03/06/2021 19:02:31 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[03/06/2021 19:02:31 PM] ---------------------------------------------------------------------------------------
[03/06/2021 19:02:31 PM] 
[03/06/2021 19:02:32 PM] -- Affected level --
[03/06/2021 19:02:32 PM] Details:
[03/06/2021 19:02:32 PM] 	All players: 0 total; []
[03/06/2021 19:02:32 PM] 	Chunk stats: Client Chunks (ImmPtl) 0
[03/06/2021 19:02:32 PM] 	Level dimension: minecraft:the_nether
[03/06/2021 19:02:32 PM] 	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
[03/06/2021 19:02:32 PM] 	Level time: 158 game time, 158 day time
[03/06/2021 19:02:32 PM] 	Server brand: fabric
[03/06/2021 19:02:32 PM] 	Server type: Integrated singleplayer server
[03/06/2021 19:02:32 PM] Stacktrace:
[03/06/2021 19:02:32 PM] 	at net.minecraft.class_638.method_8538(class_638.java:449)
[03/06/2021 19:02:33 PM] 	at net.minecraft.class_310.method_1587(class_310.java:2239)
[03/06/2021 19:02:33 PM] 	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28)
[03/06/2021 19:02:33 PM] 	at net.minecraft.class_310.modify$bne000$onCrash(class_310.java:10912)
[03/06/2021 19:02:33 PM] 	at net.minecraft.class_310.method_1514(class_310.java:704)
[03/06/2021 19:02:33 PM] 	at net.minecraft.client.main.Main.main(Main.java:215)
[03/06/2021 19:02:33 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03/06/2021 19:02:33 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[03/06/2021 19:02:33 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03/06/2021 19:02:33 PM] 	at java.lang.reflect.Method.invoke(Method.java:497)
[03/06/2021 19:02:33 PM] 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
[03/06/2021 19:02:33 PM] 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
[03/06/2021 19:02:34 PM] 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
[03/06/2021 19:02:34 PM] -- System Details --
[03/06/2021 19:02:34 PM] Details:
[03/06/2021 19:02:34 PM] 	Minecraft Version: 1.16.5
[03/06/2021 19:02:34 PM] 	Minecraft Version ID: 1.16.5
[03/06/2021 19:02:34 PM] 	Operating System: Windows 10 (amd64) version 10.0
[03/06/2021 19:02:34 PM] 	Java Version: 1.8.0_51, Oracle Corporation
[03/06/2021 19:02:34 PM] 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[03/06/2021 19:02:34 PM] 	Memory: 4771319464 bytes (4550 MB) / 8220835840 bytes (7840 MB) up to 13958643712 bytes (13312 MB)
[03/06/2021 19:02:34 PM] 	CPUs: 8
[03/06/2021 19:02:34 PM] 	JVM Flags: 13 total; -XX:-OmitStackTraceInFastThrow -Xms512M -Xmx4096M -XX:MetaspaceSize=256M -Xmx13G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=30 -XX:G1ReservePercent=30 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=512M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
[03/06/2021 19:02:34 PM] 	Suspected Mods: Fabric Loader (fabricloader), Immersive Portals Core (imm_ptl_core)
[03/06/2021 19:02:34 PM] 	Fabric Mods: 
[03/06/2021 19:02:34 PM] 		addendum: Addendum 1.16.5-1.0.2
[03/06/2021 19:02:34 PM] 		adorn: Adorn 1.14.1+1.16.5
[03/06/2021 19:02:34 PM] 		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.7
[03/06/2021 19:02:34 PM] 		amecs: Amecs 1.3.4+mc.1.16.3
[03/06/2021 19:02:34 PM] 		amecsapi: Amecs API 1.1.4+mc1.16.5
[03/06/2021 19:02:34 PM] 		angerable-patch: Angerable Patch 1.1.0-1.16.4
[03/06/2021 19:02:34 PM] 		appleskin: AppleSkin 1.0.11
[03/06/2021 19:02:34 PM] 		arcana2plus: Arcana ++ 0.0.3+1.16-alpha
[03/06/2021 19:02:34 PM] 		arcanaflavor: Arcana Flavor 0.0.8+1.16-alpha
[03/06/2021 19:02:34 PM] 		architectury: Architectury 1.9.132
[03/06/2021 19:02:34 PM] 		arfo: Artificial Foliage 2.0
[03/06/2021 19:02:34 PM] 		arstheurgia: Ars Theurgia 1.0.6
[03/06/2021 19:02:34 PM] 		artifacts: Artifacts 3.2.1+fabric
[03/06/2021 19:02:34 PM] 		artifice: Artifice 0.14.6+1.16.5
[03/06/2021 19:02:34 PM] 		artofalchemy: Art of Alchemy: Memoriam 1.0.0-rc4+1.16.4
[03/06/2021 19:02:34 PM] 		astromine: Astromine 1.11.5+fabric-1.16.5
[03/06/2021 19:02:34 PM] 		astromine-core: Astromine: Core 1.11.5+fabric-1.16.5
[03/06/2021 19:02:34 PM] 		astromine-discoveries: Astromine: Discoveries 1.11.5+fabric-1.16.5
[03/06/2021 19:02:34 PM] 		astromine-foundations: Astromine: Foundations 1.11.5+fabric-1.16.5
[03/06/2021 19:02:34 PM] 		astromine-technologies: Astromine: Technologies 1.11.5+fabric-1.16.5
[03/06/2021 19:02:34 PM] 		astromine-transportations: Astromine: Transportations 1.11.5+fabric-1.16.5
[03/06/2021 19:02:34 PM] 		atbyw: All The Blocks You Want (ATBYW) 1.3.4
[03/06/2021 19:02:34 PM] 		autoconfig1u: Auto Config v1 Updated 3.3.1
[03/06/2021 19:02:34 PM] 		automated_crafting: Automated Crafting 1.3.21+MC1.16.2-1.16.5
[03/06/2021 19:02:34 PM] 		axesareweapons: Axes Are Weapons 1.1
[03/06/2021 19:02:34 PM] 		backslot: BackSlot 1.1.11
[03/06/2021 19:02:34 PM] 		bambootweaks: Bamboo Tweaks 2.0.5
[03/06/2021 19:02:34 PM] 		beachslimes: Beach Slimes 2.1.0+mc1.16.1
[03/06/2021 19:02:34 PM] Exception in thread "Thread-397" [19:02:29] [Thread-397/INFO]: [STDERR]: java.lang.NullPointerException
[03/06/2021 19:02:34 PM] [19:02:29] [Thread-397/INFO]: [STDERR]: 	at com.vandendaelen.nicephore.thread.InitThread.run(InitThread.java:60)

**Comment by qouteall** [comment]
Do you have sodium installed?

**Comment by nullified33** [comment]
> Do you have sodium installed?

yes, a fork of your fork

**Comment by qouteall** [comment]
Which fork?

**Comment by nullified33** [comment]
> Which fork?

https://github.com/machinesmith42/sodium-fabric with Indium

**Comment by qouteall** [comment]
I am going to check this later. I am only sure that my sodium fork works https://github.com/qouteall/sodium-fabric/releases
