### ISSUE TITLE
1.17 compatibility issues causing crashes

### ISSUE THREAD

**Issue by micahflack** [qouteall/ImmersivePortalsMod#743]
Using Immersive Portals 0.04 for Fabric 1.17 causes the server to crash with any of the following mods:

*SimplePipes
*GeckoLib, HappinessWithGuns
*DimensionalDoors 
*MoreVillagersFabric
*Industrial Revolution
*Stoneholm
*Gobber2
*GateOfBabylon
*MCDungeonArmor
*MedievalWeapons
*VillagerNames

The same error code thrown at crash is the following...

`[13:22:16] [main/FATAL]: Failed to start the minecraft server
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.method_3831()" because the return value of "qouteall.q_misc_util.MiscHelper.getServer()" is null
	at qouteall.imm_ptl.core.platform_specific.IPConfig.getGameDir(IPConfig.java:57) ~[b8ceeacd-5e09-40af-b90c-40a562fb1ad2.jar:?]
	at qouteall.imm_ptl.core.platform_specific.IPConfig.readConfig(IPConfig.java:62) ~[b8ceeacd-5e09-40af-b90c-40a562fb1ad2.jar:?]
	at qouteall.imm_ptl.core.platform_specific.O_O.loadConfigFabric(O_O.java:68) ~[b8ceeacd-5e09-40af-b90c-40a562fb1ad2.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zeg000$onServerConstruct(MinecraftServer.java:2311) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:305) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.<init>(class_3176.java:86) ~[intermediary-server.jar:?]
	at net.minecraft.server.Main.method_29734(Main.java:195) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:277) ~[intermediary-server.jar:?]
	at net.minecraft.server.Main.main(Main.java:194) [intermediary-server.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]`

**Comment by qouteall** [comment]
Does this version fix the issue? https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.05-1.17

**Comment by micahflack** [comment]
Seems to have resolved any conflicts. Whatever incompatibility there is with DimensionalDoors does not seem to be caused by Immersive Portals.

`Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:58)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:116)
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:70)
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68)
	... 2 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:236)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28)
	... 7 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	... 9 more
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/render/fluid/v1/FluidRenderHandler
	at org.dimdev.dimdoors.block.EternalFluidBlock.<init>(EternalFluidBlock.java:25)
	at org.dimdev.dimdoors.block.ModBlocks.<clinit>(ModBlocks.java:154)
	at org.dimdev.dimdoors.world.feature.ModFeatures.<clinit>(ModFeatures.java:48)
	at net.minecraft.class_3864.handler$zzb000$addGateway(class_3864.java:589)
	at net.minecraft.class_3864.method_17003(class_3864.java:57)
	at net.minecraft.class_5478.method_30698(class_5478.java:333)
	at net.minecraft.class_5504.<clinit>(class_5504.java:19)
	at net.minecraft.class_5458.method_30567(class_5458.java:52)
	at net.minecraft.class_5458.method_30566(class_5458.java:75)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at net.minecraft.class_5458.<clinit>(class_5458.java:74)
	at net.minecraft.class_2378.<clinit>(class_2378.java:266)
	at net.minecraft.class_2966.method_12851(class_2966.java:44)
	at net.minecraft.server.Main.main(Main.java:92)
	... 14 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:57)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 28 more`

**Comment by micahflack** [comment]
Did some more checking and the incompatibility with DimensionalDoors was caused by GlassDoors 1.5.0-1.17... So there are no issues with IP and DimDoors.

Thanks!
