### ISSUE TITLE
Incompatible with Better End. End portal crash

### ISSUE THREAD

**Issue by AzureMonument** [qouteall/ImmersivePortalsMod#771]
Playing fabric (api: 0.36.0, loader 0.11.6), minecraft 1.17, immersive portals 0.10. Have a chunk of other mods, including BetterEnd and BetterNether. As well as Better Strongholds (yung). I also am running lithium and krypton.
Game instantly crashes when placing the last eye of ender in the end portal (right after the heavy crash/thrum). Nether Portals function as expected.

Crash Log: 
[16:27:51] [Render thread/INFO]: WorldRenderer reloaded minecraft:the_end
[16:27:51] [Render thread/INFO]: Client World Created minecraft:the_end
[16:27:51] [Render thread/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_ENUM in (null): (ID: 173538523) Generic error'
[16:27:51] [Render thread/INFO]: [STDERR]: java.lang.Throwable
[16:27:51] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1008.handler$bgo000$onLogging(class_1008.java:521)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1008.method_4224(class_1008.java:104)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.opengl.GL11C.glEnable(Native Method)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.opengl.GL11.glEnable(GL11.java:777)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_761.handler$def000$be_renderBetterEndSky(class_761.java:8575)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_761.method_3257(class_761.java)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_761.method_22710(class_761.java:1137)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_757.method_3188(class_757.java:1001)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at qouteall.imm_ptl.core.render.MyGameRenderer.lambda$switchAndRenderTheWorld$0(MyGameRenderer.java:197)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at qouteall.imm_ptl.core.render.MyGameRenderer.switchAndRenderTheWorld(MyGameRenderer.java:195)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at qouteall.imm_ptl.core.render.MyGameRenderer.renderWorldNew(MyGameRenderer.java:75)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at qouteall.imm_ptl.core.render.PortalRenderer.invokeWorldRendering(PortalRenderer.java:229)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at qouteall.imm_ptl.core.render.PortalRenderer.renderPortalContent(PortalRenderer.java:195)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at qouteall.imm_ptl.core.render.RendererUsingStencil.doRenderPortal(RendererUsingStencil.java:140)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at qouteall.imm_ptl.core.render.PortalRenderer.renderPortals(PortalRenderer.java:110)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at qouteall.imm_ptl.core.render.RendererUsingStencil.doPortalRendering(RendererUsingStencil.java:54)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at qouteall.imm_ptl.core.render.RendererUsingStencil.onBeforeTranslucentRendering(RendererUsingStencil.java:49)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_761.handler$bih000$onBeforeTranslucentRendering(class_761.java:6897)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_761.method_22710(class_761.java:1379)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_757.method_3188(class_757.java:1001)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_757.redirect$bic000$redirectRenderingWorld(class_757.java:5092)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_757.method_3192(class_757.java:806)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1114)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:730)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:217)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[16:27:51] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
FATAL ERROR in native method: Thread[Render thread,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL11.glAlphaFunc(Native Method)
	at net.minecraft.class_761.handler$def000$be_renderBetterEndSky(class_761.java:8576)
	at net.minecraft.class_761.method_3257(class_761.java)
	at net.minecraft.class_761.method_22710(class_761.java:1137)
	at net.minecraft.class_757.method_3188(class_757.java:1001)
	at qouteall.imm_ptl.core.render.MyGameRenderer.lambda$switchAndRenderTheWorld$0(MyGameRenderer.java:197)
	at qouteall.imm_ptl.core.render.MyGameRenderer$$Lambda$11815/0x00000008022f6220.run(Unknown Source)
	at qouteall.imm_ptl.core.render.PortalRenderer$$Lambda$11812/0x00000008022f3ab0.accept(Unknown Source)
	at qouteall.imm_ptl.core.render.MyGameRenderer.switchAndRenderTheWorld(MyGameRenderer.java:195)
	at qouteall.imm_ptl.core.render.MyGameRenderer.renderWorldNew(MyGameRenderer.java:75)
	at qouteall.imm_ptl.core.render.PortalRenderer.invokeWorldRendering(PortalRenderer.java:229)
	at qouteall.imm_ptl.core.render.PortalRenderer.renderPortalContent(PortalRenderer.java:195)
	at qouteall.imm_ptl.core.render.RendererUsingStencil.doRenderPortal(RendererUsingStencil.java:140)
	at qouteall.imm_ptl.core.render.PortalRenderer.renderPortals(PortalRenderer.java:110)
	at qouteall.imm_ptl.core.render.RendererUsingStencil.doPortalRendering(RendererUsingStencil.java:54)
	at qouteall.imm_ptl.core.render.RendererUsingStencil.onBeforeTranslucentRendering(RendererUsingStencil.java:49)
	at net.minecraft.class_761.handler$bih000$onBeforeTranslucentRendering(class_761.java:6897)
	at net.minecraft.class_761.method_22710(class_761.java:1379)
	at net.minecraft.class_757.method_3188(class_757.java:1001)
	at net.minecraft.class_757.redirect$bic000$redirectRenderingWorld(class_757.java:5092)
	at net.minecraft.class_757.method_3192(class_757.java:806)
	at net.minecraft.class_310.method_1523(class_310.java:1114)
	at net.minecraft.class_310.method_1514(class_310.java:730)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@16.0.1/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@16.0.1/Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@16.0.1/Unknown Source)
	at java.lang.reflect.Method.invoke(java.base@16.0.1/Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@16.0.1/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@16.0.1/Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@16.0.1/Unknown Source)
	at java.lang.reflect.Method.invoke(java.base@16.0.1/Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 1.

**Comment by qouteall** [comment]
First don't use lithium with IP because it may memory leak.
It seem to crash inside better end sky rendering 
```
GL11.glEnable(GL11.GL_ALPHA_TEST);

GL11.glEnable(GL11.GL_BLEND);
```
Does this issue happen without this mod?

**Comment by AzureMonument** [comment]
Just tested it, no- if I remove better end it works fine. Should I go move this crash over to better end?

**Comment by qouteall** [comment]
@AzureMonument Does the issue happen with better end and without Immersive Portals?

**Comment by AzureMonument** [comment]
Just tried it, and it looks like it doesn't.

**Comment by MR-Spagetty** [comment]
I have encountered a similar issue but was not creating any crash log and I found that after removing better end the crash no longer occurred
my full mod list is:
![image](https://user-images.githubusercontent.com/54694556/125563833-93bbf821-3355-466f-8e2b-85b3f83c7358.png)
(here better end is disabled)

**Comment by schuberty** [comment]
I think I have the same issue. I removed Lithium but still got the same error. Got BetterEnd and IP with some other mods as well. 

Does Lithium on server side makes any diference?

[latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/6827738/latest.log)

**Comment by schuberty** [comment]
BetterEnd solved the issues. But now it looks like the render distance is something like 2 but in a sphere shape when in The End.
