### ISSUE TITLE
Can't start server on 1.17.1 preview version

### ISSUE THREAD

**Issue by Orangenal-name** [qouteall/ImmersivePortalsMod#785]
Server thread/FATAL17:08:16
Mixin apply failed imm_ptl.mixins.json:common.chunk_sync.MixinThreadedAnvilChunkStorage_C -> net.minecraft.class_3898: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field field_17707 was not located in the target class net.minecraft.class_3898. Using refmap imm_ptl_core-refmap.json
Console17:08:16
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_17707 was not located in the target class net.minecraft.class_3898. Using refmap imm_ptl_core-refmap.json
at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:610) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:289) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-server-launch.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
at net.minecraft.class_3215.<init>(class_3215.java:87) ~[intermediary-server.jar:?]
at net.minecraft.class_3218.<init>(class_3218.java:200) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:383) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:350) ~[intermediary-server.jar:?]
at net.minecraft.class_3176.method_3823(class_3176.java:184) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
at java.lang.Thread.run(Thread.java:831) [?:?]
Server thread/ERROR17:08:16
Encountered an unexpected exception
Console17:08:16
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-server-launch.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
at net.minecraft.class_3215.<init>(class_3215.java:87) ~[intermediary-server.jar:?]
at net.minecraft.class_3218.<init>(class_3218.java:200) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:383) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:350) ~[intermediary-server.jar:?]
at net.minecraft.class_3176.method_3823(class_3176.java:184) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [imm_ptl.mixins.json:common.chunk_sync.MixinThreadedAnvilChunkStorage_C] from phase [DEFAULT] in config [imm_ptl.mixins.json] FAILED during APPLY
at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356) ~[fabric-server-launch.jar:?]
... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_17707 was not located in the target class net.minecraft.class_3898. Using refmap imm_ptl_core-refmap.json
at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:610) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:289) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric-server-launch.jar:?]
... 14 more
Server thread/ERROR17:08:16
This crash report has been saved to: /home/amp/.ampdata/instances/AlexsWorld/Minecraft/./crash-reports/crash-2021-07-17_16.08.16-server.txt
Server thread/INFO17:08:16
Stopping server
Saving players
Saving worlds
Server thread/ERROR17:08:16
Exception stopping the server
Console17:08:16
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_8621()" because "â˜ƒ" is null
at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:588) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:624) ~[intermediary-server.jar:?]
at net.minecraft.class_3176.method_3782(class_3176.java:585) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:734) ~[intermediary-server.jar:?]
17:08:17
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by qouteall** [comment]
What's the minecraft version and the mod version?
