### ISSUE TITLE
1.17 IP + Optifabric causes Java Crash Eventually ('EXCEPTION_ACCESS_VIOLATION')

### ISSUE THREAD

**Issue by MindForged** [qouteall/ImmersivePortalsMod#796]
IP never gave me any crashes before I added Optifabric/fine (HD_U_G9_pre26) for a resource pack. But with them added,  the game will crash after a few minutes, due to the Java runtime also crashing. Removing Optifabric from the mod loader seems to stop this, but it would really suck if that's the only fix (seems to happen with every 1.17 mod version). The loader also had this error while loading but long before the crash minutes later (client side only, server simply notes my disconnection):

`[15:39:22] [Render thread/INFO]: WorldRenderer reloaded minecraft:overworld
[15:39:22] [Render thread/FATAL]: Error executing task on Client
java.lang.IndexOutOfBoundsException: Index 46 out of bounds for length 46

Full crash report:

[hs_err_pid5984.txt](https://github.com/qouteall/ImmersivePortalsMod/files/6858816/hs_err_pid5984.txt)

**Comment by qouteall** [comment]
Try to turn off render regions

**Comment by MindForged** [comment]
> Try to turn off render regions

Did that, same result.

**Comment by Cva666** [comment]
I am having the same issue with it. full crash report:

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 7/30/21, 11:26 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'imm_ptl_core'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3334)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2611)
	at qouteall.imm_ptl.core.compat.optifine_compatibility.OFBuiltChunkStorageFix.lambda$init$0(OFBuiltChunkStorageFix.java:31)
	at qouteall.q_misc_util.Helper.noError(Helper.java:460)
	at qouteall.imm_ptl.core.compat.optifine_compatibility.OFBuiltChunkStorageFix.init(OFBuiltChunkStorageFix.java:29)
	at qouteall.imm_ptl.core.IPModMainClient.init(IPModMainClient.java:133)
	at qouteall.imm_ptl.core.platform_specific.IPModEntryClient.onInitializeClient(IPModEntryClient.java:64)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectMax(II)I in imm_ptl.mixins.json:client.render.optimization.MixinChunkBuilder failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap imm_ptl_core-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 26 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.<init>(class_310.java:459)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 229636096 bytes (218 MiB) / 1071644672 bytes (1022 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
	Identifier: Intel64 Family 6 Model 126 Stepping 5
	Microarchitecture: Ice Lake (Client)
	Frequency (GHz): 1.19
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x8a56
	Graphics card #0 versionInfo: DriverVersion=27.20.100.9466
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 20301.25
	Virtual memory used (MB): 11419.71
	Swap memory total (MB): 12366.89
	Swap memory used (MB): 1609.13
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		actuallyunbreaking: Actually Unbreaking 1.17-0.2.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		ambientenvironment: Ambient Environment fabric-1.17.1-6.0.13
		amecsapi: Amecs API 1.1.5+mc21w16a
		animal_feeding_trough: Animal Feeding Trough 1.0.2
		appleskin: AppleSkin mc1.17-2.1.0
		architectury: Architectury 2.2.21
		armor_hud: BerdinskiyBear's ArmorHUD 0.3.4
		autoclicker-fabric: Auto Clicker 1.17-1.1.1-build.7
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autofish: Autofish 0.9.3
		axesareweapons: Axes Are Weapons 1.3-1.17
		backslot: BackSlot 1.1.13
		basicaiots: Basic AIOTs 1.3.1
		bno: Basic Nether Ores 1.17-6.0.0-Fabric
		bowinfinityfix: Bow Infinity Fix rv10
		cardinal-components-base: Cardinal Components API (base) 3.0.1
		cardinal-components-entity: Cardinal Components API (entities) 3.0.1
		cardinal-components-item: Cardinal Components API (items) 3.0.1
		carrier: Carrier 1.8.0
		cleancut: CleanCut 1.17-4.0-fabric
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v4 5.0.34
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		com_focamacho_sealconfig: sealconfig 1.2.2
		combatedit: CombatEdit 1.4.0
		comforts: Comforts 0.0.4-1.17
		connected-doors: Connected Doors 1.1+1.17
		controlling: Controlling For Fabric 1.1.2
		convenient-mobgriefing: Convenient mobGriefing 2.0.2
		craftable_enchanted_golden_apple: Craftable Enchanted Golden Apple 1.0.1
		crowdin-translate: CrowdinTranslate 1.3+1.17
		crusade: Crusade 1.2.4
		dark-enchanting: Dark Enchanting 0.3.1-1.17
		defaultsettings: DefaultSettings 3.0.3
		discerning_furnace: Discerning Furnace 1.0.3+MC1.17-1.17.1
		doublejump: Double Jump Mod 1.0.1+mc1.17
		easiervillagertrading: EasierVillagerTrading 1.17-fabric0.34.9-1.5.4
		emerald_tools: Emerald Tools 1.2.23
		enchantmentdescriptions: Enchantment Descriptions 3.0.12
		expanded_armor_enchanting: Expanded Armor Enchanting 1.0.1
		expanded_axe_enchanting: Expanded Axe Enchanting 1.0.2
		expanded_trident_enchanting: Expanded Trident Enchanting 1.0.2
		expanded_weapon_enchanting: Expanded Weapon Enchanting 1.0.1
		expandedstorage: Expanded Storage 7.0.0-alpha.33
		fabric: Fabric API 0.36.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b4463d5
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d03d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c03d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-furnaces: Fabric Furnaces 2.0.1-1.17
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b4463a0
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463a0
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab6121a0
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b44633d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121a0
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab6121a0
		fabricenchantments: Fabric Enchantments 0.2.3
		fabricloader: Fabric Loader 0.11.6
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fallingleaves: Falling Leaves 1.7.2+1.17
		fallingtree: FallingTree 2.12.1
		fatxporbs: Fat Experience Orbs 1.0.1
		gateofbabylon: Gate Of Babylon 1.5.0-1.17
		gbfabrictools: GBfabrictools 1.3.4+1.17
		gottaclimbfast: Gotta Climb Fast! 1.17-3.0-fabric
		greater_eye: Greater Eye of Ender 1.2.8
		grindenchantments: Grind Enchantments 1.2.1+1.17
		harvest_scythes: Harvest Scythes 2.0.5
		health_levels: Health Levels 1.0.1
		held-item-info: Held Item Info 1.2.0
		here-be-no-dragons: Here be no Dragons! 1.0.0
		iknowwhatimdoing: I Know What I'm Doing 3.0.0
		illuminations: Illuminations 1.6.3
		imm_ptl_core: Immersive Portals Core 0.10
		immersive_portals: Immersive Portals 0.10
		incantationem: Incantationem 1.1
		infinitevillagertrading: InfiniteVillagerTrading 1.17-fabric0.34.9-1.1
		inmis: Inmis 2.3.1-1.17
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		jumpoverfences: JumpOverFences 1.16-0.0.3
		ksrch: Keybind Search 1.0.0
		lapisreserve: Lapis Reserve 1.0.8
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.0.0+1.17
		libninepatch: LibNinePatch 1.1.0
		magna: Magna 1.5.5-1.17-pre4
		maybe-data: Maybe data 1.0.1-1.17
		midnightlib: MidnightLib 0.2.2
		minecraft: Minecraft 1.17
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 2.0.4
		moreberries: More Berries 1.4.2
		mostructures: Mo' Structures 1.2.1-1.17
		mousewheelie: Mouse Wheelie 1.7.3+mc1.17-rc1
		no-potion-offset: No Potion Offset ${version}
		noenchantcap: NoEnchantCap 4.1.0
		norecipebook: NoRecipeBook 2.1+1.17
		omega-config: OmegaConfig 1.0.8
		optifabric: OptiFabric 1.11.18
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		playerabilitylib: Pal 1.3.0-nightly.1.17-rc1
		prefab: Prefab 2.0.2.1
		pugh_tools: Pugh Tools ${version}
		q_misc_util: A Miscellaneous Utility Library from qouteall 0.10
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		replanter: Replanter 1.1
		rightclickharvest: Right Click Harvest 1.3.0
		ring_of_miner: Ring Of Miner 1.2.11
		ringsofascension: Rings of Ascension 1.0
		rotten: FleshZ 1.4.2
		roughlyenoughitems: Roughly Enough Items 6.0.264-alpha
		shulkerboxtooltip: Shulker Box Tooltip 3.0.1+1.17
		simple_cobblestone_generator: Simple cobblestone generator 1.1.3
		slime_sling: SlimeSling 1.0.0
		smoothboot: Smooth Boot 1.16.5-1.6.0
		smootherbedrock: Smoother Bedrock 1.0.1
		somnus: Somnus API 0.0.12-1.17
		spawnermod: Enhanced Mob Spawners 1.1.1
		speedyhopper: Speedy Hopper 1.1-1.17-1
		stackablepotions: Stackable Potions 1.0.0
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		stepup: StepUp 1.17-fabric0.34.9-1.1
		taxfreelevels: Tax Free Levels 1.2.1
		toolstats: Tool Stats 2.0.1
		tooltipfix: ToolTip Fix 1.0.3-1.16
		torohealth: ToroHealth Damage Indicators 1.17-fabric-7
		trinkets: Trinkets 3.0.0
		tweed: Tweed 3.0.0-beta.26
		vanilla-hammers: Vanilla Hammers 3.1.2-1.17
		vanillaexcavators: Vanilla Excavators 1.1.0
		vexc: Vein Excavator 1.0.0
		visualoverhaul: VisualOverhaul 3.3.0
		voxelmap: VoxelMap 1.10.15
		waystones: Waystones 2.0.1
		winged: Winged Mod 1.17-3.0.0-beta.2
		xp_storage: XP Storage 1.4.2+1.17.1
	Launched Version: fabric-loader-0.11.6-1.17
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.17_HD_U_G9_pre26
	OptiFine Build: 20210709-184608
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 0

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.17
	OptiFine jar version: OptiFine_1.17_HD_U_G9_pre26
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/iceki/Twitch/Minecraft/Instances/1.17/.optifine/OptiFine_1.17_HD_U_G9_pre26/Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by Shibva** [comment]
Did you clear out some info? The access violation is a error causes with the JVM itself and there can be some info on it that you don't want others to see

**Comment by Ynaught** [comment]
Just to follow this up. Do you guys have Dimension Stacking turned on and/or Alternate Dimensions turned on? I've had varying issues with that and am still trying to sort that out myself even now.
