### ISSUE TITLE
Crash on world load with Iris/Sodium/Indium

### ISSUE THREAD

**Issue by Schlungo** [qouteall/ImmersivePortalsMod#797]
Hiya, I think there's some crashes happening with Iris/Sodium/Indium and IP, but I can't figure out what to do about it so any help would be greatly appreciated.

On trying to load into any world, the loading reaches roughly 50% then the entire game crashes, after removing IP everything works seamlessly, I'll post the FATAL part of the log below,
Many thanks

[12:50:45] [Render thread/FATAL]: Mixin apply failed imm_ptl_sodium.mixins.json:MixinSodiumChunkProgram -> me.jellysquid.mods.sodium.client.render.chunk.shader.ChunkProgram: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Invalid descriptor on imm_ptl_sodium.mixins.json:MixinSodiumChunkProgram->@Inject::onInitEnded(Lme/jellysquid/mods/sodium/client/gl/device/RenderDevice;ILme/jellysquid/mods/sodium/client/render/chunk/shader/ChunkShaderOptions;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (Lme/jellysquid/mods/sodium/client/gl/device/RenderDevice;ILme/jellysquid/mods/sodium/client/render/chunk/shader/ChunkShaderOptions;Lnet/coderbot/iris/gl/program/ProgramUniforms;Lnet/coderbot/iris/gl/program/ProgramSamplers;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lme/jellysquid/mods/sodium/client/gl/device/RenderDevice;ILme/jellysquid/mods/sodium/client/render/chunk/shader/ChunkShaderOptions;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [INJECT Applicator Phase -> imm_ptl_sodium.mixins.json:MixinSodiumChunkProgram -> Apply Injections ->  -> Inject -> imm_ptl_sodium.mixins.json:MixinSodiumChunkProgram->@Inject::onInitEnded(Lme/jellysquid/mods/sodium/client/gl/device/RenderDevice;ILme/jellysquid/mods/sodium/client/render/chunk/shader/ChunkShaderOptions;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on imm_ptl_sodium.mixins.json:MixinSodiumChunkProgram->@Inject::onInitEnded(Lme/jellysquid/mods/sodium/client/gl/device/RenderDevice;ILme/jellysquid/mods/sodium/client/render/chunk/shader/ChunkShaderOptions;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (Lme/jellysquid/mods/sodium/client/gl/device/RenderDevice;ILme/jellysquid/mods/sodium/client/render/chunk/shader/ChunkShaderOptions;Lnet/coderbot/iris/gl/program/ProgramUniforms;Lnet/coderbot/iris/gl/program/ProgramSamplers;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lme/jellysquid/mods/sodium/client/gl/device/RenderDevice;ILme/jellysquid/mods/sodium/client/render/chunk/shader/ChunkShaderOptions;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [INJECT Applicator Phase -> imm_ptl_sodium.mixins.json:MixinSodiumChunkProgram -> Apply Injections ->  -> Inject -> imm_ptl_sodium.mixins.json:MixinSodiumChunkProgram->@Inject::onInitEnded(Lme/jellysquid/mods/sodium/client/gl/device/RenderDevice;ILme/jellysquid/mods/sodium/client/render/chunk/shader/ChunkShaderOptions;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:517) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:447) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:385) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1284) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.11.6.jar:0.9.4+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) [fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) [?:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.deletePrograms(ShaderChunkRenderer.java:245) [a142f726-b80f-471e-9da7-14d58d980d15.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.deleteAllPrograms(ShaderChunkRenderer.java:251) [a142f726-b80f-471e-9da7-14d58d980d15.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.delete(ShaderChunkRenderer.java:257) [a142f726-b80f-471e-9da7-14d58d980d15.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.delete(RegionChunkRenderer.java:154) [a142f726-b80f-471e-9da7-14d58d980d15.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.initRenderer(SodiumWorldRenderer.java:269) [a142f726-b80f-471e-9da7-14d58d980d15.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.reload(SodiumWorldRenderer.java:259) [a142f726-b80f-471e-9da7-14d58d980d15.jar:?]
	at net.minecraft.class_761.handler$cgg001$onReload(class_761.java:14119) [intermediary-1.17.jar:?]
	at net.minecraft.class_761.method_3279(class_761.java:787) [intermediary-1.17.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:49) [iris-mc1.17-1.1.0.jar:?]
	at net.minecraft.class_761.handler$cal000$iris$beginWorldRender(class_761.java:9525) [intermediary-1.17.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java) [intermediary-1.17.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1001) [intermediary-1.17.jar:?]
	at net.minecraft.class_757.redirect$zka000$redirectRenderingWorld(class_757.java:4092) [intermediary-1.17.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:806) [intermediary-1.17.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1114) [intermediary-1.17.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:730) [intermediary-1.17.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-1.17.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[12:50:45] [Render thread/FATAL]: Unreported exception thrown!
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.11.6.jar:0.9.4+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.deletePrograms(ShaderChunkRenderer.java:245) ~[a142f726-b80f-471e-9da7-14d58d980d15.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.deleteAllPrograms(ShaderChunkRenderer.java:251) ~[a142f726-b80f-471e-9da7-14d58d980d15.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.delete(ShaderChunkRenderer.java:257) ~[a142f726-b80f-471e-9da7-14d58d980d15.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.delete(RegionChunkRenderer.java:154) ~[a142f726-b80f-471e-9da7-14d58d980d15.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.initRenderer(SodiumWorldRenderer.java:269) ~[a142f726-b80f-471e-9da7-14d58d980d15.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.reload(SodiumWorldRenderer.java:259) ~[a142f726-b80f-471e-9da7-14d58d980d15.jar:?]
	at net.minecraft.class_761.handler$cgg001$onReload(class_761.java:14119) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_761.method_3279(class_761.java:787) ~[intermediary-1.17.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:49) ~[iris-mc1.17-1.1.0.jar:?]
	at net.minecraft.class_761.handler$cal000$iris$beginWorldRender(class_761.java:9525) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1001) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_757.redirect$zka000$redirectRenderingWorld(class_757.java:4092) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:806) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1114) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:730) [intermediary-1.17.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-1.17.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [imm_ptl_sodium.mixins.json:MixinSodiumChunkProgram] from phase [DEFAULT] in config [imm_ptl_sodium.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	... 30 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on imm_ptl_sodium.mixins.json:MixinSodiumChunkProgram->@Inject::onInitEnded(Lme/jellysquid/mods/sodium/client/gl/device/RenderDevice;ILme/jellysquid/mods/sodium/client/render/chunk/shader/ChunkShaderOptions;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (Lme/jellysquid/mods/sodium/client/gl/device/RenderDevice;ILme/jellysquid/mods/sodium/client/render/chunk/shader/ChunkShaderOptions;Lnet/coderbot/iris/gl/program/ProgramUniforms;Lnet/coderbot/iris/gl/program/ProgramSamplers;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lme/jellysquid/mods/sodium/client/gl/device/RenderDevice;ILme/jellysquid/mods/sodium/client/render/chunk/shader/ChunkShaderOptions;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [INJECT Applicator Phase -> imm_ptl_sodium.mixins.json:MixinSodiumChunkProgram -> Apply Injections ->  -> Inject -> imm_ptl_sodium.mixins.json:MixinSodiumChunkProgram->@Inject::onInitEnded(Lme/jellysquid/mods/sodium/client/gl/device/RenderDevice;ILme/jellysquid/mods/sodium/client/render/chunk/shader/ChunkShaderOptions;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:517) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:447) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:385) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1284) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	... 30 more
[12:50:46] [Server thread/INFO]: Stopping server

**Comment by qouteall** [comment]
IP is not compatible with Iris until the pr gets merged. Duplicate to https://github.com/qouteall/ImmersivePortalsMod/issues/648
