### ISSUE TITLE
[All Of Fabric 4] Crash after "teleportation.CrossPortalSound.createPortalSound() - java:50"

### ISSUE THREAD

**Issue by TeoNikolov** [qouteall/ImmersivePortalsMod#798]
> Provide instructions for how to reproduce the issue. Include the minecraft version and mod version.

I'm running this on Minecraft 1.17.1 with the 'All Of Fabric 4-0.0.7' mod via CurseForge. I also added the following mods to that:

- extraalchemy-fabric-1.17-1.5.1.jar
- immersive-portals-0.15-mc1.17.1-fabric.jar
- BetterThirdPerson-Fabric-1.17-1.5.0.jar

Suddenly my friend and I experienced a crash on our server simultaneously (server was left intact). Here is the [full crash log pastebin](https://pastebin.com/2uCX3tjF) and just the stacktrace:

> java.lang.IllegalArgumentException: too big
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:159)
	at qouteall.imm_ptl.core.McHelper.foreachEntities(McHelper.java:408)
	at qouteall.imm_ptl.core.McHelper.findEntities(McHelper.java:381)
	at qouteall.imm_ptl.core.McHelper.findEntitiesRough(McHelper.java:444)
	at qouteall.imm_ptl.core.McHelper.getServerEntitiesNearbyWithoutLoadingChunk(McHelper.java:284)
	at qouteall.imm_ptl.core.IPMcHelper.getNearbyPortals(IPMcHelper.java:41)
	at qouteall.imm_ptl.core.teleportation.CrossPortalSound.createCrossPortalSound(CrossPortalSound.java:50)
	at net.minecraft.class_638.handler$zmf000$onPlaySound(class_638.java:2047)
	at net.minecraft.class_638.method_8486(class_638.java)
	at net.minecraft.class_1538.method_5773(class_1538.java:90)
	at net.minecraft.class_638.method_18646(class_638.java:179)
	at net.minecraft.class_1937.method_18472(class_1937.java:483)
	at net.minecraft.class_638.method_32124(class_638.java:167)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:163)
	at net.minecraft.class_310.method_1574(class_310.java:1750)
	at net.minecraft.class_310.method_1523(class_310.java:1081)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

At the moment I am not sure how to reproduce this issue. However, I dug through the code and it seems that the issue has something to do with the soundVol passed to the createCrossPortalSound() function. Maybe it has something to do with the Minecraft sound settings since I cannot see the other functions without digging through the Minecraft codebase. I think the handling of the sound value (and ultimately the 'isTrue' verification in the last function call) should be changed to account for this.

Apologies if this is a duplicate. I could not find another one on here.

**Comment by qouteall** [comment]
Probably fixed in this version https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.16-1.17

**Comment by TeoNikolov** [comment]
Hopefully that does it, cheers!
In the meantime I'll see if I could make it reproducible to verify later.

Edit: I managed to reproduce the issue by summoning a lightning strike ~100 blocks away from me on 0.15. I applied the 0.16 pre-release and the crash did not occur, so the issue can probably be closed @qouteall
