### ISSUE TITLE
Bug on Server 1.16

### ISSUE THREAD

**Issue by K3llerk1nd98** [qouteall/ImmersivePortalsMod#824]
[12:46:18 INFO]: Preparing level "world"
[12:46:18 INFO]: [FabricRegistrySync] [fabric-registry-sync] Loaded registry data [file 1/4]
[12:46:23 ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception generating new chunk
at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:2202) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:2020) ~[intermediary-server.jar:?]
at net.minecraft.class_3176.method_3823(class_3176.java:179) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
at net.minecraft.server.MinecraftServer.method_3767(MinecraftServer.java:1463) ~[intermediary-server.jar:?]
at com.qouteall.imm_ptl_peripheral.altius_world.AltiusGameRule.getIsDimensionStack(AltiusGameRule.java:33) ~[immersive-portals-0.78-mc1.16.5-fabric.jar:?]
at com.qouteall.imm_ptl_peripheral.altius_world.AltiusInfo.replaceBedrock(AltiusInfo.java:97) ~[immersive-portals-0.78-mc1.16.5-fabric.jar:?]
at net.minecraft.class_2806.handler$zgk000$redirectBuildSurface(class_2806.java:529) ~[intermediary-server.jar:?]
at net.minecraft.class_2806.method_16567(class_2806.java:75) ~[intermediary-server.jar:?]
at net.minecraft.class_2806$class_3768.doWork(class_2806.java:263) ~[intermediary-server.jar:?]
at net.minecraft.class_2806.method_12154(class_2806.java:219) ~[intermediary-server.jar:?]
at net.minecraft.class_3898.method_17225(class_3898.java:568) ~[intermediary-server.jar:?]
at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[intermediary-server.jar:?]
at net.minecraft.class_3898.method_17224(class_3898.java:562) ~[intermediary-server.jar:?]
at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_211]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_211]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_211]
at net.minecraft.class_3900.method_17634(class_3900.java:58) ~[intermediary-server.jar:?]
at net.minecraft.class_3846.method_16907(class_3846.java:94) ~[intermediary-server.jar:?]
at net.minecraft.class_3846.method_16900(class_3846.java:137) ~[intermediary-server.jar:?]
at net.minecraft.class_3846.run(class_3846.java:105) ~[intermediary-server.jar:?]
at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_211]
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_211]
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_211]
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_211]
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_211]
[12:46:23 ERROR]: This crash report has been saved to: /home/zap62238/g691/fabric/./crash-reports/crash-2021-08-19_12.46.23-server.txt
[12:46:23 INFO]: [WorldEdit] Disabling WorldEdit v7.2.6-beta-02+2e45a20
[12:46:23 INFO]: Unregistering com.sk89q.worldedit.bukkit.BukkitServerInterface from WorldEdit
[12:46:23 INFO]: Stopping server
[12:46:23 INFO]: Saving players
[12:46:23 INFO]: Saving worlds

**Comment by qouteall** [comment]
Post the full crash report. Are you using Cardboard?

**Comment by K3llerk1nd98** [comment]
Yeah issue come with Cardboard. 
log sending later

**Comment by K3llerk1nd98** [comment]
Got it working with some earlier version for 1.16. but in 1.17 still a lot of errors there..

**Comment by qouteall** [comment]
Duplicate to https://github.com/qouteall/ImmersivePortalsMod/issues/501
