### ISSUE TITLE
Incompatible with multiconnect

### ISSUE THREAD

**Issue by Justsnoopy30** [qouteall/ImmersivePortalsMod#834]
Minecraft Version: 1.17.1
Immersive Portals Commit: b6117d4

The conflicting mod's GitHub: https://github.com/Earthcomputer/multiconnect
Mixin conflict, log here:
`[02:25:05] [Render thread/WARN]: @Redirect conflict. Skipping multiconnect.1_12_2.mixins.json:MixinClientPlayerInteractionManager->@Redirect::cancelInteractBlockPacket(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 1000, already redirected by imm_ptl.mixins.json:client.block_manipulation.MixinClientPlayerInteractionManager->@Redirect::redirectSendPacketOnInteractBlock(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 1000
[02:25:06] [Render thread/FATAL]: Unreported exception thrown!
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[universe-loader-0.11.6.jar:0.9.4+mixin.0.8.2]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[universe-loader-0.11.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[universe-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.minecraft.class_634.method_11120(class_634.java:344) ~[intermediary-universe-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_2678.method_11567(class_2678.java:100) ~[intermediary-universe-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_2678.method_11054(class_2678.java:18) ~[intermediary-universe-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-universe-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-universe-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-universe-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-universe-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) ~[intermediary-universe-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1075) ~[intermediary-universe-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-universe-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-universe-fabric-loader-0.11.6-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [universe-loader-0.11.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:65) [universe-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [universe-loader-0.11.6.jar:?]
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector cancelInteractBlockPacket(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V in multiconnect.1_12_2.mixins.json:MixinClientPlayerInteractionManager failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap multiconnect-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	... 24 more`
And crash report generated:
`org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.class_634.method_11120(class_634.java:344)
	at net.minecraft.class_2678.method_11567(class_2678.java:100)
	at net.minecraft.class_2678.method_11054(class_2678.java:18)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_1255.method_18859(class_1255.java:151)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:125)
	at net.minecraft.class_1255.method_5383(class_1255.java:110)
	at net.minecraft.class_310.method_1523(class_310.java:1075)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:65)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector cancelInteractBlockPacket(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V in multiconnect.1_12_2.mixins.json:MixinClientPlayerInteractionManager failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap multiconnect-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 24 more`

**Comment by Justsnoopy30** [comment]
Associated issue report: https://github.com/Earthcomputer/multiconnect/issues/236

**Comment by Earthcomputer** [comment]
Even if this was fixed, there are more fundamental problems running immersive portals and multiconnect together, as immersive portals changes the protocol, and the assumption that there is only one world (as clearly stated in the readme). If the immersive portals dev is willing to fix this let me know, but be prepared for a lot of head banging on wall, it won't be fun at all. The next version of multiconnect will specify immersive portals in its `breaks` block in `fabric.mod.json`.

**Comment by Earthcomputer** [comment]
Turns out there is a limited usecase for using the two mods together, and it sorta kinda works apparently, so I'll look into fixing the redirect.

**Comment by Earthcomputer** [comment]
https://github.com/qouteall/ImmersivePortalsMod/pull/836
