### ISSUE TITLE
Crash with Lithium

### ISSUE THREAD

**Issue by bleonard252** [qouteall/ImmersivePortalsMod#866]
* Minecraft version: 1.17.1
* IP Version: 0.28

<details><summary>Other installed mods</summary>
<pre>
	- cloth-basic-math 0.5.1
	- cloth-config2 5.0.34
	- com_fasterxml_jackson_dataformat_jackson-dataformat-yaml 2.12.2
	- craftpresence 1.8.8
	- dashloader 2.0.1
	- ec-core 1.0.0-mc1.17.1
	- essential_commands 0.16.2-mc1.17.1
	- fabric 0.40.8+1.17
	- fabric-api-base 0.3.0+a02b446318
	- fabric-api-lookup-api-v1 1.3.0+cbda931818
	- fabric-biome-api-v1 3.2.0+cbda931818
	- fabric-blockrenderlayer-v1 1.1.5+a02b446318
	- fabric-command-api-v1 1.1.3+5ab9934c18
	- fabric-commands-v0 0.2.2+92519afa18
	- fabric-containers-v0 0.1.12+cbda931818
	- fabric-content-registries-v0 0.3.0+cbda931818
	- fabric-crash-report-info-v1 0.1.5+be9da31018
	- fabric-dimensions-v1 2.0.11+6cefd57718
	- fabric-entity-events-v1 1.2.3+87cc6e4c18
	- fabric-events-interaction-v0 0.4.10+fc40aa9d18
	- fabric-events-lifecycle-v0 0.2.1+92519afa18
	- fabric-game-rule-api-v1 1.0.7+cbda931818
	- fabric-item-api-v1 1.2.4+cbda931818
	- fabric-item-groups-v0 0.2.10+b7ab612118
	- fabric-key-binding-api-v1 1.0.4+cbda931818
	- fabric-keybindings-v0 0.2.2+36b77c3e18
	- fabric-lifecycle-events-v1 1.4.4+a02b446318
	- fabric-loot-tables-v1 1.0.4+a02b446318
	- fabric-mining-levels-v0 0.1.3+92519afa18
	- fabric-models-v0 0.3.0+a02b446318
	- fabric-networking-api-v1 1.0.13+cbda931818
	- fabric-networking-blockentity-v0 0.2.11+a02b446318
	- fabric-networking-v0 0.3.2+92519afa18
	- fabric-object-builder-api-v1 1.10.9+cbda931818
	- fabric-object-builders-v0 0.7.3+a02b446318
	- fabric-particles-v1 0.2.4+a02b446318
	- fabric-permissions-api-v0 0.1-SNAPSHOT
	- fabric-registry-sync-v0 0.7.11+7931163218
	- fabric-renderer-api-v1 0.4.4+cbda931818
	- fabric-renderer-indigo 0.4.8+cbda931818
	- fabric-renderer-registries-v1 3.2.4+7931163218
	- fabric-rendering-data-attachment-v1 0.1.5+a02b446318
	- fabric-rendering-fluids-v1 0.1.14+4658223018
	- fabric-rendering-v0 1.1.5+7931163218
	- fabric-rendering-v1 1.9.0+7931163218
	- fabric-resource-loader-v0 0.4.8+a00e834b18
	- fabric-screen-api-v1 1.0.4+cbda931818
	- fabric-screen-handler-api-v1 1.1.8+cbda931818
	- fabric-structure-api-v1 1.1.13+5ab9934c18
	- fabric-tag-extensions-v0 1.2.1+b06cb95b18
	- fabric-textures-v0 1.0.6+a02b446318
	- fabric-tool-attribute-api-v1 1.2.12+b7ab612118
	- fabric-transfer-api-v1 1.4.0+7931163218
	- fabricloader 0.12.1
	- imm_ptl_core 0.28
	- immersive_portals 0.28
	- io_activej_activej-codegen 4.3
	- io_activej_activej-serializer 4.3
	- java 16
	- lithium 0.7.4
	- minecraft 1.17.1
	- modmenu 2.0.14
	- org_slf4j_slf4j-api 1.7.29
	- org_yaml_snakeyaml 1.27
	- placeholder-api 1.1.0+1.17.1
	- playerabilitylib 1.3.0
	- q_misc_util 0.28
	- xaerominimapfair 21.18.0
	- xaeroworldmap 1.17.2
</pre></details>

When attempting to load into a Fabric server, the game crashes. It started doing this immediately after I ran `/portal global connect_ceil minecraft:overworld immersive_portals:alternate2`, and I was far from spawn at about y=237. After that first crash, the world refuses to render. The server runs without any errors or problems, and for a few seconds before the client tries to render the terrain, I can run commands from the server console on my account, including teleporting. However, even deleting the player data doesn't seem to work.

## The error
```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 10/15/21, 5:06 PM
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "qouteall.imm_ptl.core.ducks.IEShader.ip_getClippingEquationUniform()" because "shader" is null
```
<details>

```
	at qouteall.imm_ptl.core.render.FrontClipping.updateClippingEquationUniformForCurrentShader(FrontClipping.java:156)
	at com.mojang.blaze3d.systems.RenderSystem.handler$zmm000$onSetShader(RenderSystem.java:1384)
	at com.mojang.blaze3d.systems.RenderSystem.setShader(RenderSystem.java:1139)
	at qouteall.imm_ptl.core.render.ViewAreaRenderer.renderPortalArea(ViewAreaRenderer.java:72)
	at qouteall.imm_ptl.core.render.RendererUsingStencil.renderPortalViewAreaToStencil(RendererUsingStencil.java:189)
	at qouteall.imm_ptl.core.render.RendererUsingStencil.lambda$doRenderPortal$0(RendererUsingStencil.java:122)
	at qouteall.imm_ptl.core.render.GlQueryObject.performQuery(GlQueryObject.java:42)
	at qouteall.imm_ptl.core.render.GlQueryObject.performQueryAnySamplePassed(GlQueryObject.java:26)
	at qouteall.imm_ptl.core.portal.PortalRenderInfo.renderAndDecideVisibility(PortalRenderInfo.java:231)
	at qouteall.imm_ptl.core.render.RendererUsingStencil.doRenderPortal(RendererUsingStencil.java:121)
	at qouteall.imm_ptl.core.render.PortalRenderer.renderPortals(PortalRenderer.java:111)
	at qouteall.imm_ptl.core.render.RendererUsingStencil.doPortalRendering(RendererUsingStencil.java:58)
	at qouteall.imm_ptl.core.render.RendererUsingStencil.onBeforeTranslucentRendering(RendererUsingStencil.java:49)
	at net.minecraft.class_761.handler$zmp000$onBeforeTranslucentRendering(class_761.java:4902)
	at net.minecraft.class_761.method_22710(class_761.java:1378)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.redirect$zmj000$redirectRenderingWorld(class_757.java:3622)
	at net.minecraft.class_757.method_3192(class_757.java:810)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at qouteall.imm_ptl.core.render.FrontClipping.updateClippingEquationUniformForCurrentShader(FrontClipping.java:156)
	at com.mojang.blaze3d.systems.RenderSystem.handler$zmm000$onSetShader(RenderSystem.java:1384)
	at com.mojang.blaze3d.systems.RenderSystem.setShader(RenderSystem.java:1139)
	at qouteall.imm_ptl.core.render.ViewAreaRenderer.renderPortalArea(ViewAreaRenderer.java:72)
	at qouteall.imm_ptl.core.render.RendererUsingStencil.renderPortalViewAreaToStencil(RendererUsingStencil.java:189)
	at qouteall.imm_ptl.core.render.RendererUsingStencil.lambda$doRenderPortal$0(RendererUsingStencil.java:122)
	at qouteall.imm_ptl.core.render.GlQueryObject.performQuery(GlQueryObject.java:42)
	at qouteall.imm_ptl.core.render.GlQueryObject.performQueryAnySamplePassed(GlQueryObject.java:26)
	at qouteall.imm_ptl.core.portal.PortalRenderInfo.renderAndDecideVisibility(PortalRenderInfo.java:231)
	at qouteall.imm_ptl.core.render.RendererUsingStencil.doRenderPortal(RendererUsingStencil.java:121)
	at qouteall.imm_ptl.core.render.PortalRenderer.renderPortals(PortalRenderer.java:111)
	at qouteall.imm_ptl.core.render.RendererUsingStencil.doPortalRendering(RendererUsingStencil.java:58)
	at qouteall.imm_ptl.core.render.RendererUsingStencil.onBeforeTranslucentRendering(RendererUsingStencil.java:49)
	at net.minecraft.class_761.handler$zmp000$onBeforeTranslucentRendering(class_761.java:4902)
	at net.minecraft.class_761.method_22710(class_761.java:1378)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.redirect$zmj000$redirectRenderingWorld(class_757.java:3622)

-- Affected level --
Details:
	All players: 1 total; [class_746['fleshroots'/1330, l='ClientWorld minecraft:overworld', x=-994.67, y=176.17, z=153.49]]
	Chunk stats: Client Chunks (ImmPtl) 479
	Level dimension: minecraft:overworld
	Level spawn location: World: (96,76,-240), Section: (at 0,12,0 in 6,4,-15; chunk contains blocks 96,0,-240 to 111,255,-225), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 157158 game time, 6147 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, amethystsmp.zip, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Microsoft
	Memory: 692843872 bytes (660 MiB) / 2619342848 bytes (2498 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
	Identifier: Intel64 Family 6 Model 126 Stepping 5
	Microarchitecture: Ice Lake (Client)
	Frequency (GHz): 1.19
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x8a56
	Graphics card #0 versionInfo: DriverVersion=27.20.100.9365
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 16229.39
	Virtual memory used (MB): 14098.68
	Swap memory total (MB): 8269.92
	Swap memory used (MB): 1893.01
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.12.2
		craftpresence: CraftPresence 1.8.8
		dashloader: DashLoader 2.0.1
		ec-core: Essential Commands Core 1.0.0-mc1.17.1
		essential_commands: Essential Commands 0.16.2-mc1.17.1
		fabric: Fabric API 0.40.8+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+87cc6e4c18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931818
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+cbda931818
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931818
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.11+7931163218
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+cbda931818
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931818
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.4+7931163218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.5+7931163218
		fabric-rendering-v1: Fabric Rendering (v1) 1.9.0+7931163218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+cbda931818
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.0+7931163218
		fabricloader: Fabric Loader 0.12.1
		imm_ptl_core: Immersive Portals Core 0.28
		immersive_portals: Immersive Portals 0.28
		io_activej_activej-codegen: activej-codegen 4.3
		io_activej_activej-serializer: activej-serializer 4.3
		java: OpenJDK 64-Bit Server VM 16
		lithium: Lithium 0.7.4
		minecraft: Minecraft 1.17.1
		modmenu: Mod Menu 2.0.14
		org_slf4j_slf4j-api: slf4j-api 1.7.29
		org_yaml_snakeyaml: snakeyaml 1.27
		placeholder-api: Placeholder API 1.1.0+1.17.1
		playerabilitylib: Pal 1.3.0
		q_misc_util: A Miscellaneous Utility Library from qouteall 0.28
		xaerominimapfair: Xaero's Minimap 21.18.0
		xaeroworldmap: Xaero's World Map 1.17.2
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics GL version 3.2.0 - Build 27.20.100.9365, Intel
	Window size: 1366x745
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/amethystsmp.zip, Fabric Mods
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
```

</details>

**Comment by bleonard252** [comment]
Update: this appears to be a compatibility error with Lithium, as disabling it allowed me to load into the world. I'll check if one of Lithium's patches can be turned off to resolve this error, and if not, see if the issue has already been raised. I'll close the thread when that's done :)

edit: I've combed through IP's issues, and it doesn't seem like there's anything mentioning this issue. If I'm wrong don't hesitate to correct me, but I'll leave this up in case it's actually a real bug (probably just a lithium configuration change) after all

**Comment by qouteall** [comment]
Close because outdated.
