### ISSUE TITLE
Alternate 3/4 does not work with some worldgen mods?

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#913]
```
java.lang.IllegalStateException: Feature order cycle found, involved biomes: [net.minecraft.class_1959@24527435, net.minecraft.class_1959@6d778e3f]
    at net.minecraft.class_1966.method_39525(class_1966.java:130)
    at net.minecraft.class_1966.<init>(class_1966.java:65)
    at qouteall.imm_ptl.peripheral.alternate_dimension.ChaosBiomeSource.<init>(ChaosBiomeSource.java:26)
    at qouteall.imm_ptl.peripheral.alternate_dimension.AlternateDimensions.createErrorTerrainGenerator(AlternateDimensions.java:225)
    at qouteall.imm_ptl.peripheral.alternate_dimension.AlternateDimensions.initializeAlternateDimensions(AlternateDimensions.java:92)
    at qouteall.q_misc_util.api.DimensionAPI.lambda$static$0(DimensionAPI.java:36)
    at net.minecraft.server.MinecraftServer.handler$ckh000$onBeforeCreateWorlds(MinecraftServer.java:7252)
    at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java)
    at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:327)
    at net.minecraft.class_3176.method_3823(class_3176.java:182)
    at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:657)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by qouteall** [comment]
Probably fixed
