### ISSUE TITLE
V1.1.2 for 1.18 incompatible with c2me

### ISSUE THREAD

**Issue by Joulanh** [qouteall/ImmersivePortalsMod#938]
Mods:
IP1.1.2
fabric api-0.44.0
c2me-fabric-mc1.18.1-0.2.0+alpha.5.108
https://github.com/RelativityMC/C2ME-fabric

Starting a dedicated server with those 3 Mods installed crashes the server on startup
[crash-2021-12-21_20.04.40-server.txt](https://github.com/qouteall/ImmersivePortalsMod/files/7757495/crash-2021-12-21_20.04.40-server.txt)

**Comment by qouteall** [comment]
You can disable alternate dimensions to avoid crash for now.

**Comment by qouteall** [comment]
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2794.method_38276()" because "this.delegate" is null
	at qouteall.imm_ptl.peripheral.alternate_dimension.DelegatedChunkGenerator.method_38276(DelegatedChunkGenerator.java:53)
	at net.minecraft.class_2794.handler$zzj001$onInit(class_2794.java:1598)
	at net.minecraft.class_2794.<init>(class_2794.java:96)
	at net.minecraft.class_2794.<init>(class_2794.java:88)
	at qouteall.imm_ptl.peripheral.alternate_dimension.DelegatedChunkGenerator.<init>(DelegatedChunkGenerator.java:32)
	at qouteall.imm_ptl.peripheral.alternate_dimension.DelegatedChunkGenerator$SpecialNoise.<init>(DelegatedChunkGenerator.java:112)
	at qouteall.imm_ptl.peripheral.alternate_dimension.AlternateDimensions.createSkylandGenerator(AlternateDimensions.java:216)
	at qouteall.imm_ptl.peripheral.alternate_dimension.AlternateDimensions.initializeAlternateDimensions(AlternateDimensions.java:73)
	at qouteall.q_misc_util.api.DimensionAPI.lambda$static$0(DimensionAPI.java:36)
	at net.minecraft.server.MinecraftServer.handler$zll000$onBeforeCreateWorlds(MinecraftServer.java:4752)
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:327)
	at net.minecraft.class_3176.method_3823(class_3176.java:182)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:657)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by qouteall** [comment]
https://github.com/RelativityMC/C2ME-fabric/blob/57a17da56de6be2d537374848ac288ddd7d16ba1/src/main/java/com/ishland/c2me/mixin/fixes/worldgen/threading/MixinChunkGenerator.java#L28

**Comment by qouteall** [comment]
I can make a workaround to avoid the crash in the new version. But there may be other incompatibilities

**Comment by Joulanh** [comment]
I will go with disabling alternate dimensions for now since im not using them anyway. Ill report back if i notice anything else.

**Comment by copygirl** [comment]
Just wanted to add what I collected: Still crashes after disabling alternate dimensions. The issue on C2ME's tracker also has [a comment](https://github.com/RelativityMC/C2ME-fabric/issues/89#issuecomment-1019681664) with a similar crash posted. Will just provide my log in case it helps: https://gist.github.com/copygirl/cfe72faa7ee3334bd1286f80d5313ea0

```
[14:45:42] [Render thread/ERROR]: Mixin apply for mod c2me failed c2me.mixins.json:notickvd.MixinThreadedAnvilChunkStorage from mod c2me -> net.minecraft.class_3898: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_3898::redirectSendWatchPacketsGetWorldChunk with priority 1100 cannot inject into net/minecraft/class_3898::method_17241(Lnet/minecraft/class_3222;Lnet/minecraft/class_1923;Lorg/apache/commons/lang3/mutable/MutableObject;ZZ)V merged by qouteall.imm_ptl.core.mixin.common.chunk_sync.MixinChunkMap_C with priority 1100 [PREINJECT Applicator Phase -> c2me.mixins.json:notickvd.MixinThreadedAnvilChunkStorage from mod c2me -> Prepare Injections ->  -> redirect$zkh000$redirectSendWatchPacketsGetWorldChunk(Lnet/minecraft/class_3193;)Lnet/minecraft/class_2818; -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_3898::redirectSendWatchPacketsGetWorldChunk with priority 1100 cannot inject into net/minecraft/class_3898::method_17241(Lnet/minecraft/class_3222;Lnet/minecraft/class_1923;Lorg/apache/commons/lang3/mutable/MutableObject;ZZ)V merged by qouteall.imm_ptl.core.mixin.common.chunk_sync.MixinChunkMap_C with priority 1100 [PREINJECT Applicator Phase -> c2me.mixins.json:notickvd.MixinThreadedAnvilChunkStorage from mod c2me -> Prepare Injections ->  -> redirect$zkh000$redirectSendWatchPacketsGetWorldChunk(Lnet/minecraft/class_3193;)Lnet/minecraft/class_2818; -> Prepare]
[...]
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_3898::redirectSendWatchPacketsGetWorldChunk with priority 1100 cannot inject into net/minecraft/class_3898::method_17241(Lnet/minecraft/class_3222;Lnet/minecraft/class_1923;Lorg/apache/commons/lang3/mutable/MutableObject;ZZ)V merged by qouteall.imm_ptl.core.mixin.common.chunk_sync.MixinChunkMap_C with priority 1100 [PREINJECT Applicator Phase -> c2me.mixins.json:notickvd.MixinThreadedAnvilChunkStorage from mod c2me -> Prepare Injections ->  -> redirect$zkh000$redirectSendWatchPacketsGetWorldChunk(Lnet/minecraft/class_3193;)Lnet/minecraft/class_2818; -> Prepare]
```

I might be able to do some basic testing if needed.
