### ISSUE TITLE
Rendering errors

### ISSUE THREAD

**Issue by GdXyhd** [qouteall/ImmersivePortalsMod#944]
Start a new world, Go to creative and the game froze instantly in any game mode after walking around for a bit.

**Comment by qouteall** [comment]
It may be a mod compatibility issue. Does this issue occur with only immptl and fabric api?

**Comment by PilaScat** [comment]
updated from 1.1.4 to 1.1.7 and this appens every time near a portal (using sodium and iris, before it worked)
```
java.lang.NullPointerException: Cannot read field "field_29470" because "shader" is null
	at qouteall.imm_ptl.core.render.ViewAreaRenderer.renderPortalArea(ViewAreaRenderer.java:74)
	at qouteall.imm_ptl.core.render.RendererUsingStencil.renderPortalViewAreaToStencil(RendererUsingStencil.java:189)
	at qouteall.imm_ptl.core.render.RendererUsingStencil.lambda$doRenderPortal$0(RendererUsingStencil.java:122)
	at qouteall.imm_ptl.core.render.GlQueryObject.performQuery(GlQueryObject.java:42)
	at qouteall.imm_ptl.core.render.GlQueryObject.performQueryAnySamplePassed(GlQueryObject.java:26)
	at qouteall.imm_ptl.core.portal.PortalRenderInfo.renderAndDecideVisibility(PortalRenderInfo.java:230)
	at qouteall.imm_ptl.core.render.RendererUsingStencil.doRenderPortal(RendererUsingStencil.java:121)
	at qouteall.imm_ptl.core.render.PortalRenderer.renderPortals(PortalRenderer.java:110)
	at qouteall.imm_ptl.core.render.RendererUsingStencil.doPortalRendering(RendererUsingStencil.java:58)
	at qouteall.imm_ptl.core.render.RendererUsingStencil.onBeforeTranslucentRendering(RendererUsingStencil.java:49)
	at net.minecraft.class_761.handler$bdc000$onBeforeTranslucentRendering(class_761.java:7521)
	at net.minecraft.class_761.method_22710(class_761.java:1473)
	at net.minecraft.class_757.method_3188(class_757.java:1031)
	at net.minecraft.class_757.redirect$bcl000$redirectRenderingWorld(class_757.java:4131)
	at net.minecraft.class_757.method_3192(class_757.java:811)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by qouteall** [comment]
@PilaScat Are you using altoclef? Immptl is incompatible with it.

**Comment by PilaScat** [comment]
It was dimensional threading, I removed it and now it worksFilippo ScatignaOn 30 Dec 2021 08:14, qouteall ***@***.***> wrote:
Are you using altoclef? Immptl is incompatible with it.

**Comment by luni3359** [comment]
> It was dimensional threading, I removed it and now it works

I had the same issue, but removing Dimensional Threading only helped inconsistently. Subsequent attempts to load the world resulted in the same crash.

I'm also running the latest Iris (1.1.4) and Sodium (0.4.0-alpha5+build.9). Minecraft 1.18.1.
<details>
<summary>Mod list</summary>

Dimensional Threading 1.2.6
entityculling 1.3.3
iris 1.1.4 (currently not using any shaders) 
lazydfu 0.1.2
lithium 0.7.7
sodium 0.4.0-alpha5+build.9
starlight 1.0.0
lambdynamiclight 2.1.0
wthit 4.4.1
Xaero's Minimap 21.23.0
Xaero's World Map 1.19.0
dynamic sound filters 1.3.0
</details>

<details>
<summary>Mods I removed to test but still caused crashes</summary>

Dimensional Threading 1.2.6
entityculling 1.3.3
</details>

```
[13:12:12] [Render thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: Cannot read field "field_29470" because "shader" is null
	at qouteall.imm_ptl.core.render.ViewAreaRenderer.renderPortalArea(ViewAreaRenderer.java:74) ~[imm_ptl_core-1.1.8-acc503312511a8e9.jar:?]
	at qouteall.imm_ptl.core.render.RendererUsingStencil.renderPortalViewAreaToStencil(RendererUsingStencil.java:189) ~[imm_ptl_core-1.1.8-acc503312511a8e9.jar:?]
	at qouteall.imm_ptl.core.render.RendererUsingStencil.lambda$doRenderPortal$0(RendererUsingStencil.java:122) ~[imm_ptl_core-1.1.8-acc503312511a8e9.jar:?]
	at qouteall.imm_ptl.core.render.GlQueryObject.performQuery(GlQueryObject.java:42) ~[imm_ptl_core-1.1.8-acc503312511a8e9.jar:?]
	at qouteall.imm_ptl.core.render.GlQueryObject.performQueryAnySamplePassed(GlQueryObject.java:26) ~[imm_ptl_core-1.1.8-acc503312511a8e9.jar:?]
	at qouteall.imm_ptl.core.portal.PortalRenderInfo.renderAndDecideVisibility(PortalRenderInfo.java:230) ~[imm_ptl_core-1.1.8-acc503312511a8e9.jar:?]
	at qouteall.imm_ptl.core.render.RendererUsingStencil.doRenderPortal(RendererUsingStencil.java:121) ~[imm_ptl_core-1.1.8-acc503312511a8e9.jar:?]
	at qouteall.imm_ptl.core.render.PortalRenderer.renderPortals(PortalRenderer.java:110) ~[imm_ptl_core-1.1.8-acc503312511a8e9.jar:?]
	at qouteall.imm_ptl.core.render.RendererUsingStencil.doPortalRendering(RendererUsingStencil.java:58) ~[imm_ptl_core-1.1.8-acc503312511a8e9.jar:?]
	at qouteall.imm_ptl.core.render.RendererUsingStencil.onBeforeTranslucentRendering(RendererUsingStencil.java:49) ~[imm_ptl_core-1.1.8-acc503312511a8e9.jar:?]
	at net.minecraft.class_761.handler$zpk000$onBeforeTranslucentRendering(class_761.java:7021) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1473) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1031) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.redirect$zpd000$redirectRenderingWorld(class_757.java:4131) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:811) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1117) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
```

**Comment by qouteall** [comment]
@luni3359 Does it crash after removing Xaero's Minimap, Xaero's World Map, starlight?

**Comment by luni3359** [comment]
Yes. Even without them I'm still getting that shader error.
>The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot read field "field_29470" because "shader" is null
終了コード：255

I did further testing, and it turns out it was Dashloader's fault, a mod that I hadn't included. Absolutely every other mod I thought was a problem works flawlessly, but Dashloader's mod caching causes issues. I suppose the other users are also using Dashloader since the error is similar, and the crash happens in the same way.

**Comment by GdXyhd** [comment]
I don't have shaders or any fps boosts, Only Fabric API and this mod.

**Comment by qouteall** [comment]
@luni3359 issue moved to https://github.com/qouteall/ImmersivePortalsMod/issues/960

**Comment by qouteall** [comment]
@GdXyhd are you using mc 1.18.1 and the latest version of immptl? If so post the log (`.minecraft/logs/latest.log`)

**Comment by GdXyhd** [comment]
> @GdXyhd are you using mc 1.18.1 and the latest version of immptl? If so post the log (`.minecraft/logs/latest.log`)

Yes, I have been using the latest version of immptl and minecraft

**Comment by qouteall** [comment]
@GdXyhd It may be a mod compatibility issue. Does the issue occur with only immptl and fabric api?

**Comment by GdXyhd** [comment]
> @GdXyhd It may be a mod compatibility issue. Does the issue occur with only immptl and fabric api?

Yes I only use immptl and fabric API.
(Note: I am in 21' mac )

**Comment by qouteall** [comment]
Can you reproduce the issue with the latest version of immptl and post the log? (The log is `.minecraft/logs/latest.log`)

**Comment by qouteall** [comment]
Close because outdated.
